// meshchatx/src/frontend/features/rnpath/RNPathPage.svelte
<!-- SPDX-License-Identifier: 0BSD -->

<script lang="ts">
    import { onMount } from "svelte";
    import { fade } from "svelte/transition";
    import MaterialDesignIcon from "../../ui/svelte/MaterialDesignIcon.svelte";
    import ToolsPageHeader from "../../ui/svelte/ToolsPageHeader.svelte";
    import ToastUtils from "../../js/ToastUtils.js";
    import DialogUtils from "../../js/DialogUtils.js";
    import { t } from "../../js/i18n.js";
    import { DEFAULT_REMOTE_TIMEOUT, DEFAULT_ITEMS_PER_PAGE, RNPATH_TABS } from "./lib/constants.js";
    import { buildPathQueryParams, buildRemoteQueryParams, extractInterfaceNames } from "./lib/pathQuery.js";
    import type { PathEntry, RateEntry, RNPathTab, PathTableResponse } from "./lib/types.js";
    import RNPathTableTab from "./components/RNPathTableTab.svelte";
    import RNPathRatesTab from "./components/RNPathRatesTab.svelte";
    import RNPathActionsTab from "./components/RNPathActionsTab.svelte";

    let tab = $state<RNPathTab>("table");
    let isLoading = $state(false);
    let pathTable = $state<PathEntry[]>([]);
    let rateTable = $state<RateEntry[]>([]);
    let interfaces = $state<string[]>([]);

    let searchQuery = $state("");
    let filterInterface = $state("");
    let filterHops = $state<number | string | null>(null);
    let currentPage = $state(1);
    let itemsPerPage = $state(DEFAULT_ITEMS_PER_PAGE);
    let totalItems = $state(0);
    let responsiveItems = $state(0);
    let unresponsiveItems = $state(0);

    let remoteHash = $state("");
    let identityPath = $state("");
    let remoteTimeout = $state(DEFAULT_REMOTE_TIMEOUT);
    let activeRemoteHash = $state("");

    const totalPages = $derived(Math.max(1, Math.ceil(totalItems / itemsPerPage)));

    function isReducedMotion(): boolean {
        if (typeof window === "undefined" || typeof window.matchMedia !== "function") {
            return false;
        }
        return window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    }

    const tabFadeMs = $derived(isReducedMotion() ? 0 : 120);

    async function fetchPathTableData(): Promise<PathTableResponse> {
        let params: Record<string, unknown>;
        try {
            params = buildPathQueryParams({
                searchQuery,
                filterInterface,
                filterHops,
                currentPage,
                itemsPerPage,
                remoteHash,
                identityPath,
                remoteTimeout,
            });
        } catch {
            throw new Error(t("tools.rnpath.invalid_hops"));
        }
        const res = await window.api.get("/api/v1/rnpath/table", { params });
        const data = (res as any)?.data as PathTableResponse | undefined;
        return (data || { table: [], total: 0, responsive: 0, unresponsive: 0 }) as PathTableResponse;
    }

    export async function refreshAll(): Promise<void> {
        isLoading = true;
        try {
            const remoteParams = buildRemoteQueryParams(remoteHash, identityPath, remoteTimeout);
            const [pathRes, rateRes, ifaceRes, discRes] = await Promise.all([
                fetchPathTableData(),
                window.api.get("/api/v1/rnpath/rates", { params: remoteParams }),
                window.api.get("/api/v1/reticulum/interfaces"),
                window.api.get("/api/v1/reticulum/discovered-interfaces").catch(() => ({ data: {} }) as any),
            ]);
            const rateData = (rateRes as any)?.data as { remote?: string; rates?: RateEntry[] } | undefined;
            const ifaceData = (ifaceRes as any)?.data as { interfaces?: Record<string, unknown> } | undefined;
            const discData = (discRes as any)?.data as
                { active?: Array<{ name?: string }>; interfaces?: Array<{ name?: string } | string> } | undefined;
            pathTable = pathRes?.table || [];
            totalItems = pathRes?.total || 0;
            responsiveItems = pathRes?.responsive || 0;
            unresponsiveItems = pathRes?.unresponsive || 0;
            activeRemoteHash = pathRes?.remote || rateData?.remote || "";
            rateTable = rateData?.rates || [];
            interfaces = extractInterfaceNames(ifaceData, discData);
        } catch (e: any) {
            console.error(e);
            const detail = e?.response?.data?.message || e?.message || "";
            ToastUtils.error(detail ? `${t("tools.rnpath.failed_fetch")}: ${detail}` : t("tools.rnpath.failed_fetch"));
        } finally {
            isLoading = false;
        }
    }

    export async function refreshTable(): Promise<void> {
        isLoading = true;
        try {
            const res = await fetchPathTableData();
            pathTable = res.table || [];
            totalItems = res.total || 0;
            responsiveItems = res.responsive || 0;
            unresponsiveItems = res.unresponsive || 0;
            activeRemoteHash = res.remote || "";
        } catch (e: any) {
            console.error(e);
            const detail = e?.response?.data?.message || e?.message || "";
            ToastUtils.error(detail ? `${t("tools.rnpath.failed_fetch")}: ${detail}` : t("tools.rnpath.failed_fetch"));
        } finally {
            isLoading = false;
        }
    }

    function handleFilterChange(): void {
        currentPage = 1;
        void refreshTable();
    }

    function handlePageChange(page: number): void {
        currentPage = page;
        void refreshTable();
    }

    function clearRemote(): void {
        remoteHash = "";
        activeRemoteHash = "";
        void refreshAll();
    }

    async function dropPath(hash: string): Promise<void> {
        if (!(await DialogUtils.confirm(t("tools.rnpath.drop_confirm", { hash })))) {
            return;
        }
        try {
            const res = await window.api.post("/api/v1/rnpath/drop", { destination_hash: hash });
            const data = (res as any)?.data as { success?: boolean } | undefined;
            if (data?.success) {
                ToastUtils.success(t("tools.rnpath.path_dropped"));
                void refreshAll();
            } else {
                ToastUtils.error(t("tools.rnpath.failed_drop"));
            }
        } catch {
            ToastUtils.error(t("tools.rnpath.error_drop"));
        }
    }

    async function requestPath(hash: string): Promise<void> {
        try {
            await window.api.post("/api/v1/rnpath/request", { destination_hash: hash });
            ToastUtils.success(t("tools.rnpath.path_requested", { hash: hash.substring(0, 8) }));
        } catch {
            ToastUtils.error(t("tools.rnpath.failed_request"));
        }
    }

    async function dropAllVia(hash: string): Promise<void> {
        if (!(await DialogUtils.confirm(t("tools.rnpath.drop_via_confirm", { hash })))) {
            return;
        }
        try {
            const res = await window.api.post("/api/v1/rnpath/drop-via", {
                transport_instance_hash: hash,
            });
            const data = (res as any)?.data as { success?: boolean } | undefined;
            if (data?.success) {
                ToastUtils.success(t("tools.rnpath.paths_dropped"));
                void refreshAll();
            }
        } catch {
            ToastUtils.error(t("tools.rnpath.failed_drop_paths"));
        }
    }

    async function dropAnnounceQueues(): Promise<void> {
        if (!(await DialogUtils.confirm(t("tools.rnpath.purge_confirm")))) {
            return;
        }
        try {
            await window.api.post("/api/v1/rnpath/drop-queues");
            ToastUtils.success(t("tools.rnpath.queues_purged"));
        } catch {
            ToastUtils.error(t("tools.rnpath.failed_purge"));
        }
    }

    onMount(() => {
        void refreshAll();
    });
</script>

<div class="flex flex-col flex-1 overflow-hidden min-w-0 bg-sem-canvas" data-testid="rnpath-page">
    <ToolsPageHeader
        icon="route"
        title={t("tools.rnpath.title")}
        description={t("tools.rnpath.description")}
        accent="indigo"
    >
        <button
            type="button"
            class="p-2 text-gray-500 hover:text-indigo-500 dark:text-gray-400 dark:hover:text-indigo-400 transition-colors cursor-pointer"
            title="Refresh"
            onclick={() => void refreshAll()}
        >
            <MaterialDesignIcon iconName="refresh" class="size-6 {isLoading ? 'animate-spin-reverse' : ''}" />
        </button>
    </ToolsPageHeader>

    <div
        class="flex-1 overflow-y-auto min-w-0 p-3 sm:p-4 md:p-6 space-y-4 sm:space-y-6 pb-[max(1rem,env(safe-area-inset-bottom))]"
    >
        <!-- tabs -->
        <div class="-mx-3 sm:mx-0 overflow-x-auto border-b border-sem-border">
            <div class="flex min-w-0 px-3 sm:px-0">
                {#each RNPATH_TABS as tName (tName)}
                    <button
                        type="button"
                        class="shrink-0 px-4 sm:px-6 py-3 text-sm font-semibold transition-colors border-b-2 -mb-px cursor-pointer focus-ring-sem {tab ===
                        tName
                            ? 'text-sem-accent border-sem-accent'
                            : 'text-sem-fg-muted border-transparent hover:text-sem-fg'}"
                        onclick={() => (tab = tName)}
                    >
                        {tName.charAt(0).toUpperCase() + tName.slice(1)}
                    </button>
                {/each}
            </div>
        </div>

        {#key tab}
            <div in:fade={{ duration: tabFadeMs }}>
                {#if tab === "table"}
                    <RNPathTableTab
                        {pathTable}
                        {totalItems}
                        {responsiveItems}
                        {unresponsiveItems}
                        {interfaces}
                        {totalPages}
                        bind:remoteHash
                        bind:identityPath
                        bind:remoteTimeout
                        {activeRemoteHash}
                        bind:searchQuery
                        bind:filterInterface
                        bind:filterHops
                        bind:currentPage
                        bind:itemsPerPage
                        onDropPath={dropPath}
                        onClearRemote={clearRemote}
                        onFilterChange={handleFilterChange}
                        onPageChange={handlePageChange}
                    />
                {:else if tab === "rates"}
                    <RNPathRatesTab {rateTable} />
                {:else if tab === "actions"}
                    <RNPathActionsTab
                        onRequestPath={(hash) => void requestPath(hash)}
                        onDropAllVia={(hash) => void dropAllVia(hash)}
                        onDropAnnounceQueues={() => void dropAnnounceQueues()}
                    />
                {/if}
            </div>
        {/key}
    </div>
</div>

// meshchatx/src/frontend/components/tools/RNPathPage.vue
<!-- SPDX-License-Identifier: 0BSD -->

<template>
    <div class="flex flex-col flex-1 overflow-hidden min-w-0 bg-sem-canvas">
        <ToolsPageHeader
            icon="route"
            :title="$t('tools.rnpath.title')"
            :description="$t('tools.rnpath.description')"
            accent="indigo"
        >
            <template #actions>
                <button
                    class="p-2 text-gray-500 hover:text-indigo-500 dark:text-gray-400 dark:hover:text-indigo-400 transition-colors"
                    title="Refresh"
                    @click="refreshAll"
                >
                    <MaterialDesignIcon
                        icon-name="refresh"
                        class="size-6"
                        :class="{ 'animate-spin-reverse': isLoading }"
                    />
                </button>
            </template>
        </ToolsPageHeader>

        <div
            class="flex-1 overflow-y-auto min-w-0 p-3 sm:p-4 md:p-6 space-y-4 sm:space-y-6 pb-[max(1rem,env(safe-area-inset-bottom))]"
        >
            <!-- tabs -->
            <div class="-mx-3 sm:mx-0 overflow-x-auto border-b border-sem-border">
                <div class="flex min-w-0 px-3 sm:px-0">
                    <button
                        v-for="t in ['table', 'rates', 'actions']"
                        :key="t"
                        type="button"
                        class="shrink-0 px-4 sm:px-6 py-3 text-sm font-semibold transition-colors border-b-2 -mb-px"
                        :class="[
                            tab === t
                                ? 'text-indigo-600 border-indigo-500 dark:text-indigo-400 dark:border-indigo-400'
                                : 'text-gray-500 border-transparent hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200',
                        ]"
                        @click="tab = t"
                    >
                        {{ t.charAt(0).toUpperCase() + t.slice(1) }}
                    </button>
                </div>
            </div>

            <!-- path table -->
            <div v-if="tab === 'table'" class="space-y-4">
                <div class="rounded-lg border border-sem-border bg-sem-surface p-3 sm:p-4 space-y-3">
                    <div class="text-sm font-semibold">{{ $t("rnstatus.remote_query") }}</div>
                    <p class="text-xs text-gray-500">{{ $t("rnstatus.remote_query_hint") }}</p>
                    <div class="grid gap-3 lg:grid-cols-2">
                        <input
                            v-model="remoteHash"
                            type="text"
                            class="input-field font-mono text-xs"
                            :placeholder="$t('rnstatus.remote_transport_placeholder')"
                        />
                        <input
                            v-model.number="remoteTimeout"
                            type="number"
                            min="1"
                            class="input-field text-sm"
                            :placeholder="$t('rnstatus.remote_timeout')"
                        />
                    </div>
                    <ManagementIdentityPicker v-model="identityPath" default-name="mgmt" />
                    <div v-if="activeRemoteHash" class="flex flex-wrap items-center gap-2 text-xs">
                        <span class="font-mono text-amber-700 dark:text-amber-300">{{
                            $t("rnstatus.remote_active", { hash: activeRemoteHash })
                        }}</span>
                        <button type="button" class="secondary-chip px-2 py-1 text-xs" @click="clearRemote">
                            {{ $t("rnstatus.use_local") }}
                        </button>
                    </div>
                </div>
                <!-- filters -->
                <div
                    class="rounded-lg border border-sem-border bg-sem-surface p-3 sm:p-4 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4"
                >
                    <div class="relative">
                        <input
                            v-model="searchQuery"
                            type="text"
                            placeholder="Search Hash or Via..."
                            class="input-field pr-10"
                            autocomplete="off"
                        />
                        <MaterialDesignIcon
                            icon-name="magnify"
                            class="pointer-events-none absolute right-3 top-1/2 size-5 -translate-y-1/2 text-gray-400"
                            aria-hidden="true"
                        />
                    </div>
                    <select v-model="filterInterface" class="input-field">
                        <option value="">All Interfaces</option>
                        <option v-for="iface in interfaces" :key="iface" :value="iface">
                            {{ iface }}
                        </option>
                    </select>
                    <div class="flex items-center gap-2">
                        <span class="text-xs font-semibold text-gray-500 uppercase min-w-fit">Hops:</span>
                        <input
                            v-model.number="filterHops"
                            type="number"
                            min="0"
                            max="128"
                            placeholder="Any"
                            class="input-field"
                        />
                    </div>
                    <div
                        class="flex flex-wrap items-center justify-start sm:justify-end gap-x-4 gap-y-2 sm:flex-nowrap lg:col-span-1"
                    >
                        <div class="flex flex-col items-start sm:items-end">
                            <span class="text-[10px] font-bold text-gray-400 uppercase">Total</span>
                            <span class="text-sm font-bold">{{ totalItems }}</span>
                        </div>
                        <div class="flex flex-col items-start sm:items-end">
                            <span class="text-[10px] font-bold text-green-500 uppercase">Responsive</span>
                            <span class="text-sm font-bold text-green-600 dark:text-green-400">{{
                                responsiveItems
                            }}</span>
                        </div>
                        <div class="flex flex-col items-start sm:items-end">
                            <span class="text-[10px] font-bold text-red-500 uppercase">Unresponsive</span>
                            <span class="text-sm font-bold text-red-600 dark:text-red-400">{{
                                unresponsiveItems
                            }}</span>
                        </div>
                    </div>
                </div>

                <div
                    v-if="pathTable.length === 0"
                    class="rounded-lg border border-sem-border bg-sem-surface p-8 sm:p-12 text-center text-gray-500"
                >
                    No paths found matching your criteria.
                </div>
                <div v-else class="grid gap-4">
                    <div
                        v-for="path in pathTable"
                        :key="path.hash"
                        class="rounded-lg border border-sem-border bg-sem-surface p-3 sm:p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-l-4"
                        :class="[
                            path.state === 2
                                ? 'border-l-green-500'
                                : path.state === 1
                                  ? 'border-l-red-500'
                                  : 'border-l-gray-300 dark:border-l-zinc-700',
                        ]"
                    >
                        <div class="min-w-0">
                            <div class="flex flex-wrap items-center gap-2 mb-1">
                                <span class="font-mono text-sm font-bold text-indigo-600 dark:text-indigo-400 truncate">
                                    {{ path.hash }}
                                </span>
                                <span
                                    class="px-2 py-0.5 text-[10px] font-bold bg-indigo-50 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300 rounded-sm uppercase tracking-wider"
                                >
                                    {{ path.hops }} {{ path.hops === 1 ? "hop" : "hops" }}
                                </span>
                                <span
                                    class="px-2 py-0.5 text-[10px] font-bold rounded-sm uppercase tracking-wider"
                                    :class="getStateColor(path.state)"
                                >
                                    {{ getStateText(path.state) }}
                                </span>
                            </div>
                            <div class="text-xs text-sem-fg-muted font-mono truncate">
                                via {{ path.via }} on {{ path.interface }}
                            </div>
                            <div class="flex flex-wrap gap-x-4 gap-y-1 mt-2 text-[10px]">
                                <div class="text-gray-400">
                                    <span class="font-semibold uppercase">Last Updated:</span>
                                    {{ path.timestamp ? formatDate(path.timestamp) : "Unknown" }}
                                </div>
                                <div class="text-gray-400">
                                    <span class="font-semibold uppercase">Expires:</span> {{ formatDate(path.expires) }}
                                </div>
                                <div v-if="path.announce_hash" class="text-gray-400">
                                    <span class="font-semibold uppercase">Announce Hash:</span> {{ path.announce_hash }}
                                </div>
                            </div>
                        </div>
                        <button
                            class="px-3 py-1.5 text-xs font-semibold text-red-600 hover:bg-red-50 dark:text-red-400 dark:hover:bg-red-900/20 rounded-lg transition-colors border border-red-200 dark:border-red-900/30"
                            @click="dropPath(path.hash)"
                        >
                            Drop Path
                        </button>
                    </div>
                </div>

                <!-- pagination -->
                <div
                    v-if="totalPages > 1"
                    class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 rounded-lg border border-sem-border bg-sem-surface p-3 sm:p-4"
                >
                    <div class="flex items-center gap-2">
                        <button
                            class="p-2 rounded-lg hover:bg-sem-surface-muted disabled:opacity-50 transition-colors"
                            :disabled="currentPage === 1"
                            @click="currentPage--"
                        >
                            <MaterialDesignIcon icon-name="chevron-left" class="size-5" />
                        </button>
                        <span class="text-sm font-medium"> Page {{ currentPage }} of {{ totalPages }} </span>
                        <button
                            class="p-2 rounded-lg hover:bg-sem-surface-muted disabled:opacity-50 transition-colors"
                            :disabled="currentPage === totalPages"
                            @click="currentPage++"
                        >
                            <MaterialDesignIcon icon-name="chevron-right" class="size-5" />
                        </button>
                    </div>
                    <div class="flex items-center gap-2 justify-between sm:justify-end w-full sm:w-auto">
                        <span class="text-xs text-gray-500 uppercase font-semibold">Show:</span>
                        <select
                            v-model="itemsPerPage"
                            class="bg-transparent border-none text-sm font-bold text-sem-fg focus:ring-0 cursor-pointer"
                        >
                            <option :value="20">20</option>
                            <option :value="50">50</option>
                            <option :value="100">100</option>
                            <option :value="250">250</option>
                        </select>
                    </div>
                </div>
            </div>

            <!-- announce rates -->
            <div v-if="tab === 'rates'" class="space-y-4">
                <div
                    v-if="rateTable.length === 0"
                    class="rounded-lg border border-sem-border bg-sem-surface p-8 sm:p-12 text-center text-gray-500"
                >
                    No announce rate data available.
                </div>
                <div v-else class="grid gap-4">
                    <div
                        v-for="rate in rateTable"
                        :key="rate.hash"
                        class="rounded-lg border border-sem-border bg-sem-surface p-3 sm:p-4"
                    >
                        <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-3">
                            <span class="font-mono text-sm font-bold text-indigo-600 dark:text-indigo-400 truncate">
                                {{ rate.hash }}
                            </span>
                            <span
                                v-if="rate.blocked_until > Date.now() / 1000"
                                class="px-2 py-0.5 text-[10px] font-bold bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-300 rounded-sm"
                            >
                                RATE LIMITED
                            </span>
                        </div>
                        <div class="grid grid-cols-2 sm:grid-cols-4 gap-4">
                            <div>
                                <div class="text-[10px] uppercase text-gray-500">Last Heard</div>
                                <div class="text-xs font-medium">{{ formatTimeAgo(rate.last) }}</div>
                            </div>
                            <div>
                                <div class="text-[10px] uppercase text-gray-500">Announces</div>
                                <div class="text-xs font-medium">{{ rate.timestamps.length }}</div>
                            </div>
                            <div>
                                <div class="text-[10px] uppercase text-gray-500">Violations</div>
                                <div
                                    class="text-xs font-medium"
                                    :class="rate.rate_violations > 0 ? 'text-red-500' : ''"
                                >
                                    {{ rate.rate_violations }}
                                </div>
                            </div>
                            <div>
                                <div class="text-[10px] uppercase text-gray-500">Rate</div>
                                <div class="text-xs font-medium">{{ calculateRate(rate) }} / hr</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- manual actions -->
            <div v-if="tab === 'actions'" class="max-w-2xl mx-auto space-y-6">
                <!-- request path -->
                <section class="rounded-lg border border-sem-border bg-sem-surface p-4 sm:p-6 space-y-4">
                    <h2 class="text-lg font-bold">Request Path</h2>
                    <p class="text-sm text-gray-500">Broadcast a path request for a destination hash.</p>
                    <div class="flex flex-col sm:flex-row gap-2">
                        <input
                            v-model="requestHash"
                            type="text"
                            placeholder="Destination Hash (32 hex chars)"
                            class="input-field flex-1 min-w-0 font-mono"
                        />
                        <button
                            type="button"
                            class="px-4 py-2.5 sm:py-2 bg-indigo-600 text-white rounded-lg font-semibold hover:bg-indigo-500 transition active:scale-95 disabled:opacity-50 shrink-0"
                            :disabled="requestHash.length !== 32"
                            @click="requestPath"
                        >
                            Request
                        </button>
                    </div>
                </section>

                <!-- drop all via -->
                <section class="rounded-lg border border-sem-border bg-sem-surface p-4 sm:p-6 space-y-4">
                    <h2 class="text-lg font-bold">Drop All Via</h2>
                    <p class="text-sm text-gray-500">
                        Remove all known paths routed through a specific transport instance.
                    </p>
                    <div class="flex flex-col sm:flex-row gap-2">
                        <input
                            v-model="dropViaHash"
                            type="text"
                            placeholder="Transport Instance Hash"
                            class="input-field flex-1 min-w-0 font-mono"
                        />
                        <button
                            type="button"
                            class="px-4 py-2.5 sm:py-2 bg-red-600 text-white rounded-lg font-semibold hover:bg-red-500 transition active:scale-95 disabled:opacity-50 shrink-0"
                            :disabled="dropViaHash.length !== 32"
                            @click="dropAllVia"
                        >
                            Drop All
                        </button>
                    </div>
                </section>

                <!-- drop queues -->
                <section class="rounded-lg border border-sem-border bg-sem-surface p-4 sm:p-6 space-y-4">
                    <h2 class="text-lg font-bold">Drop Announce Queues</h2>
                    <p class="text-sm text-gray-500">
                        Clear all outbound announce packets currently queued on all interfaces.
                    </p>
                    <button
                        type="button"
                        class="w-full px-4 py-3 bg-zinc-800 text-white rounded-lg font-semibold hover:bg-zinc-700 transition active:scale-95"
                        @click="dropAnnounceQueues"
                    >
                        Purge All Queues
                    </button>
                </section>
            </div>
        </div>
    </div>
</template>

<script>
import MaterialDesignIcon from "../MaterialDesignIcon.vue";
import ToastUtils from "../../js/ToastUtils";
import DialogUtils from "../../js/DialogUtils";
import Utils from "../../js/Utils";
import ToolsPageHeader from "./ToolsPageHeader.vue";
import ManagementIdentityPicker from "./ManagementIdentityPicker.vue";

export default {
    name: "RNPathPage",
    components: {
        MaterialDesignIcon,
        ToolsPageHeader,
        ManagementIdentityPicker,
    },
    data() {
        return {
            tab: "table",
            isLoading: false,
            pathTable: [],
            rateTable: [],
            requestHash: "",
            dropViaHash: "",
            // Pagination & Filtering
            searchQuery: "",
            filterInterface: "",
            filterHops: null,
            currentPage: 1,
            itemsPerPage: 50,
            totalItems: 0,
            responsiveItems: 0,
            unresponsiveItems: 0,
            interfaces: [],
            remoteHash: "",
            identityPath: "",
            remoteTimeout: 15,
            activeRemoteHash: "",
        };
    },
    computed: {
        totalPages() {
            return Math.ceil(this.totalItems / this.itemsPerPage);
        },
    },
    watch: {
        searchQuery() {
            this.currentPage = 1;
            this.refreshTable();
        },
        filterInterface() {
            this.currentPage = 1;
            this.refreshTable();
        },
        filterHops() {
            this.currentPage = 1;
            this.refreshTable();
        },
        currentPage() {
            this.refreshTable();
        },
        itemsPerPage() {
            this.currentPage = 1;
            this.refreshTable();
        },
    },
    mounted() {
        this.refreshAll();
    },
    methods: {
        remoteQueryParams() {
            const remote = (this.remoteHash || "").trim();
            if (!remote) {
                return {};
            }
            const params = { remote };
            if (this.identityPath) {
                params.identity_path = this.identityPath;
            }
            if (this.remoteTimeout) {
                params.timeout = this.remoteTimeout;
            }
            return params;
        },
        clearRemote() {
            this.remoteHash = "";
            this.activeRemoteHash = "";
            this.refreshAll();
        },
        async refreshAll() {
            this.isLoading = true;
            try {
                const remoteParams = this.remoteQueryParams();
                const [pathRes, rateRes, ifaceRes, discRes] = await Promise.all([
                    this.fetchPathTable(),
                    window.api.get("/api/v1/rnpath/rates", { params: remoteParams }),
                    window.api.get("/api/v1/reticulum/interfaces"),
                    window.api.get("/api/v1/reticulum/discovered-interfaces").catch(() => ({ data: {} })),
                ]);
                this.pathTable = pathRes.table;
                this.totalItems = pathRes.total;
                this.responsiveItems = pathRes.responsive;
                this.unresponsiveItems = pathRes.unresponsive;
                this.activeRemoteHash = pathRes.remote || rateRes.data?.remote || "";
                this.rateTable = rateRes.data.rates;
                const nameSet = new Set(Object.keys(ifaceRes.data?.interfaces || {}));
                for (const row of discRes.data?.active || []) {
                    if (row?.name) {
                        nameSet.add(String(row.name));
                    }
                }
                for (const d of discRes.data?.interfaces || []) {
                    if (d && typeof d === "object" && d.name) {
                        nameSet.add(String(d.name));
                    }
                }
                this.interfaces = Array.from(nameSet).sort();
            } catch (e) {
                console.error(e);
                const detail = e?.response?.data?.message || e?.message || "";
                ToastUtils.error(
                    detail ? `${this.$t("tools.rnpath.failed_fetch")}: ${detail}` : this.$t("tools.rnpath.failed_fetch")
                );
            } finally {
                this.isLoading = false;
            }
        },
        async refreshTable() {
            this.isLoading = true;
            try {
                const res = await this.fetchPathTable();
                this.pathTable = res.table;
                this.totalItems = res.total;
                this.responsiveItems = res.responsive;
                this.unresponsiveItems = res.unresponsive;
                this.activeRemoteHash = res.remote || "";
            } catch (e) {
                console.error(e);
                const detail = e?.response?.data?.message || e?.message || "";
                ToastUtils.error(
                    detail ? `${this.$t("tools.rnpath.failed_fetch")}: ${detail}` : this.$t("tools.rnpath.failed_fetch")
                );
            } finally {
                this.isLoading = false;
            }
        },
        async fetchPathTable() {
            let hops = undefined;
            if (this.filterHops !== null && this.filterHops !== "") {
                const parsed = Number(this.filterHops);
                if (!Number.isFinite(parsed)) {
                    throw new Error(this.$t("tools.rnpath.invalid_hops"));
                }
                hops = parsed;
            }
            const params = {
                page: this.currentPage,
                limit: this.itemsPerPage,
                search: this.searchQuery || undefined,
                interface: this.filterInterface || undefined,
                hops,
                ...this.remoteQueryParams(),
            };
            const res = await window.api.get("/api/v1/rnpath/table", { params });
            return res.data;
        },
        getStateColor(state) {
            if (state === 2) return "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300";
            if (state === 1) return "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300";
            return "bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-400";
        },
        getStateText(state) {
            if (state === 2) return "RESPONSIVE";
            if (state === 1) return "UNRESPONSIVE";
            return "UNKNOWN";
        },
        async dropPath(hash) {
            if (!(await DialogUtils.confirm(this.$t("tools.rnpath.drop_confirm", { hash })))) {
                return;
            }
            try {
                const res = await window.api.post("/api/v1/rnpath/drop", { destination_hash: hash });
                if (res.data.success) {
                    ToastUtils.success(this.$t("tools.rnpath.path_dropped"));
                    this.refreshAll();
                } else {
                    ToastUtils.error(this.$t("tools.rnpath.failed_drop"));
                }
            } catch {
                ToastUtils.error(this.$t("tools.rnpath.error_drop"));
            }
        },
        async requestPath() {
            try {
                await window.api.post("/api/v1/rnpath/request", { destination_hash: this.requestHash });
                ToastUtils.success(this.$t("tools.rnpath.path_requested", { hash: this.requestHash.substring(0, 8) }));
                this.requestHash = "";
            } catch {
                ToastUtils.error(this.$t("tools.rnpath.failed_request"));
            }
        },
        async dropAllVia() {
            if (!(await DialogUtils.confirm(this.$t("tools.rnpath.drop_via_confirm", { hash: this.dropViaHash })))) {
                return;
            }
            try {
                const res = await window.api.post("/api/v1/rnpath/drop-via", {
                    transport_instance_hash: this.dropViaHash,
                });
                if (res.data.success) {
                    ToastUtils.success(this.$t("tools.rnpath.paths_dropped"));
                    this.dropViaHash = "";
                    this.refreshAll();
                }
            } catch {
                ToastUtils.error(this.$t("tools.rnpath.failed_drop_paths"));
            }
        },
        async dropAnnounceQueues() {
            if (!(await DialogUtils.confirm(this.$t("tools.rnpath.purge_confirm")))) {
                return;
            }
            try {
                await window.api.post("/api/v1/rnpath/drop-queues");
                ToastUtils.success(this.$t("tools.rnpath.queues_purged"));
            } catch {
                ToastUtils.error(this.$t("tools.rnpath.failed_purge"));
            }
        },
        calculateRate(rate) {
            if (rate.timestamps.length === 0) return 0;
            const startTs = rate.timestamps[0];
            const span = Math.max(Date.now() / 1000 - startTs, 3600.0);
            const spanHours = span / 3600.0;
            return (rate.timestamps.length / spanHours).toFixed(2);
        },
        formatDate(ts) {
            return new Date(ts * 1000).toLocaleString();
        },
        formatTimeAgo(ts) {
            return Utils.formatSecondsAgo(Math.floor(Date.now() / 1000 - ts));
        },
    },
};
</script>

<style scoped>
@reference "../../style.css";
.input-field {
    @apply bg-gray-50/90 dark:bg-zinc-800/80 border border-sem-border text-sm rounded-xl focus:ring-2 focus:ring-indigo-400 focus:border-indigo-400 dark:focus:ring-indigo-500 dark:focus:border-indigo-500 block w-full p-3 text-gray-900 dark:text-gray-100 transition;
}
</style>
