// meshchatx/src/frontend/components/relay/RelayMessageEntry.vue
<!-- SPDX-License-Identifier: 0BSD -->

<template>
    <div
        v-if="entry.type === 'dateDivider'"
        class="flex items-center justify-center gap-3 w-full my-3 shrink-0 px-2 select-none"
        role="separator"
        :aria-label="page.formatDateDividerLabel(entry.dayKey)"
    >
        <span class="h-px w-10 shrink-0 bg-sem-border sm:w-14" aria-hidden="true" />
        <span
            class="max-w-[min(100%,18rem)] text-center text-[11px] font-medium leading-snug tracking-wide text-sem-fg-muted"
        >
            {{ page.formatDateDividerLabel(entry.dayKey) }}
        </span>
        <span class="h-px w-10 shrink-0 bg-sem-border sm:w-14" aria-hidden="true" />
    </div>
    <div v-else-if="entry.type === 'presenceGroup'" class="px-2 py-1">
        <button
            type="button"
            class="mx-auto flex max-w-full items-center gap-1 rounded-md px-2 py-0.5 text-xs italic text-sem-fg-muted transition-colors hover:bg-sem-surface/50 hover:text-sem-fg"
            :aria-expanded="expanded"
            @click="page.togglePresenceGroup(entry.id)"
        >
            <MaterialDesignIcon
                :icon-name="expanded ? 'chevron-down' : 'chevron-right'"
                class="size-3.5 shrink-0 opacity-70"
            />
            <span class="truncate">{{ page.formatPresenceGroupSummary(entry) }}</span>
        </button>
        <div v-if="expanded" class="mt-1 space-y-0.5">
            <div
                v-for="(msg, idx) in entry.messages"
                :key="page.messageKey(msg) || idx"
                class="py-0.5 text-center text-xs italic text-sem-fg-muted"
                :data-msg-key="page.messageKey(msg)"
            >
                {{ msg.text }}
            </div>
        </div>
    </div>
    <div
        v-else-if="isSystemLike"
        class="py-0.5 text-center text-xs italic"
        :class="entry.msg.kind === 'error' ? 'text-sem-danger' : 'text-sem-fg-muted'"
        :data-msg-key="page.messageKey(entry.msg)"
    >
        {{ entry.msg.text }}
    </div>
    <div
        v-else-if="entry.msg && entry.msg.kind === 'action'"
        class="rounded-lg px-2 py-1 text-sm italic"
        :class="entry.msg.mention ? 'bg-sem-warning/15' : ''"
        :data-msg-key="page.messageKey(entry.msg)"
    >
        <span class="mr-1 text-xs text-sem-fg-muted">{{ page.formatTime(entry.msg.ts) }}</span>
        * {{ page.displayName(entry.msg) }}
        <!-- eslint-disable vue/no-v-html -- sanitized via renderMessageHtml -->
        <span
            class="wrap-break-word"
            @click="page.handleMessageHtmlClick($event)"
            v-html="page.renderMessageHtml(entry.msg.text)"
        ></span>
        <!-- eslint-enable vue/no-v-html -->
    </div>
    <div
        v-else-if="entry.msg"
        class="rounded-lg px-2 py-1 text-sm"
        :class="entry.msg.mention ? 'bg-sem-warning/15' : 'hover:bg-sem-surface/40 dark:hover:bg-sem-surface/20'"
        :data-msg-key="page.messageKey(entry.msg)"
        @contextmenu="page.openMessageContextMenu($event, entry.msg)"
    >
        <span class="mr-1.5 text-xs text-sem-fg-muted">{{ page.formatTime(entry.msg.ts) }}</span>
        <span class="mr-1.5 font-semibold" :style="page.nameStyle(entry.msg)">{{ page.displayName(entry.msg) }}:</span>
        <!-- eslint-disable vue/no-v-html -- sanitized via renderMessageHtml -->
        <span
            class="whitespace-pre-wrap wrap-break-word"
            @click="page.handleMessageHtmlClick($event)"
            v-html="page.renderMessageHtml(page.relayMessageDisplayText(entry.msg))"
        ></span>
        <!-- eslint-enable vue/no-v-html -->
        <div
            v-if="translation"
            class="mt-1 pt-1 border-t border-black/5 dark:border-white/5 text-xs text-sem-fg-muted flex items-center gap-2"
        >
            <span>
                {{
                    $t("messages.translated_from_to", {
                        source: translation.from.toUpperCase(),
                        target: translation.to.toUpperCase(),
                    })
                }}
            </span>
            <button
                type="button"
                class="text-sem-info hover:underline"
                @click.stop="page.toggleRelayMessageOriginal(entry.msg)"
            >
                {{ translation.showOriginal ? $t("messages.show_translation") : $t("messages.show_original") }}
            </button>
        </div>
    </div>
</template>

<script setup>
import { computed } from "vue";
import MaterialDesignIcon from "../MaterialDesignIcon.vue";

const props = defineProps({
    entry: {
        type: Object,
        required: true,
    },
    page: {
        type: Object,
        required: true,
    },
});

const isSystemLike = computed(() => {
    const kind = props.entry?.msg?.kind;
    return kind === "system" || kind === "notice" || kind === "error";
});

const expanded = computed(() => {
    if (props.entry?.type !== "presenceGroup") {
        return false;
    }
    return props.page.isPresenceGroupExpanded(props.entry.id);
});

const translation = computed(() => {
    if (!props.entry?.msg) {
        return null;
    }
    return props.page.relayMessageTranslation(props.entry.msg);
});
</script>

// meshchatx/src/frontend/features/relay-chat/components/RelayMessageEntry.svelte
<!-- SPDX-License-Identifier: 0BSD -->

<script lang="ts">
    import MaterialDesignIcon from "../../../ui/svelte/MaterialDesignIcon.svelte";
    import { t } from "../../../js/i18n.js";
    import { formatTime, nameStyle, displayName } from "../lib/relayFormatters.js";
    import type { RrcMessage, RrcMessageTranslation, RrcTimelineEntry } from "../lib/types.js";

    interface Props {
        entry: RrcTimelineEntry;
        formatDateDividerLabel: (dayKey?: string) => string;
        isPresenceGroupExpanded: (id?: string) => boolean;
        togglePresenceGroup: (id?: string) => void;
        formatPresenceGroupSummary: (entry: RrcTimelineEntry) => string;
        messageKey: (msg?: RrcMessage) => string;
        renderMessageHtml: (text: string) => string;
        relayMessageDisplayText?: (msg: RrcMessage) => string;
        relayMessageTranslation?: (msg: RrcMessage) => RrcMessageTranslation | null;
        toggleRelayMessageOriginal?: (msg: RrcMessage) => void;
        onmessagehtmlclick?: (e: MouseEvent) => void;
        onmessagecontextmenu?: (e: MouseEvent, msg: RrcMessage) => void;
    }

    let {
        entry,
        formatDateDividerLabel,
        isPresenceGroupExpanded,
        togglePresenceGroup,
        formatPresenceGroupSummary,
        messageKey,
        renderMessageHtml,
        relayMessageDisplayText = (m: RrcMessage) => m?.text ?? "",
        relayMessageTranslation = () => null,
        toggleRelayMessageOriginal = () => {},
        onmessagehtmlclick,
        onmessagecontextmenu,
    }: Props = $props();

    const isSystemLike = $derived.by(() => {
        const kind = entry?.msg?.kind;
        return kind === "system" || kind === "notice" || kind === "error";
    });

    const expanded = $derived.by(() => {
        if (entry?.type !== "presenceGroup") return false;
        return isPresenceGroupExpanded(entry.id);
    });

    const translation = $derived.by(() => {
        if (!entry?.msg) return null;
        return relayMessageTranslation(entry.msg);
    });
</script>

{#if entry.type === "dateDivider"}
    <div
        class="flex items-center justify-center gap-3 w-full my-3 shrink-0 px-2 select-none"
        role="separator"
        aria-label={formatDateDividerLabel(entry.dayKey)}
    >
        <span class="h-px w-10 shrink-0 bg-sem-border sm:w-14" aria-hidden="true"></span>
        <span
            class="max-w-[min(100%,18rem)] text-center text-[11px] font-medium leading-snug tracking-wide text-sem-fg-muted"
        >
            {formatDateDividerLabel(entry.dayKey)}
        </span>
        <span class="h-px w-10 shrink-0 bg-sem-border sm:w-14" aria-hidden="true"></span>
    </div>
{:else if entry.type === "presenceGroup"}
    <div class="px-2 py-1">
        <button
            type="button"
            class="mx-auto flex max-w-full items-center gap-1 rounded-md px-2 py-0.5 text-xs italic text-sem-fg-muted transition-colors hover:bg-sem-surface/50 hover:text-sem-fg cursor-pointer"
            aria-expanded={expanded}
            onclick={() => togglePresenceGroup(entry.id)}
        >
            <MaterialDesignIcon
                iconName={expanded ? "chevron-down" : "chevron-right"}
                class="size-3.5 shrink-0 opacity-70"
            />
            <span class="truncate">{formatPresenceGroupSummary(entry)}</span>
        </button>
        {#if expanded && entry.messages}
            <div class="mt-1 space-y-0.5">
                {#each entry.messages as msg, idx (messageKey(msg) || idx)}
                    <div class="py-0.5 text-center text-xs italic text-sem-fg-muted" data-msg-key={messageKey(msg)}>
                        {msg.text}
                    </div>
                {/each}
            </div>
        {/if}
    </div>
{:else if isSystemLike && entry.msg}
    <div
        class="py-0.5 text-center text-xs italic {entry.msg.kind === 'error' ? 'text-sem-danger' : 'text-sem-fg-muted'}"
        data-msg-key={messageKey(entry.msg)}
    >
        {entry.msg.text}
    </div>
{:else if entry.msg && entry.msg.kind === "action"}
    <div
        class="rounded-lg px-2 py-1 text-sm italic {entry.msg.mention ? 'bg-sem-warning/15' : ''}"
        data-msg-key={messageKey(entry.msg)}
    >
        <span class="mr-1 text-xs text-sem-fg-muted">{formatTime(entry.msg.ts)}</span>
        * {displayName(entry.msg)}
        <span
            class="wrap-break-word"
            onclick={(e) => onmessagehtmlclick?.(e)}
            onkeydown={(e) => {
                if (e.key === "Enter") onmessagehtmlclick?.(e as unknown as MouseEvent);
            }}
            role="button"
            tabindex="0"
        >
            <!-- eslint-disable-next-line svelte/no-at-html-tags -->
            {@html renderMessageHtml(entry.msg.text)}
        </span>
    </div>
{:else if entry.msg}
    <div
        class="rounded-lg px-2 py-1 text-sm {entry.msg.mention
            ? 'bg-sem-warning/15'
            : 'hover:bg-sem-surface/40 dark:hover:bg-sem-surface/20'}"
        data-msg-key={messageKey(entry.msg)}
        oncontextmenu={(e) => onmessagecontextmenu?.(e, entry.msg!)}
        role="article"
    >
        <span class="mr-1.5 text-xs text-sem-fg-muted">{formatTime(entry.msg.ts)}</span>
        <span class="mr-1.5 font-semibold" style={nameStyle(entry.msg)}>{displayName(entry.msg)}:</span>
        <span
            class="whitespace-pre-wrap wrap-break-word"
            onclick={(e) => onmessagehtmlclick?.(e)}
            onkeydown={(e) => {
                if (e.key === "Enter") onmessagehtmlclick?.(e as unknown as MouseEvent);
            }}
            role="button"
            tabindex="0"
        >
            <!-- eslint-disable-next-line svelte/no-at-html-tags -->
            {@html renderMessageHtml(relayMessageDisplayText(entry.msg))}
        </span>
        {#if translation}
            <div
                class="mt-1 pt-1 border-t border-black/5 dark:border-white/5 text-xs text-sem-fg-muted flex items-center gap-2"
            >
                <span>
                    {t("messages.translated_from_to", {
                        source: translation.from.toUpperCase(),
                        target: translation.to.toUpperCase(),
                    })}
                </span>
                <button
                    type="button"
                    class="text-sem-info hover:underline cursor-pointer"
                    onclick={(e) => {
                        e.stopPropagation();
                        if (entry.msg) toggleRelayMessageOriginal(entry.msg);
                    }}
                >
                    {translation.showOriginal ? t("messages.show_translation") : t("messages.show_original")}
                </button>
            </div>
        {/if}
    </div>
{/if}
