// meshchatx/src/frontend/features/app-shell/components/CommandPalette.svelte
<!-- SPDX-License-Identifier: 0BSD -->

<script lang="ts">
    import { onDestroy, tick } from "svelte";
    import { t } from "../../../js/i18n.js";
    import MaterialDesignIcon from "../../../ui/svelte/MaterialDesignIcon.svelte";
    import GlobalEmitter from "../../../js/GlobalEmitter.js";
    import ToastUtils from "../../../js/ToastUtils.js";
    import { listCommands } from "../../../js/registries/commandRegistry.js";
    import type { CommandEntry } from "../../../js/registries/coreCommandEntries.js";
    import type { PeerAnnounce, Contact, ResultItem } from "../lib/commandPaletteTypes.js";
    import CommandPaletteResultRow from "./CommandPaletteResultRow.svelte";

    interface Props {
        isOpen?: boolean;
        onnavigate?: (route: unknown) => void;
        onexecuteaction?: () => void;
    }

    let { isOpen = $bindable(false), onnavigate, onexecuteaction }: Props = $props();

    let query = $state("");
    let rawHighlightedId = $state<string | null>(null);
    let peers = $state<PeerAnnounce[]>([]);
    let contacts = $state<Contact[]>([]);
    let inputRef: HTMLInputElement | undefined = $state(undefined);

    const actions = $derived(listCommands());

    const allResults = $derived.by(() => {
        const results: ResultItem[] = actions.map((action: CommandEntry) => ({
            id: action.id,
            title: t(`command_palette.${action.title}`),
            description: t(`command_palette.${action.description}`),
            icon: action.icon,
            type: action.type,
            route: action.route,
            action: action.action,
        }));

        if (Array.isArray(peers)) {
            for (const peer of peers) {
                results.push({
                    id: `peer-${peer.destination_hash}`,
                    title: peer.custom_display_name ?? peer.display_name ?? peer.destination_hash,
                    description: peer.destination_hash,
                    icon: peer.lxmf_user_icon?.icon_name ?? "account",
                    iconForeground: peer.lxmf_user_icon?.foreground_colour,
                    iconBackground: peer.lxmf_user_icon?.background_colour,
                    type: "peer",
                    peer,
                });
            }
        }

        if (Array.isArray(contacts)) {
            for (const contact of contacts) {
                results.push({
                    id: `contact-${contact.id}`,
                    title: contact.name,
                    description: `${t("app.call")} ${contact.remote_identity_hash}`,
                    icon: "phone",
                    type: "contact",
                    contact,
                });
            }
        }

        return results;
    });

    const filteredResults = $derived.by(() => {
        if (!query.trim()) {
            return allResults.filter((r) => r.type === "navigation" || r.type === "action");
        }
        const q = query.toLowerCase();
        return allResults.filter((r) => r.title.toLowerCase().includes(q) || r.description.toLowerCase().includes(q));
    });

    const highlightedId = $derived.by(() => {
        if (filteredResults.length === 0) return null;
        if (rawHighlightedId && filteredResults.some((r) => r.id === rawHighlightedId)) {
            return rawHighlightedId;
        }
        return filteredResults[0]?.id || null;
    });

    const groupedResults = $derived.by(() => {
        const groups: Record<string, ResultItem[]> = {};
        for (const result of filteredResults) {
            const groupName =
                result.type === "peer"
                    ? "group_recent"
                    : result.type === "contact"
                      ? "group_contacts"
                      : "group_actions";
            if (!groups[groupName]) {
                groups[groupName] = [];
            }
            groups[groupName].push(result);
        }
        return groups;
    });

    export async function open(): Promise<void> {
        query = "";
        rawHighlightedId = null;
        isOpen = true;
        void loadPeersAndContacts();
        await tick();
        inputRef?.focus();
    }

    export function close(): void {
        isOpen = false;
    }

    export async function toggle(): Promise<void> {
        if (isOpen) {
            close();
        } else {
            await open();
        }
    }

    export function getIsOpen(): boolean {
        return isOpen;
    }

    export function getFilteredResults(): ResultItem[] {
        return filteredResults;
    }

    export function getGroupedResults(): Record<string, ResultItem[]> {
        return groupedResults;
    }

    export function setQuery(val: string): void {
        query = val;
    }

    export function setPeers(val: PeerAnnounce[]): void {
        peers = val;
    }

    export function setContacts(val: Contact[]): void {
        contacts = val;
    }

    export function getHighlightedId(): string | null {
        return highlightedId;
    }

    export function setHighlightedId(val: string | null): void {
        rawHighlightedId = val;
    }

    async function loadPeersAndContacts(): Promise<void> {
        try {
            const api = (
                window as unknown as { api?: { get: (url: string, config?: unknown) => Promise<{ data: unknown }> } }
            ).api;
            if (!api) return;
            const peerResponse = await api.get("/api/v1/announces", {
                params: { aspect: "lxmf.delivery", limit: 20 },
            });
            const pData = peerResponse?.data as { announces?: PeerAnnounce[] } | undefined;
            peers = pData?.announces || [];

            const contactResponse = await api.get("/api/v1/telephone/contacts");
            const cData = contactResponse?.data as { contacts?: Contact[] } | Contact[] | undefined;
            if (Array.isArray(cData)) {
                contacts = cData;
            } else if (cData && Array.isArray(cData.contacts)) {
                contacts = cData.contacts;
            } else {
                contacts = [];
            }
        } catch (e) {
            console.error("Failed to load command palette data:", e);
        }
    }

    function handleGlobalKeydown(e: KeyboardEvent): void {
        if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k") {
            e.preventDefault();
            e.stopPropagation();
            void toggle();
        }
    }

    if (typeof window !== "undefined") {
        window.addEventListener("keydown", handleGlobalKeydown, true);
        GlobalEmitter.on("open-command-palette", open);
    }

    onDestroy(() => {
        if (typeof window !== "undefined") {
            window.removeEventListener("keydown", handleGlobalKeydown, true);
            GlobalEmitter.off("open-command-palette", open);
        }
    });

    export function moveHighlight(step: number): void {
        const index = filteredResults.findIndex((r) => r.id === highlightedId);
        let nextIndex = index + step;
        if (nextIndex < 0) nextIndex = filteredResults.length - 1;
        if (nextIndex >= filteredResults.length) nextIndex = 0;
        if (filteredResults[nextIndex]) {
            rawHighlightedId = filteredResults[nextIndex].id;
        }
    }

    export function executeAction(direct = false): void {
        if (!direct && onexecuteaction) {
            onexecuteaction();
            return;
        }
        const result = filteredResults.find((r) => r.id === highlightedId);
        if (result) {
            void handleExecuteResult(result);
        }
    }

    export async function executeResult(result: ResultItem): Promise<void> {
        await handleExecuteResult(result);
    }

    async function handleExecuteResult(result: ResultItem): Promise<void> {
        close();
        if (result.type === "navigation") {
            if (onnavigate && result.route) {
                onnavigate(result.route);
            } else if (result.route?.name) {
                window.location.hash = `#/${result.route.name === "home" ? "" : result.route.name}`;
            }
        } else if (result.type === "peer" && result.peer) {
            if (onnavigate) {
                onnavigate({ name: "messages", params: { destinationHash: result.peer.destination_hash } });
            } else {
                window.location.hash = `#/messages/${result.peer.destination_hash}`;
            }
        } else if (result.type === "contact" && result.contact) {
            void dialContact(result.contact.remote_identity_hash);
        } else if (result.type === "action") {
            if (result.action === "sync") {
                GlobalEmitter.emit("sync-propagation-node");
            } else if (result.action === "compose") {
                if (onnavigate) {
                    onnavigate({ name: "messages" });
                } else {
                    window.location.hash = "#/messages";
                }
                GlobalEmitter.emit("compose-new-message");
            } else if (result.action === "show-tutorial") {
                GlobalEmitter.emit("show-tutorial");
            } else if (result.action === "show-changelog") {
                GlobalEmitter.emit("show-changelog");
            }
        }
    }

    async function dialContact(hash: string): Promise<void> {
        try {
            const api = (window as unknown as { api?: { post: (url: string) => Promise<unknown> } }).api;
            if (api) {
                await api.post(`/api/v1/telephone/call/${hash}`);
            }
            if (onnavigate) {
                onnavigate({ name: "call" });
            } else {
                window.location.hash = "#/call";
            }
        } catch (e: any) {
            ToastUtils.error(e?.response?.data?.message || "Failed to initiate call");
        }
    }

    function onBackdropClick(e: MouseEvent): void {
        if (e.target === e.currentTarget) {
            close();
        }
    }
</script>

{#if isOpen}
    <!-- svelte-ignore a11y_click_events_have_key_events -->
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div
        class="fixed inset-0 z-200 flex items-start justify-center p-4 pt-[max(0.5rem,env(safe-area-inset-top))] bg-black/40 backdrop-blur-xs"
        onclick={onBackdropClick}
    >
        <div
            class="w-full max-w-2xl bg-white/95 dark:bg-zinc-900/95 backdrop-blur-md rounded-2xl shadow-2xl border border-sem-border overflow-hidden flex flex-col max-h-[min(70dvh,70vh)] mt-2 sm:mt-8"
            role="dialog"
            aria-modal="true"
        >
            <!-- search input -->
            <div class="relative flex items-center p-4 border-b border-sem-border">
                <MaterialDesignIcon iconName="magnify" class="size-6 text-gray-400 mr-3" />
                <input
                    bind:this={inputRef}
                    bind:value={query}
                    type="text"
                    class="w-full bg-transparent border-none focus:ring-0 text-sem-fg placeholder-gray-400 text-lg outline-hidden"
                    placeholder={t("command_palette.search_placeholder")}
                    onkeydown={(e) => {
                        if (e.key === "ArrowDown" || e.keyCode === 40) {
                            e.preventDefault();
                            moveHighlight(1);
                        } else if (e.key === "ArrowUp" || e.keyCode === 38) {
                            e.preventDefault();
                            moveHighlight(-1);
                        } else if (e.key === "Enter" || e.keyCode === 13) {
                            e.preventDefault();
                            executeAction();
                        } else if (e.key === "Escape" || e.key === "Esc" || e.keyCode === 27) {
                            e.preventDefault();
                            close();
                        }
                    }}
                />
                <div class="flex items-center gap-1 ml-2">
                    <kbd
                        class="px-2 py-1 text-xs font-semibold text-gray-500 bg-sem-surface-muted border border-sem-border rounded-lg shadow-xs"
                    >
                        ESC
                    </kbd>
                </div>
            </div>

            <!-- results -->
            <div class="flex-1 overflow-y-auto p-2 min-h-0">
                {#if filteredResults.length === 0}
                    <div class="p-8 text-center text-sem-fg-muted">
                        {t("command_palette.no_results", { query })}
                    </div>
                {:else}
                    <div class="space-y-1">
                        {#each Object.entries(groupedResults) as [groupName, group] (groupName)}
                            <div>
                                <div class="px-3 py-2 text-[10px] font-bold text-gray-400 uppercase tracking-widest">
                                    {t(`command_palette.${groupName}`)}
                                </div>
                                {#each group as result (result.id)}
                                    <CommandPaletteResultRow
                                        {result}
                                        isHighlighted={highlightedId === result.id}
                                        onselect={executeResult}
                                        onhighlight={(id) => (rawHighlightedId = id)}
                                    />
                                {/each}
                            </div>
                        {/each}
                    </div>
                {/if}
            </div>

            <!-- footer -->
            <div
                class="p-3 bg-gray-50/50 dark:bg-zinc-900/50 border-t border-sem-border flex justify-center gap-6 text-[10px] font-bold text-gray-400 uppercase tracking-widest"
            >
                <div class="flex items-center gap-1.5">
                    <kbd class="px-1.5 py-0.5 bg-white dark:bg-zinc-800 border border-sem-border rounded-xs shadow-xs">
                        &uarr;&darr;
                    </kbd>
                    <span>{t("command_palette.footer_navigate")}</span>
                </div>
                <div class="flex items-center gap-1.5">
                    <kbd class="px-1.5 py-0.5 bg-white dark:bg-zinc-800 border border-sem-border rounded-xs shadow-xs">
                        Enter
                    </kbd>
                    <span>{t("command_palette.footer_select")}</span>
                </div>
            </div>
        </div>
    </div>
{/if}

<style>
    kbd {
        font-family: inherit;
    }
</style>

// meshchatx/src/frontend/components/CommandPalette.vue
<!-- SPDX-License-Identifier: 0BSD -->

<template>
    <transition name="slide-down">
        <div
            v-if="isOpen"
            class="fixed inset-x-0 top-0 z-200 flex items-start justify-center p-4 pt-[max(0.5rem,env(safe-area-inset-top))] pointer-events-none"
        >
            <div
                v-click-outside="close"
                class="w-full max-w-2xl bg-white/95 dark:bg-zinc-900/95 backdrop-blur-md rounded-2xl shadow-2xl border border-gray-200 dark:border-zinc-800 overflow-hidden flex flex-col max-h-[min(70dvh,70vh)] pointer-events-auto mt-2 sm:mt-8"
            >
                <!-- search input -->
                <div class="relative flex items-center p-4 border-b border-gray-100 dark:border-zinc-800">
                    <MaterialDesignIcon icon-name="magnify" class="size-6 text-gray-400 mr-3" />
                    <input
                        ref="input"
                        v-model="query"
                        type="text"
                        class="w-full bg-transparent border-none focus:ring-0 text-gray-900 dark:text-white placeholder-gray-400 text-lg"
                        :placeholder="$t('command_palette.search_placeholder')"
                        @keydown.down.prevent="moveHighlight(1)"
                        @keydown.up.prevent="moveHighlight(-1)"
                        @keydown.enter="executeAction"
                        @keydown.esc="close"
                    />
                    <div class="flex items-center gap-1 ml-2">
                        <kbd
                            class="px-2 py-1 text-xs font-semibold text-gray-500 bg-gray-100 dark:bg-zinc-800 border border-gray-200 dark:border-zinc-700 rounded-lg shadow-xs"
                            >ESC</kbd
                        >
                    </div>
                </div>

                <!-- results -->
                <div class="flex-1 overflow-y-auto p-2 min-h-0">
                    <div v-if="filteredResults.length === 0" class="p-8 text-center text-gray-500 dark:text-gray-400">
                        {{ $t("command_palette.no_results", { query: query }) }}
                    </div>
                    <div v-else class="space-y-1">
                        <div v-for="(group, groupName) in groupedResults" :key="groupName">
                            <div class="px-3 py-2 text-[10px] font-bold text-gray-400 uppercase tracking-widest">
                                {{ $t(`command_palette.${groupName}`) }}
                            </div>
                            <button
                                v-for="result in group"
                                :key="result.id"
                                type="button"
                                class="w-full flex items-center gap-3 p-3 rounded-xl transition-all text-left group"
                                :class="[
                                    highlightedId === result.id
                                        ? 'bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400'
                                        : 'hover:bg-gray-50 dark:hover:bg-zinc-800/50 text-gray-700 dark:text-zinc-300',
                                ]"
                                @click="executeResult(result)"
                                @mousemove="highlightedId = result.id"
                            >
                                <div
                                    class="size-10 rounded-xl flex items-center justify-center shrink-0 border transition-colors"
                                    :class="[
                                        highlightedId === result.id
                                            ? 'bg-blue-100 dark:bg-blue-900/40 border-blue-200 dark:border-blue-800'
                                            : 'bg-gray-100 dark:bg-zinc-800 border-gray-200 dark:border-zinc-700',
                                    ]"
                                >
                                    <LxmfUserIcon
                                        v-if="result.type === 'contact' || result.type === 'peer'"
                                        :custom-image="result.type === 'contact' ? result.contact.custom_image : ''"
                                        :icon-name="result.icon"
                                        :icon-foreground-colour="result.iconForeground"
                                        :icon-background-colour="result.iconBackground"
                                        icon-class="size-5"
                                    />
                                    <MaterialDesignIcon v-else :icon-name="result.icon" class="size-5" />
                                </div>
                                <div class="min-w-0 flex-1">
                                    <div class="font-bold truncate">{{ result.title }}</div>
                                    <div class="text-xs opacity-60 truncate">{{ result.description }}</div>
                                </div>
                                <MaterialDesignIcon
                                    v-if="highlightedId === result.id"
                                    icon-name="arrow-right"
                                    class="size-4 animate-in slide-in-from-left-2"
                                />
                            </button>
                        </div>
                    </div>
                </div>

                <!-- footer -->
                <div
                    class="p-3 bg-gray-50/50 dark:bg-zinc-900/50 border-t border-gray-100 dark:border-zinc-800 flex justify-center gap-6 text-[10px] font-bold text-gray-400 uppercase tracking-widest"
                >
                    <div class="flex items-center gap-1.5">
                        <kbd
                            class="px-1.5 py-0.5 bg-white dark:bg-zinc-800 border border-gray-200 dark:border-zinc-700 rounded-sm shadow-xs"
                            >↑↓</kbd
                        >
                        <span>{{ $t("command_palette.footer_navigate") }}</span>
                    </div>
                    <div class="flex items-center gap-1.5">
                        <kbd
                            class="px-1.5 py-0.5 bg-white dark:bg-zinc-800 border border-gray-200 dark:border-zinc-700 rounded-sm shadow-xs"
                            >Enter</kbd
                        >
                        <span>{{ $t("command_palette.footer_select") }}</span>
                    </div>
                </div>
            </div>
        </div>
    </transition>
</template>

<script>
import MaterialDesignIcon from "./MaterialDesignIcon.vue";
import LxmfUserIcon from "./LxmfUserIcon.vue";

import GlobalEmitter from "../js/GlobalEmitter";
import ToastUtils from "../js/ToastUtils";
import { listCommands } from "../js/registries/commandRegistry.js";

export default {
    name: "CommandPalette",
    components: { MaterialDesignIcon, LxmfUserIcon },
    data() {
        return {
            isOpen: false,
            query: "",
            highlightedId: null,
            peers: [],
            contacts: [],
        };
    },
    computed: {
        actions() {
            return listCommands();
        },
        allResults() {
            const results = this.actions.map((action) => ({
                ...action,
                title: this.$t(`command_palette.${action.title}`),
                description: this.$t(`command_palette.${action.description}`),
            }));

            // add peers
            if (Array.isArray(this.peers)) {
                for (const peer of this.peers) {
                    results.push({
                        id: `peer-${peer.destination_hash}`,
                        title: peer.custom_display_name ?? peer.display_name,
                        description: peer.destination_hash,
                        icon: peer.lxmf_user_icon?.icon_name ?? "account",
                        iconForeground: peer.lxmf_user_icon?.foreground_colour,
                        iconBackground: peer.lxmf_user_icon?.background_colour,
                        type: "peer",
                        peer: peer,
                    });
                }
            }

            // add contacts
            if (Array.isArray(this.contacts)) {
                for (const contact of this.contacts) {
                    results.push({
                        id: `contact-${contact.id}`,
                        title: contact.name,
                        description: this.$t("app.call") + ` ${contact.remote_identity_hash}`,
                        icon: "phone",
                        type: "contact",
                        contact: contact,
                    });
                }
            }

            return results;
        },
        filteredResults() {
            if (!this.query) return this.allResults.filter((r) => r.type === "navigation" || r.type === "action");
            const q = this.query.toLowerCase();
            return this.allResults.filter(
                (r) => r.title.toLowerCase().includes(q) || r.description.toLowerCase().includes(q)
            );
        },
        groupedResults() {
            const groups = {};
            for (const result of this.filteredResults) {
                const groupName =
                    result.type === "peer"
                        ? "group_recent"
                        : result.type === "contact"
                          ? "group_contacts"
                          : "group_actions";
                if (!groups[groupName]) groups[groupName] = [];
                groups[groupName].push(result);
            }
            return groups;
        },
    },
    watch: {
        filteredResults: {
            handler(newResults) {
                if (
                    newResults.length > 0 &&
                    (!this.highlightedId || !newResults.find((r) => r.id === this.highlightedId))
                ) {
                    this.highlightedId = newResults[0].id;
                }
            },
            immediate: true,
        },
    },
    mounted() {
        window.addEventListener("keydown", this.handleGlobalKeydown, true);
        GlobalEmitter.on("open-command-palette", this.open);
    },
    beforeUnmount() {
        window.removeEventListener("keydown", this.handleGlobalKeydown, true);
        GlobalEmitter.off("open-command-palette", this.open);
    },
    methods: {
        handleGlobalKeydown(e) {
            if ((e.metaKey || e.ctrlKey) && e.key === "k") {
                e.preventDefault();
                e.stopPropagation();
                this.toggle();
            }
        },
        async toggle() {
            if (this.isOpen) {
                this.close();
            } else {
                await this.open();
            }
        },
        async open() {
            this.query = "";
            this.isOpen = true;
            this.loadPeersAndContacts();
            this.$nextTick(() => {
                this.$refs.input?.focus();
            });
        },
        close() {
            this.isOpen = false;
        },
        async loadPeersAndContacts() {
            try {
                // fetch announces for "lxmf.delivery" aspect to get peers
                const peerResponse = await window.api.get(`/api/v1/announces`, {
                    params: { aspect: "lxmf.delivery", limit: 20 },
                });
                this.peers = peerResponse.data.announces;

                // fetch telephone contacts
                const contactResponse = await window.api.get("/api/v1/telephone/contacts");
                this.contacts =
                    contactResponse.data?.contacts ?? (Array.isArray(contactResponse.data) ? contactResponse.data : []);
            } catch (e) {
                console.error("Failed to load command palette data:", e);
            }
        },
        moveHighlight(step) {
            const index = this.filteredResults.findIndex((r) => r.id === this.highlightedId);
            let nextIndex = index + step;
            if (nextIndex < 0) nextIndex = this.filteredResults.length - 1;
            if (nextIndex >= this.filteredResults.length) nextIndex = 0;
            this.highlightedId = this.filteredResults[nextIndex].id;
        },
        executeAction() {
            const result = this.filteredResults.find((r) => r.id === this.highlightedId);
            if (result) {
                void this.executeResult(result);
            }
        },
        async executeResult(result) {
            this.close();
            if (result.type === "navigation") {
                this.$router.push(result.route);
            } else if (result.type === "peer") {
                this.$router.push({ name: "messages", params: { destinationHash: result.peer.destination_hash } });
            } else if (result.type === "contact") {
                this.dialContact(result.contact.remote_identity_hash);
            } else if (result.type === "action") {
                if (result.action === "sync") {
                    GlobalEmitter.emit("sync-propagation-node");
                } else if (result.action === "compose") {
                    try {
                        await this.$router.push({ name: "messages" });
                    } catch {
                        // already on messages, or navigation aborted
                    }
                    GlobalEmitter.emit("compose-new-message");
                } else if (result.action === "show-tutorial") {
                    GlobalEmitter.emit("show-tutorial");
                } else if (result.action === "show-changelog") {
                    GlobalEmitter.emit("show-changelog");
                }
            }
        },
        async dialContact(hash) {
            try {
                await window.api.post(`/api/v1/telephone/call/${hash}`);
                if (this.$route.name !== "call") {
                    this.$router.push({ name: "call" });
                }
            } catch (e) {
                ToastUtils.error(e.response?.data?.message || "Failed to initiate call");
            }
        },
    },
};
</script>

<style scoped>
.slide-down-enter-active,
.slide-down-leave-active {
    transition: all 0.3s cubic-bezier(0.16, 1, 0.3, 1);
}

.slide-down-enter-from,
.slide-down-leave-to {
    opacity: 0;
    transform: translateY(-20px) scale(0.98);
}

kbd {
    font-family: inherit;
}
</style>
