// meshchatx/src/frontend/ui/svelte/EmptyState.svelte
<!-- SPDX-License-Identifier: 0BSD -->

<script>
    import MaterialDesignIcon from "./MaterialDesignIcon.svelte";

    /**
     * @type {{
     *   icon?: string,
     *   title?: string,
     *   description?: string,
     *   plain?: boolean,
     *   class?: string,
     *   children?: import('svelte').Snippet,
     * }}
     */
    let { icon = "", title = "", description = "", plain = false, class: rootClass = "", children } = $props();

    const iconClass = $derived(
        plain ? "w-8 h-8 mx-auto mb-2 text-sem-fg-muted" : "w-12 h-12 mx-auto mb-4 text-sem-fg-muted"
    );
    const shellClass = $derived(
        [
            "text-center",
            plain
                ? "px-2 py-3"
                : "rounded-lg border border-dashed border-sem-border px-4 py-12 bg-sem-surface-muted/40",
            rootClass,
        ]
            .filter(Boolean)
            .join(" ")
    );
</script>

<div class={shellClass}>
    {#if icon}
        <MaterialDesignIcon iconName={icon} class={iconClass} />
    {/if}
    {#if title}
        <div class="text-base font-semibold text-sem-fg">{title}</div>
    {/if}
    {#if description}
        <p class="mt-2 text-sm text-sem-fg-muted max-w-md mx-auto">{description}</p>
    {/if}
    {#if children}
        <div class="flex justify-center {plain ? 'mt-3' : 'mt-4'}">
            {@render children()}
        </div>
    {/if}
</div>

// meshchatx/src/frontend/components/EmptyState.vue
<!-- SPDX-License-Identifier: 0BSD -->

<template>
    <div
        class="text-center"
        :class="[
            plain
                ? 'px-2 py-3'
                : 'rounded-lg border border-dashed border-sem-border px-4 py-12 bg-sem-surface-muted/40',
            rootClass,
        ]"
    >
        <MaterialDesignIcon
            v-if="icon"
            :icon-name="icon"
            :class="plain ? 'w-8 h-8 mx-auto mb-2 text-sem-fg-muted' : 'w-12 h-12 mx-auto mb-4 text-sem-fg-muted'"
        />
        <div v-if="title" class="text-base font-semibold text-sem-fg">{{ title }}</div>
        <p v-if="description" class="mt-2 text-sm text-sem-fg-muted max-w-md mx-auto">
            {{ description }}
        </p>
        <div v-if="$slots.action" class="flex justify-center" :class="plain ? 'mt-3' : 'mt-4'">
            <slot name="action" />
        </div>
    </div>
</template>

<script>
import MaterialDesignIcon from "./MaterialDesignIcon.vue";

export default {
    name: "EmptyState",
    components: {
        MaterialDesignIcon,
    },
    props: {
        icon: {
            type: String,
            default: "",
        },
        title: {
            type: String,
            default: "",
        },
        description: {
            type: String,
            default: "",
        },
        rootClass: {
            type: String,
            default: "",
        },
        plain: {
            type: Boolean,
            default: false,
        },
    },
};
</script>
