// meshchatx/src/frontend/ui/svelte/LoadingState.svelte
<!-- SPDX-License-Identifier: 0BSD -->

<script>
    import MaterialDesignIcon from "./MaterialDesignIcon.svelte";

    /**
     * @type {{
     *   message?: string,
     *   class?: string,
     * }}
     */
    let { message = "", class: rootClass = "" } = $props();
</script>

<div class="flex flex-col items-center justify-center px-4 py-10 text-center {rootClass}">
    <MaterialDesignIcon iconName="loading" class="size-8 animate-spin text-sem-accent motion-reduce:animate-none" />
    {#if message}
        <p class="mt-3 text-sm text-sem-fg-muted">{message}</p>
    {/if}
</div>

// meshchatx/src/frontend/components/LoadingState.vue
<!-- SPDX-License-Identifier: 0BSD -->

<template>
    <div class="flex flex-col items-center justify-center px-4 py-10 text-center" :class="rootClass">
        <MaterialDesignIcon
            icon-name="loading"
            class="size-8 animate-spin text-sem-accent motion-reduce:animate-none"
        />
        <p v-if="message" class="mt-3 text-sm text-sem-fg-muted">{{ message }}</p>
    </div>
</template>

<script>
import MaterialDesignIcon from "./MaterialDesignIcon.vue";

export default {
    name: "LoadingState",
    components: {
        MaterialDesignIcon,
    },
    props: {
        message: {
            type: String,
            default: "",
        },
        rootClass: {
            type: String,
            default: "",
        },
    },
};
</script>
