// meshchatx/src/frontend/components/map/MapBrowser.vue
<!-- SPDX-License-Identifier: 0BSD AND MIT -->

<template>
    <div class="flex flex-1 min-w-0 h-full flex-col overflow-hidden bg-sem-canvas text-sem-fg">
        <div
            v-if="showTabStrip"
            class="flex h-9 shrink-0 items-stretch overflow-x-auto border-b border-sem-border bg-sem-surface-muted"
            role="tablist"
        >
            <button
                v-for="tab in tabs"
                :key="tab.id"
                type="button"
                role="tab"
                :aria-selected="tab.id === activeTabId"
                class="group flex min-w-[7rem] max-w-[14rem] items-center gap-1.5 border-r border-sem-border px-3 text-sm transition-colors"
                :class="
                    tab.id === activeTabId
                        ? 'bg-sem-canvas font-medium text-sem-fg'
                        : 'text-sem-fg-muted hover:bg-sem-surface/80'
                "
                @click="selectTab(tab.id)"
            >
                <MaterialDesignIcon icon-name="map" class="size-4 shrink-0 opacity-70" />
                <input
                    v-if="renamingTabId === tab.id"
                    ref="renameInput"
                    v-model="renameDraft"
                    type="text"
                    class="min-w-0 flex-1 border-b border-sem-accent bg-transparent text-sm text-sem-fg outline-hidden"
                    :maxlength="64"
                    @click.stop
                    @keydown.enter.prevent="commitRename"
                    @keydown.esc.prevent="cancelRename"
                    @blur="commitRename"
                />
                <span
                    v-else
                    class="min-w-0 flex-1 truncate text-left"
                    :title="$t('map.tab_rename_hint')"
                    @dblclick.stop="startRename(tab.id)"
                    @touchend.stop="onTabLabelTouchEnd(tab, $event)"
                >
                    {{ tabTitle(tab) }}
                </span>
                <span
                    class="shrink-0 rounded p-0.5 text-sem-fg-muted opacity-0 transition-opacity hover:bg-sem-surface hover:text-sem-fg group-hover:opacity-100 group-focus-within:opacity-100"
                    :title="$t('common.cancel')"
                    @click.stop="closeTab(tab.id)"
                >
                    <MaterialDesignIcon icon-name="close" class="size-4" />
                </span>
            </button>
            <button
                type="button"
                class="flex w-9 shrink-0 items-center justify-center text-sem-fg-muted transition-colors hover:bg-sem-surface/80"
                :title="$t('map.new_tab_shortcut')"
                @click="addTab()"
            >
                <MaterialDesignIcon icon-name="plus" class="size-5" />
            </button>
        </div>

        <div class="flex flex-1 min-h-0 min-w-0 overflow-hidden">
            <MapPage
                v-for="tab in tabs"
                v-show="tab.id === activeTabId"
                :key="tab.storageId"
                embedded
                :tab-storage-id="tab.storageId"
                :tab-title="tabTitle(tab)"
                :is-active-tab="tab.id === activeTabId && isRouteActive"
                @update-title="onMapUpdateTitle(tab.id, $event)"
            />
        </div>
    </div>
</template>

<script>
import MapPage from "./MapPage.vue";
import MaterialDesignIcon from "../MaterialDesignIcon.vue";
import TileCache from "../../js/TileCache";
import GlobalEmitter from "../../js/GlobalEmitter";
import GlobalState from "../../js/GlobalState";
import { loadMapTabs, saveMapTabs } from "../../js/browserLayoutStore";
import { LEGACY_MAP_STATE_KEY, legacyMapTabStateKey, mapViewStateKey } from "../../js/mapStateKeys.js";

const DOUBLE_TAP_MS = 400;

function createStorageId() {
    if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
        return crypto.randomUUID();
    }
    return `map-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
}

export default {
    name: "MapBrowser",
    components: {
        MapPage,
        MaterialDesignIcon,
    },
    data() {
        return {
            tabs: [],
            activeTabId: null,
            nextTabId: 1,
            nextTabNumber: 1,
            isWideViewport: false,
            mediaQuery: null,
            mediaQueryListener: null,
            renamingTabId: null,
            renameDraft: "",
            lastLabelTap: { tabId: null, time: 0 },
            isRouteActive: true,
        };
    },
    computed: {
        showTabStrip() {
            return this.isWideViewport && this.tabs.length > 0;
        },
        activeTab() {
            return this.tabs.find((tab) => tab.id === this.activeTabId) || null;
        },
        tabLayoutSignature() {
            const tabs = this.tabs
                .map((tab) => `${tab.storageId || ""}|${tab.title || ""}|${tab.userRenamed ? "1" : "0"}`)
                .join("\u241f");
            const activeIndex = this.tabs.findIndex((tab) => tab.id === this.activeTabId);
            return `${activeIndex}\u241e${tabs}`;
        },
    },
    watch: {
        tabLayoutSignature() {
            this.persistTabs();
        },
    },
    async mounted() {
        this.setupViewportWatcher();
        window.addEventListener("keydown", this.handleKeydown, true);
        GlobalEmitter.on("identity-switched", this.onIdentitySwitched);

        if (!(await this.restoreTabs())) {
            const storageId = createStorageId();
            await this.migrateLegacyMapState(storageId);
            await this.addTab(null, true, storageId);
        }
    },
    activated() {
        this.isRouteActive = true;
    },
    deactivated() {
        this.isRouteActive = false;
    },
    beforeUnmount() {
        GlobalEmitter.off("identity-switched", this.onIdentitySwitched);
        this.teardownViewportWatcher();
        window.removeEventListener("keydown", this.handleKeydown, true);
    },
    methods: {
        onIdentitySwitched() {
            this.tabs = [];
            this.activeTabId = null;
            saveMapTabs({ tabs: [], activeIndex: 0 });
            const storageId = createStorageId();
            void this.addTab(null, true, storageId);
        },
        setupViewportWatcher() {
            if (typeof window === "undefined" || typeof window.matchMedia !== "function") {
                this.isWideViewport = false;
                return;
            }
            this.mediaQuery = window.matchMedia("(min-width: 768px)");
            this.isWideViewport = this.mediaQuery.matches;
            this.mediaQueryListener = (event) => {
                this.isWideViewport = event.matches;
            };
            if (typeof this.mediaQuery.addEventListener === "function") {
                this.mediaQuery.addEventListener("change", this.mediaQueryListener);
            } else if (typeof this.mediaQuery.addListener === "function") {
                this.mediaQuery.addListener(this.mediaQueryListener);
            }
        },
        teardownViewportWatcher() {
            if (!this.mediaQuery || !this.mediaQueryListener) {
                return;
            }
            if (typeof this.mediaQuery.removeEventListener === "function") {
                this.mediaQuery.removeEventListener("change", this.mediaQueryListener);
            } else if (typeof this.mediaQuery.removeListener === "function") {
                this.mediaQuery.removeListener(this.mediaQueryListener);
            }
            this.mediaQuery = null;
            this.mediaQueryListener = null;
        },
        defaultTabTitle(tabNumber = this.nextTabNumber) {
            return this.$t("map.tab_default_name", { number: tabNumber });
        },
        addTab(title = null, activate = true, storageId = null) {
            const tabNumber = this.nextTabNumber++;
            const id = this.nextTabId++;
            const resolvedStorageId = storageId || createStorageId();
            this.tabs.push({
                id,
                storageId: resolvedStorageId,
                title: title || this.defaultTabTitle(tabNumber),
                userRenamed: Boolean(title),
                tabNumber,
            });
            if (activate) {
                this.activeTabId = id;
            }
            return id;
        },
        tabTitle(tab) {
            if (tab.title) {
                return tab.title;
            }
            return this.$t("map.new_tab");
        },
        onMapUpdateTitle(tabId, title) {
            const tab = this.tabs.find((entry) => entry.id === tabId);
            if (!tab || tab.userRenamed) {
                return;
            }
            const trimmed = typeof title === "string" ? title.trim() : "";
            if (!trimmed) {
                return;
            }
            tab.title = trimmed.slice(0, 64);
        },
        startRename(tabId) {
            const tab = this.tabs.find((entry) => entry.id === tabId);
            if (!tab) {
                return;
            }
            this.renamingTabId = tabId;
            this.renameDraft = this.tabTitle(tab);
            this.$nextTick(() => {
                const input = this.$refs.renameInput;
                const el = Array.isArray(input) ? input.find((node) => node) : input;
                el?.focus?.();
                el?.select?.();
            });
        },
        commitRename() {
            if (this.renamingTabId == null) {
                return;
            }
            const tab = this.tabs.find((entry) => entry.id === this.renamingTabId);
            if (tab) {
                const trimmed = this.renameDraft.trim();
                tab.title = trimmed || this.defaultTabTitle(this.nextTabNumber - 1);
                tab.userRenamed = Boolean(trimmed);
            }
            this.renamingTabId = null;
            this.renameDraft = "";
        },
        cancelRename() {
            this.renamingTabId = null;
            this.renameDraft = "";
        },
        onTabLabelTouchEnd(tab, event) {
            const now = Date.now();
            if (this.lastLabelTap.tabId === tab.id && now - this.lastLabelTap.time <= DOUBLE_TAP_MS) {
                this.lastLabelTap = { tabId: null, time: 0 };
                this.startRename(tab.id);
                event.preventDefault();
                return;
            }
            this.lastLabelTap = { tabId: tab.id, time: now };
        },
        selectRelativeTab(offset) {
            if (this.tabs.length < 2) {
                return;
            }
            const index = this.tabs.findIndex((tab) => tab.id === this.activeTabId);
            if (index === -1) {
                return;
            }
            const nextIndex = (index + offset + this.tabs.length) % this.tabs.length;
            this.selectTab(this.tabs[nextIndex].id);
        },
        selectTabByIndex(index) {
            if (index >= 0 && index < this.tabs.length) {
                this.selectTab(this.tabs[index].id);
            }
        },
        handleKeydown(event) {
            if (!this.isWideViewport || this.$route?.name !== "map") {
                return;
            }

            const isMac = navigator.platform.toUpperCase().indexOf("MAC") >= 0;
            const mod = isMac ? event.metaKey : event.ctrlKey;
            const hasModifier = event.ctrlKey || event.metaKey || event.altKey;
            const isInput =
                ["INPUT", "TEXTAREA"].includes(document.activeElement?.tagName) ||
                document.activeElement?.isContentEditable;
            if (isInput && !hasModifier) {
                return;
            }

            const key = event.key.toLowerCase();

            if (mod && key === "t") {
                event.preventDefault();
                event.stopPropagation();
                this.addTab();
                return;
            }
            if (mod && key === "w") {
                event.preventDefault();
                event.stopPropagation();
                if (this.activeTabId != null) {
                    this.closeTab(this.activeTabId);
                }
                return;
            }
            if (event.ctrlKey && key === "tab") {
                event.preventDefault();
                event.stopPropagation();
                this.selectRelativeTab(event.shiftKey ? -1 : 1);
                return;
            }
            if (event.ctrlKey && key === "pageup") {
                event.preventDefault();
                event.stopPropagation();
                this.selectRelativeTab(-1);
                return;
            }
            if (event.ctrlKey && key === "pagedown") {
                event.preventDefault();
                event.stopPropagation();
                this.selectRelativeTab(1);
                return;
            }
            if (mod && key >= "1" && key <= "9") {
                event.preventDefault();
                event.stopPropagation();
                this.selectTabByIndex(parseInt(key, 10) - 1);
            }
        },
        async migrateLegacyMapState(storageId) {
            try {
                const identityHash = GlobalState.config?.identity_hash || null;
                const tabKey = mapViewStateKey(identityHash, storageId);
                const existing = await TileCache.getMapState(tabKey);
                if (existing) {
                    return;
                }
                const unscopedTab = await TileCache.getMapState(legacyMapTabStateKey(storageId));
                if (unscopedTab) {
                    await TileCache.setMapState(tabKey, unscopedTab);
                    return;
                }
                const legacy = await TileCache.getMapState(LEGACY_MAP_STATE_KEY);
                if (!legacy) {
                    return;
                }
                await TileCache.setMapState(tabKey, legacy);
            } catch {
                // migration is best-effort
            }
        },
        async restoreTabs() {
            const saved = loadMapTabs();
            if (!saved || saved.tabs.length === 0) {
                return false;
            }

            let maxTabNumber = 0;
            this.tabs = saved.tabs.map((tab, index) => {
                const tabNumber = Number.isInteger(tab.tabNumber) && tab.tabNumber > 0 ? tab.tabNumber : index + 1;
                maxTabNumber = Math.max(maxTabNumber, tabNumber);
                return {
                    id: this.nextTabId++,
                    storageId: typeof tab.storageId === "string" && tab.storageId ? tab.storageId : createStorageId(),
                    title: typeof tab.title === "string" && tab.title ? tab.title : this.defaultTabTitle(tabNumber),
                    userRenamed: tab.userRenamed === true,
                    tabNumber,
                };
            });

            if (this.tabs.length === 0) {
                return false;
            }

            this.nextTabNumber = maxTabNumber + 1;

            const activeIndex =
                Number.isInteger(saved.activeIndex) && saved.activeIndex >= 0 && saved.activeIndex < this.tabs.length
                    ? saved.activeIndex
                    : 0;
            this.activeTabId = this.tabs[activeIndex].id;

            await this.migrateLegacyMapState(this.tabs[0].storageId);
            return true;
        },
        persistTabs() {
            const activeIndex = this.tabs.findIndex((tab) => tab.id === this.activeTabId);
            saveMapTabs({
                tabs: this.tabs.map((tab) => ({
                    storageId: tab.storageId,
                    title: tab.title || null,
                    userRenamed: tab.userRenamed === true,
                    tabNumber: tab.tabNumber || null,
                })),
                activeIndex: activeIndex < 0 ? 0 : activeIndex,
            });
        },
        selectTab(tabId) {
            if (this.renamingTabId != null) {
                this.commitRename();
            }
            if (this.activeTabId === tabId) {
                return;
            }
            this.activeTabId = tabId;
        },
        closeTab(tabId) {
            if (this.renamingTabId === tabId) {
                this.cancelRename();
            }

            const index = this.tabs.findIndex((tab) => tab.id === tabId);
            if (index === -1) {
                return;
            }

            const closing = this.tabs[index];
            const wasActive = closing.id === this.activeTabId;
            this.tabs.splice(index, 1);

            if (this.tabs.length === 0) {
                this.addTab();
                return;
            }

            if (wasActive) {
                const neighbour = this.tabs[index] || this.tabs[index - 1] || this.tabs[0];
                this.activeTabId = neighbour.id;
            }
        },
    },
};
</script>

// meshchatx/src/frontend/features/map/components/MapBrowser.svelte
<!-- SPDX-License-Identifier: 0BSD -->

<script lang="ts">
    import { onMount, onDestroy, tick } from "svelte";
    import MapPage from "../MapPage.svelte";
    import MapTabBar from "./MapTabBar.svelte";
    import TileCache from "../../../js/TileCache.js";
    import GlobalEmitter from "../../../js/GlobalEmitter.js";
    import GlobalState from "../../../js/GlobalState.js";
    import { loadMapTabs, saveMapTabs } from "../../../js/browserLayoutStore.js";
    import { LEGACY_MAP_STATE_KEY, legacyMapTabStateKey, mapViewStateKey } from "../../../js/mapStateKeys.js";
    import { t } from "../../../js/i18n.js";
    import { DOUBLE_TAP_MS, MAX_MAP_TABS } from "../lib/constants.js";
    import type { MapTab } from "../lib/types.js";

    interface Props {
        route?: any;
    }

    let { route: _route = null }: Props = $props();

    let tabs = $state<MapTab[]>([]);
    let activeTabId = $state<number | null>(null);
    let nextTabId = 1;
    let nextTabNumber = 1;
    let isWideViewport = $state(false);
    let mediaQuery: MediaQueryList | null = null;
    let mediaQueryListener: ((event: MediaQueryListEvent) => void) | null = null;
    let renamingTabId = $state<number | null>(null);
    let renameDraft = $state("");
    let lastLabelTap = { tabId: null as number | null, time: 0 };
    let isRouteActive = $state(true);
    let renameInputEl = $state<HTMLInputElement | null>(null);

    const showTabStrip = $derived(isWideViewport && tabs.length > 0);
    const canAddTab = $derived(tabs.length < MAX_MAP_TABS);
    const _activeTab = $derived(tabs.find((tab) => tab.id === activeTabId) || null);

    const tabLayoutSignature = $derived.by(() => {
        const tabsStr = tabs
            .map((tab) => `${tab.storageId || ""}|${tab.title || ""}|${tab.userRenamed ? "1" : "0"}`)
            .join("\u241f");
        const activeIndex = tabs.findIndex((tab) => tab.id === activeTabId);
        return `${activeIndex}\u241e${tabsStr}`;
    });

    $effect(() => {
        if (tabLayoutSignature) {
            persistTabs();
        }
    });

    function createStorageId(): string {
        if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
            return crypto.randomUUID();
        }
        return `map-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
    }

    function defaultTabTitle(tabNumber = nextTabNumber): string {
        return t("map.tab_default_name", { number: tabNumber });
    }

    export function addTab(
        title: string | null = null,
        activate = true,
        storageId: string | null = null
    ): number | null {
        if (tabs.length >= MAX_MAP_TABS) {
            return null;
        }
        const tabNumber = nextTabNumber++;
        const id = nextTabId++;
        const resolvedStorageId = storageId || createStorageId();
        const newTab: MapTab = {
            id,
            storageId: resolvedStorageId,
            title: title || defaultTabTitle(tabNumber),
            userRenamed: Boolean(title),
            tabNumber,
        };
        tabs.push(newTab);
        if (activate) {
            activeTabId = id;
        }
        return id;
    }

    export function tabTitle(tab: { title?: string | null }): string {
        if (tab.title) {
            return tab.title;
        }
        return t("map.new_tab");
    }

    export function onMapUpdateTitle(tabId: number, title: string) {
        const tab = tabs.find((entry) => entry.id === tabId);
        if (!tab || tab.userRenamed) {
            return;
        }
        const trimmed = typeof title === "string" ? title.trim() : "";
        if (!trimmed) {
            return;
        }
        tab.title = trimmed.slice(0, 64);
    }

    export async function startRename(tabId: number) {
        const tab = tabs.find((entry) => entry.id === tabId);
        if (!tab) return;
        renamingTabId = tabId;
        renameDraft = tabTitle(tab);
        await tick();
        renameInputEl?.focus();
        renameInputEl?.select();
    }

    export function commitRename() {
        if (renamingTabId == null) return;
        const tab = tabs.find((entry) => entry.id === renamingTabId);
        if (tab) {
            const trimmed = renameDraft.trim();
            tab.title = trimmed || defaultTabTitle(nextTabNumber - 1);
            tab.userRenamed = Boolean(trimmed);
        }
        renamingTabId = null;
        renameDraft = "";
    }

    export function cancelRename() {
        renamingTabId = null;
        renameDraft = "";
    }

    function onTabLabelTouchEnd(tab: MapTab, event: TouchEvent) {
        const now = Date.now();
        if (lastLabelTap.tabId === tab.id && now - lastLabelTap.time <= DOUBLE_TAP_MS) {
            lastLabelTap = { tabId: null, time: 0 };
            startRename(tab.id);
            event.preventDefault();
            return;
        }
        lastLabelTap = { tabId: tab.id, time: now };
    }

    export function selectTab(tabId: number) {
        if (renamingTabId != null) {
            commitRename();
        }
        if (activeTabId === tabId) {
            return;
        }
        activeTabId = tabId;
    }

    export function closeTab(tabId: number) {
        if (renamingTabId === tabId) {
            cancelRename();
        }
        const index = tabs.findIndex((tab) => tab.id === tabId);
        if (index === -1) return;

        const closing = tabs[index];
        const wasActive = closing.id === activeTabId;
        tabs.splice(index, 1);

        if (tabs.length === 0) {
            addTab();
            return;
        }
        if (wasActive) {
            const neighbour = tabs[index] || tabs[index - 1] || tabs[0];
            activeTabId = neighbour.id;
        }
    }

    export function selectRelativeTab(offset: number) {
        if (tabs.length < 2) return;
        const index = tabs.findIndex((tab) => tab.id === activeTabId);
        if (index === -1) return;
        const nextIndex = (index + offset + tabs.length) % tabs.length;
        selectTab(tabs[nextIndex].id);
    }

    export function selectTabByIndex(index: number) {
        if (index >= 0 && index < tabs.length) {
            selectTab(tabs[index].id);
        }
    }

    function handleKeydown(event: KeyboardEvent) {
        if (!isWideViewport) return;

        const isMac = typeof navigator !== "undefined" && navigator.platform.toUpperCase().indexOf("MAC") >= 0;
        const mod = isMac ? event.metaKey : event.ctrlKey;
        const hasModifier = event.ctrlKey || event.metaKey || event.altKey;
        const target = document.activeElement as HTMLElement | null;
        const isInput = target && (["INPUT", "TEXTAREA"].includes(target.tagName) || target.isContentEditable);
        if (isInput && !hasModifier) return;

        const key = event.key.toLowerCase();
        if (mod && key === "t") {
            event.preventDefault();
            event.stopPropagation();
            if (canAddTab) addTab();
            return;
        }
        if (mod && key === "w") {
            event.preventDefault();
            event.stopPropagation();
            if (activeTabId != null) closeTab(activeTabId);
            return;
        }
        if (event.ctrlKey && key === "tab") {
            event.preventDefault();
            event.stopPropagation();
            selectRelativeTab(event.shiftKey ? -1 : 1);
            return;
        }
        if (event.ctrlKey && key === "pageup") {
            event.preventDefault();
            event.stopPropagation();
            selectRelativeTab(-1);
            return;
        }
        if (event.ctrlKey && key === "pagedown") {
            event.preventDefault();
            event.stopPropagation();
            selectRelativeTab(1);
            return;
        }
        if (mod && key >= "1" && key <= "9") {
            event.preventDefault();
            event.stopPropagation();
            selectTabByIndex(parseInt(key, 10) - 1);
        }
    }

    async function migrateLegacyMapState(storageId: string) {
        try {
            const identityHash = (GlobalState.config as any)?.identity_hash || null;
            const tabKey = mapViewStateKey(identityHash, storageId);
            const existing = await TileCache.getMapState(tabKey);
            if (existing) return;
            const unscopedTab = await TileCache.getMapState(legacyMapTabStateKey(storageId));
            if (unscopedTab) {
                await TileCache.setMapState(tabKey, unscopedTab);
                return;
            }
            const legacy = await TileCache.getMapState(LEGACY_MAP_STATE_KEY);
            if (!legacy) return;
            await TileCache.setMapState(tabKey, legacy);
        } catch {
            // migration is best effort
        }
    }

    export async function restoreTabs(): Promise<boolean> {
        const saved = loadMapTabs();
        if (!saved || !saved.tabs || saved.tabs.length === 0) {
            return false;
        }
        let maxTabNumber = 0;
        tabs = saved.tabs.slice(0, MAX_MAP_TABS).map((tab: any, index: number) => {
            const tabNumber = Number.isInteger(tab.tabNumber) && tab.tabNumber > 0 ? tab.tabNumber : index + 1;
            maxTabNumber = Math.max(maxTabNumber, tabNumber);
            return {
                id: nextTabId++,
                storageId: typeof tab.storageId === "string" && tab.storageId ? tab.storageId : createStorageId(),
                title: typeof tab.title === "string" && tab.title ? tab.title : defaultTabTitle(tabNumber),
                userRenamed: tab.userRenamed === true,
                tabNumber,
            };
        });

        if (tabs.length === 0) return false;

        nextTabNumber = maxTabNumber + 1;
        const activeIndex =
            Number.isInteger(saved.activeIndex) && saved.activeIndex >= 0 && saved.activeIndex < tabs.length
                ? saved.activeIndex
                : 0;
        activeTabId = tabs[activeIndex].id;
        await migrateLegacyMapState(tabs[0].storageId);
        return true;
    }

    function persistTabs() {
        const activeIndex = tabs.findIndex((tab) => tab.id === activeTabId);
        saveMapTabs({
            tabs: tabs.map((tab) => ({
                storageId: tab.storageId,
                title: tab.title || null,
                userRenamed: tab.userRenamed === true,
                tabNumber: tab.tabNumber || null,
            })),
            activeIndex: activeIndex < 0 ? 0 : activeIndex,
        });
    }

    function onIdentitySwitched() {
        tabs = [];
        activeTabId = null;
        saveMapTabs({ tabs: [], activeIndex: 0 });
        const storageId = createStorageId();
        void addTab(null, true, storageId);
    }

    function setupViewportWatcher() {
        if (typeof window === "undefined" || typeof window.matchMedia !== "function") {
            isWideViewport = false;
            return;
        }
        mediaQuery = window.matchMedia("(min-width: 768px)");
        isWideViewport = mediaQuery.matches;
        mediaQueryListener = (event: MediaQueryListEvent) => {
            isWideViewport = event.matches;
        };
        if (typeof mediaQuery.addEventListener === "function") {
            mediaQuery.addEventListener("change", mediaQueryListener);
        } else if (typeof (mediaQuery as any).addListener === "function") {
            (mediaQuery as any).addListener(mediaQueryListener);
        }
    }

    function teardownViewportWatcher() {
        if (!mediaQuery || !mediaQueryListener) return;
        if (typeof mediaQuery.removeEventListener === "function") {
            mediaQuery.removeEventListener("change", mediaQueryListener);
        } else if (typeof (mediaQuery as any).removeListener === "function") {
            (mediaQuery as any).removeListener(mediaQueryListener);
        }
        mediaQuery = null;
        mediaQueryListener = null;
    }

    onMount(async () => {
        setupViewportWatcher();
        window.addEventListener("keydown", handleKeydown, true);
        GlobalEmitter.on("identity-switched", onIdentitySwitched);

        if (!(await restoreTabs())) {
            const storageId = createStorageId();
            await migrateLegacyMapState(storageId);
            addTab(null, true, storageId);
        }
    });

    onDestroy(() => {
        GlobalEmitter.off("identity-switched", onIdentitySwitched);
        teardownViewportWatcher();
        window.removeEventListener("keydown", handleKeydown, true);
    });
</script>

<div class="flex flex-1 min-w-0 h-full flex-col overflow-hidden bg-sem-canvas text-sem-fg">
    {#if showTabStrip}
        <MapTabBar
            {tabs}
            {activeTabId}
            {renamingTabId}
            bind:renameDraft
            {canAddTab}
            bind:renameInputEl
            {tabTitle}
            onselect={selectTab}
            onstartrename={startRename}
            oncommitrename={commitRename}
            oncancelrename={cancelRename}
            ontablabeltouchend={onTabLabelTouchEnd}
            onclosetab={closeTab}
            onaddtab={() => addTab()}
        />
    {/if}

    <div class="flex flex-1 min-h-0 min-w-0 overflow-hidden">
        {#each tabs as tab (tab.storageId)}
            <div class="flex-1 min-h-0 min-w-0 {tab.id === activeTabId ? 'flex' : 'hidden'}">
                <MapPage
                    embedded={true}
                    tabStorageId={tab.storageId}
                    tabTitle={tabTitle(tab)}
                    isActiveTab={tab.id === activeTabId && isRouteActive}
                    onUpdateTitle={(title) => onMapUpdateTitle(tab.id, title)}
                />
            </div>
        {/each}
    </div>
</div>
