// meshchatx/src/frontend/components/SidebarLink.vue
<!-- SPDX-License-Identifier: 0BSD AND MIT -->

<template>
    <RouterLink v-slot="{ href, navigate, isActive }" :to="to" custom>
        <a
            :href="href"
            type="button"
            :draggable="false"
            :aria-label="ariaLabel"
            :aria-current="isActive ? 'page' : null"
            :class="[
                collapsedActiveClass(navActive(isActive)),
                isCollapsed ? 'overflow-visible justify-center rounded-none' : 'overflow-hidden rounded-r-full mr-2',
            ]"
            class="sidebar-nav-link group focus-visible:outline-sem-focus"
            @click="handleNavigate($event, navigate)"
        >
            <span class="my-auto shrink-0">
                <slot name="icon"></slot>
            </span>
            <span v-if="!isCollapsed" class="my-auto flex w-full truncate transition-all duration-300">
                <slot name="text"></slot>
            </span>
        </a>
    </RouterLink>
</template>

<script>
import { navRouteIsActive } from "../js/navRouteActive.js";

export default {
    name: "SidebarLink",
    props: {
        ariaLabel: {
            type: String,
            default: "",
        },
        to: {
            type: Object,
            required: true,
        },
        isCollapsed: {
            type: Boolean,
            default: false,
        },
        editMode: {
            type: Boolean,
            default: false,
        },
    },
    emits: ["click"],
    methods: {
        navActive(routerIsActive) {
            if (navRouteIsActive(this.to?.name, this.$route?.name)) {
                return true;
            }
            return Boolean(routerIsActive);
        },
        collapsedActiveClass(isActive) {
            if (this.isCollapsed && isActive) {
                return [
                    "text-sem-accent",
                    "bg-sem-surface-muted",
                    "shadow-[inset_2px_2px_5px_rgba(0,0,0,0.12),inset_-1px_-1px_2px_rgba(255,255,255,0.6)]",
                    "dark:shadow-[inset_2px_2px_6px_rgba(0,0,0,0.72),inset_-1px_-1px_1px_rgba(255,255,255,0.07)]",
                ].join(" ");
            }
            if (isActive) {
                return "sidebar-nav-link--active";
            }
            return "sidebar-nav-link--hover";
        },
        handleNavigate(event, navigate) {
            this.$emit("click");
            if (this.editMode) {
                event.preventDefault();
                return;
            }
            navigate(event);
        },
    },
};
</script>

// meshchatx/src/frontend/features/app-shell/components/SidebarLink.svelte
<!-- SPDX-License-Identifier: 0BSD -->

<script lang="ts">
    import type { Snippet } from "svelte";
    import { navRouteIsActive } from "../../../js/navRouteActive.js";

    interface RouteTarget {
        name?: string;
        path?: string;
        params?: Record<string, unknown>;
        query?: Record<string, unknown>;
    }

    interface Props {
        to: RouteTarget;
        isCollapsed?: boolean;
        editMode?: boolean;
        activeRouteName?: string;
        class?: string;
        onclick?: (event: MouseEvent) => void;
        icon?: Snippet;
        text?: Snippet;
    }

    let {
        to,
        isCollapsed = false,
        editMode = false,
        activeRouteName = "",
        class: className = "",
        onclick,
        icon,
        text,
    }: Props = $props();

    const isActive = $derived(navRouteIsActive(to?.name, activeRouteName));

    const href = $derived.by(() => {
        if (to?.path) return `#${to.path}`;
        if (to?.name) return `#/${to.name}`;
        return "#";
    });

    const activeClass = $derived.by(() => {
        if (isCollapsed && isActive) {
            return "text-sem-accent bg-sem-surface-muted shadow-[inset_2px_2px_5px_rgba(0,0,0,0.12),inset_-1px_-1px_2px_rgba(255,255,255,0.6)] dark:shadow-[inset_2px_2px_6px_rgba(0,0,0,0.72),inset_-1px_-1px_1px_rgba(255,255,255,0.07)]";
        }
        if (isActive) {
            return "sidebar-nav-link--active";
        }
        return "sidebar-nav-link--hover";
    });

    function handleClick(event: MouseEvent): void {
        onclick?.(event);
        if (editMode) {
            event.preventDefault();
        }
    }
</script>

<a
    {href}
    draggable="false"
    class="sidebar-nav-link group focus-visible:outline-sem-focus {activeClass} {isCollapsed
        ? 'overflow-visible justify-center rounded-none'
        : 'overflow-hidden rounded-r-full mr-2'} {className}"
    onclick={handleClick}
>
    <span class="my-auto shrink-0">
        {#if icon}
            {@render icon()}
        {/if}
    </span>
    {#if !isCollapsed}
        <span class="my-auto flex w-full truncate transition-all duration-300">
            {#if text}
                {@render text()}
            {/if}
        </span>
    {/if}
</a>
