// meshchatx/src/frontend/components/tools/PaperMessagePage.vue
<!-- SPDX-License-Identifier: 0BSD -->

<template>
    <div class="flex flex-col flex-1 overflow-hidden min-w-0 bg-sem-canvas">
        <ToolsPageHeader
            icon="qrcode"
            :title="$t('tools.paper_message.title')"
            :description="$t('tools.paper_message.description')"
            accent="blue"
        />
        <div class="flex-1 overflow-y-auto w-full pb-[max(1rem,env(safe-area-inset-bottom))]">
            <div class="p-3 sm:p-4 md:p-6 max-w-5xl mx-auto w-full space-y-4 min-w-0">
                <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
                    <!-- composer -->
                    <div class="space-y-4 min-w-0">
                        <section class="rounded-lg border border-sem-border overflow-hidden bg-sem-surface">
                            <div
                                class="px-4 py-3 border-b border-sem-border bg-sem-surface-muted/80 dark:bg-sem-surface"
                            >
                                <h2 class="flex items-center gap-2 text-base font-semibold text-sem-fg">
                                    <MaterialDesignIcon
                                        icon-name="pencil-outline"
                                        class="size-5 text-sem-fg-muted shrink-0"
                                    />
                                    Compose Message
                                </h2>
                            </div>
                            <div class="px-4 py-4 space-y-3 text-sem-fg">
                                <div>
                                    <label
                                        class="block text-[10px] font-bold text-sem-fg-muted uppercase tracking-widest mb-1.5"
                                    >
                                        Recipient Address
                                    </label>
                                    <input
                                        v-model="destinationHash"
                                        type="text"
                                        placeholder="Destination hash (e.g. a39610...)"
                                        class="input-field font-mono text-sm"
                                        maxlength="32"
                                    />
                                </div>
                                <div>
                                    <label
                                        class="block text-[10px] font-bold text-sem-fg-muted uppercase tracking-widest mb-1.5"
                                    >
                                        Subject (Optional)
                                    </label>
                                    <input
                                        v-model="title"
                                        type="text"
                                        placeholder="Message title..."
                                        class="input-field text-sm"
                                    />
                                </div>
                                <div>
                                    <label
                                        class="block text-[10px] font-bold text-sem-fg-muted uppercase tracking-widest mb-1.5"
                                    >
                                        Message Content
                                    </label>
                                    <textarea
                                        v-model="content"
                                        rows="4"
                                        placeholder="Type your message here..."
                                        class="input-field resize-none text-sm"
                                    ></textarea>
                                </div>
                                <button
                                    type="button"
                                    class="w-full flex items-center justify-center gap-2 py-2.5 px-4 bg-sem-action-primary hover:bg-sem-action-primary-hover text-sem-action-primary-text rounded-xl font-bold shadow-lg shadow-sem-action-primary/20 transition-all active:scale-[0.98] disabled:opacity-50 disabled:pointer-events-none text-sm"
                                    :disabled="!canGenerate || isGenerating"
                                    @click="generatePaperMessage"
                                >
                                    <template v-if="isGenerating">
                                        <div
                                            class="size-4 border-2 border-white/20 border-t-white rounded-full animate-spin"
                                        ></div>
                                        Generating...
                                    </template>
                                    <template v-else>
                                        <MaterialDesignIcon icon-name="qrcode-plus" class="size-5" />
                                        Generate Paper Message
                                    </template>
                                </button>
                            </div>
                        </section>

                        <!-- read / ingest section -->
                        <section class="rounded-lg border border-sem-border overflow-hidden bg-sem-surface">
                            <div
                                class="px-4 py-3 border-b border-sem-border bg-sem-surface-muted/80 dark:bg-sem-surface"
                            >
                                <h2 class="flex items-center gap-2 text-base font-semibold text-sem-fg">
                                    <MaterialDesignIcon
                                        icon-name="qrcode-scan"
                                        class="size-5 text-sem-fg-muted shrink-0"
                                    />
                                    Ingest Paper Message
                                </h2>
                            </div>
                            <div class="px-4 py-4 space-y-3 text-sem-fg">
                                <p class="text-xs text-sem-fg-muted">
                                    Paste an LXMF, LXMA, or LXM URI to decode and ingest.
                                </p>
                                <div class="flex flex-col sm:flex-row gap-2">
                                    <input
                                        v-model="ingestUri"
                                        type="text"
                                        placeholder="lxmf://... or lxma://..."
                                        class="input-field flex-1 min-w-0 font-mono text-sm"
                                        @keydown.enter="ingestPaperMessage"
                                    />
                                    <button
                                        type="button"
                                        class="inline-flex items-center justify-center gap-2 px-3 py-2.5 sm:py-2 bg-sem-surface-muted text-sem-fg-muted rounded-lg hover:bg-sem-surface-muted hover:bg-sem-surface-muted transition-colors shrink-0"
                                        @click="pasteFromClipboard"
                                    >
                                        <MaterialDesignIcon icon-name="content-paste" class="size-5" />
                                        <span class="sm:hidden text-sm font-medium">Paste</span>
                                    </button>
                                    <button
                                        v-if="cameraSupported"
                                        type="button"
                                        class="inline-flex items-center justify-center gap-2 px-3 py-2.5 sm:py-2 bg-sem-surface-muted text-sem-fg-muted rounded-lg hover:bg-sem-surface-muted hover:bg-sem-surface-muted transition-colors shrink-0"
                                        @click="openIngestScannerModal"
                                    >
                                        <MaterialDesignIcon icon-name="qrcode-scan" class="size-5" />
                                        <span class="sm:hidden text-sm font-medium">{{ $t("messages.scan_qr") }}</span>
                                    </button>
                                </div>
                                <button
                                    type="button"
                                    class="w-full py-2.5 px-4 bg-sem-surface-muted text-sem-fg-secondary rounded-xl font-bold hover:bg-sem-surface-muted hover:bg-sem-surface-muted transition-all active:scale-[0.98] text-sm"
                                    :disabled="!ingestUri"
                                    @click="ingestPaperMessage"
                                >
                                    Read LXM
                                </button>
                                <p v-if="!cameraSupported" class="text-xs text-sem-fg-muted">
                                    {{ $t("messages.camera_not_supported") }}
                                </p>
                            </div>
                        </section>
                    </div>

                    <!-- preview / result -->
                    <div class="space-y-4 min-w-0">
                        <section
                            v-if="generatedUri"
                            class="rounded-lg border border-sem-border overflow-hidden bg-sem-surface"
                        >
                            <div class="px-4 py-3 border-b border-sem-border bg-sem-info/15 dark:bg-sem-info/15">
                                <h2 class="text-base font-semibold text-sem-accent">Generated QR Code</h2>
                            </div>
                            <div class="px-4 py-4 sm:p-6 flex flex-col items-center text-sem-fg">
                                <div class="p-3 bg-sem-surface rounded-2xl shadow-inner border border-sem-border mb-6">
                                    <div class="size-40 sm:size-48 flex items-center justify-center overflow-hidden">
                                        <canvas ref="qrcode"></canvas>
                                    </div>
                                </div>

                                <div class="w-full space-y-3">
                                    <div
                                        class="bg-sem-surface-muted/50 rounded-2xl p-3 border border-sem-border border-sem-border/50"
                                    >
                                        <label
                                            class="block text-[9px] font-bold text-sem-fg-muted uppercase tracking-widest mb-1.5"
                                        >
                                            LXMF URI
                                        </label>
                                        <div class="flex gap-2">
                                            <div
                                                class="flex-1 font-mono text-[10px] break-all text-sem-fg-muted bg-sem-surface p-2 rounded-lg border border-sem-border max-h-20 overflow-y-auto"
                                            >
                                                {{ generatedUri }}
                                            </div>
                                            <button
                                                type="button"
                                                class="size-9 flex items-center justify-center bg-sem-surface text-sem-fg-muted rounded-lg border border-sem-border hover:bg-sem-info/15 hover:text-sem-info hover:border-sem-info transition-all shadow-xs"
                                                title="Copy URI"
                                                @click="copyUri"
                                            >
                                                <MaterialDesignIcon icon-name="content-copy" class="size-4" />
                                            </button>
                                        </div>
                                    </div>

                                    <div class="flex flex-col sm:flex-row gap-2 pt-1">
                                        <button
                                            type="button"
                                            class="flex-1 flex items-center justify-center gap-2 py-3 sm:py-2.5 px-4 bg-sem-action-primary hover:bg-sem-action-primary-hover text-sem-action-primary-text rounded-lg font-bold transition-all active:scale-[0.98] text-sm min-h-[44px]"
                                            @click="printQRCode"
                                        >
                                            <MaterialDesignIcon icon-name="printer" class="size-4" />
                                            Print
                                        </button>
                                        <button
                                            type="button"
                                            class="flex-1 flex items-center justify-center gap-2 py-3 sm:py-2.5 px-4 bg-sem-success hover:bg-sem-success text-white rounded-lg font-bold transition-all active:scale-[0.98] text-sm min-h-[44px]"
                                            :disabled="isSending"
                                            @click="sendPaperMessage"
                                        >
                                            <template v-if="isSending">
                                                <div
                                                    class="size-4 border-2 border-white/20 border-t-white rounded-full animate-spin"
                                                ></div>
                                                Sending...
                                            </template>
                                            <template v-else>
                                                <MaterialDesignIcon icon-name="send" class="size-4" />
                                                Send
                                            </template>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </section>

                        <div
                            v-else
                            class="rounded-lg border border-dashed border-sem-border bg-sem-surface-muted/80 dark:bg-sem-surface flex flex-col items-center justify-center p-6 sm:p-8 text-center min-h-[240px] sm:min-h-[280px] sm:h-[320px]"
                        >
                            <div class="p-3 bg-sem-surface-muted text-sem-fg-muted rounded-full mb-3">
                                <MaterialDesignIcon icon-name="qrcode" class="size-10" />
                            </div>
                            <h3 class="text-base font-bold text-sem-fg mb-1">No QR Code Generated</h3>
                            <p class="text-xs text-sem-fg-muted max-w-[200px]">
                                Fill out the message details and click generate to create a signed paper message.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div
            v-if="isIngestScannerModalOpen"
            class="fixed inset-0 z-210 flex items-center justify-center p-4 bg-black/70 backdrop-blur-xs"
            @click.self="closeIngestScannerModal"
        >
            <div class="w-full max-w-xl rounded-2xl bg-sem-surface shadow-2xl overflow-hidden">
                <div class="px-5 py-4 border-b border-sem-border flex items-center justify-between">
                    <h3 class="text-lg font-bold text-sem-fg">{{ $t("messages.scan_qr") }}</h3>
                    <button type="button" class="text-sem-fg-muted hover:text-sem-fg" @click="closeIngestScannerModal">
                        <MaterialDesignIcon icon-name="close" class="size-5" />
                    </button>
                </div>
                <div class="p-5 space-y-3">
                    <video
                        ref="ingestScannerVideo"
                        class="w-full rounded-xl bg-black max-h-[60vh]"
                        autoplay
                        playsinline
                        muted
                    ></video>
                    <div class="text-sm text-sem-fg-muted">
                        {{ ingestScannerError || $t("messages.scanner_hint") }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import QRCode from "qrcode";
import MaterialDesignIcon from "../MaterialDesignIcon.vue";
import WebSocketConnection from "../../js/WebSocketConnection";
import ToastUtils from "../../js/ToastUtils";
import Utils from "../../js/Utils";
import {
    attachStreamToVideo,
    decodeQrFromVideo,
    describeCameraError as describeQrCameraError,
    isCameraSupported,
    startCameraStream,
} from "../../js/qrScannerUtils";
import ToolsPageHeader from "./ToolsPageHeader.vue";
import { onWsEvent, offWsEvent } from "../../js/registries/wsEventRegistry";
import { apiPath, WS_EVENTS } from "../../js/constants";

export default {
    name: "PaperMessagePage",
    components: { MaterialDesignIcon, ToolsPageHeader },
    data() {
        return {
            destinationHash: "",
            title: "",
            content: "",
            isGenerating: false,
            generatedUri: null,
            ingestUri: "",
            isSending: false,
            isIngestScannerModalOpen: false,
            ingestScannerError: null,
            ingestScannerStream: null,
            ingestScannerAnimationFrame: null,
            generateTimeout: null,
        };
    },
    computed: {
        canGenerate() {
            return this.destinationHash.length === 32 && this.content.length > 0;
        },
        cameraSupported() {
            return isCameraSupported();
        },
    },
    mounted() {
        onWsEvent(WS_EVENTS.LXM_GENERATE_PAPER_URI_RESULT, this.onGeneratePaperUriResult);
        onWsEvent(WS_EVENTS.LXM_INGEST_URI_RESULT, this.onIngestUriResult);
    },
    beforeUnmount() {
        offWsEvent(WS_EVENTS.LXM_GENERATE_PAPER_URI_RESULT, this.onGeneratePaperUriResult);
        offWsEvent(WS_EVENTS.LXM_INGEST_URI_RESULT, this.onIngestUriResult);
        this.stopIngestScanner();
        clearTimeout(this.generateTimeout);
    },
    methods: {
        onGeneratePaperUriResult(json) {
            this.isGenerating = false;
            clearTimeout(this.generateTimeout);
            if (json.status === "success") {
                this.generatedUri = json.uri;
                this.$nextTick(() => {
                    this.renderQRCode();
                });
            } else {
                ToastUtils.error(json.message);
            }
        },
        onIngestUriResult(json) {
            if (json.status === "success") {
                this.ingestUri = "";
            }
        },
        async generatePaperMessage() {
            if (!this.canGenerate) return;

            this.isGenerating = true;
            this.generatedUri = null;

            const sent = WebSocketConnection.send(
                JSON.stringify({
                    type: "lxm.generate_paper_uri",
                    destination_hash: this.destinationHash,
                    content: this.content,
                    title: this.title,
                })
            );
            if (!sent) {
                this.isGenerating = false;
                ToastUtils.error(this.$t("messages.failed_generate_paper_uri"));
                return;
            }
            // A dropped reply must not leave the button disabled forever.
            clearTimeout(this.generateTimeout);
            this.generateTimeout = setTimeout(() => {
                this.isGenerating = false;
            }, 30000);
        },
        async renderQRCode() {
            if (!this.generatedUri || !this.$refs.qrcode) return;

            try {
                await QRCode.toCanvas(this.$refs.qrcode, this.generatedUri, {
                    width: 256,
                    margin: 2,
                    color: {
                        dark: "#000000",
                        light: "#ffffff",
                    },
                    errorCorrectionLevel: "L",
                });

                const el = this.$refs.qrcode;
                if (el) {
                    el.style.maxWidth = "100%";
                    el.style.height = "auto";
                    el.classList.add("rounded-lg");
                }
            } catch (err) {
                console.error("Failed to render QR code:", err);
                ToastUtils.error(this.$t("messages.failed_render_qr"));
            }
        },
        async ingestPaperMessage() {
            if (!this.ingestUri) return;

            WebSocketConnection.send(
                JSON.stringify({
                    type: "lxm.ingest_uri",
                    uri: this.ingestUri,
                })
            );
        },
        async pasteFromClipboard() {
            try {
                this.ingestUri = await navigator.clipboard.readText();
            } catch {
                ToastUtils.error(this.$t("messages.failed_read_clipboard"));
            }
        },
        async openIngestScannerModal() {
            this.ingestScannerError = null;
            this.isIngestScannerModalOpen = true;
            await this.$nextTick();
            await this.startIngestScanner();
        },
        closeIngestScannerModal() {
            this.isIngestScannerModalOpen = false;
            this.stopIngestScanner();
        },
        async startIngestScanner() {
            if (!this.cameraSupported) {
                this.ingestScannerError = this.$t("messages.camera_not_supported");
                return;
            }
            try {
                const stream = await startCameraStream();
                this.ingestScannerStream = stream;
                const video = this.$refs.ingestScannerVideo;
                if (!(await attachStreamToVideo(stream, video))) {
                    this.ingestScannerError = this.$t("messages.camera_failed");
                    this.stopIngestScanner();
                    return;
                }
                this.detectIngestQrLoop();
            } catch (e) {
                this.ingestScannerError = this.describeCameraError(e);
            }
        },
        detectIngestQrLoop() {
            if (!this.isIngestScannerModalOpen) return;
            const video = this.$refs.ingestScannerVideo;
            decodeQrFromVideo(video)
                .then((qr) => {
                    if (!this.isIngestScannerModalOpen) {
                        return;
                    }
                    if (!qr) {
                        this.ingestScannerAnimationFrame = requestAnimationFrame(() => this.detectIngestQrLoop());
                        return;
                    }
                    if (!/^lxm(a|f)?:\/\//i.test(qr)) {
                        ToastUtils.error(this.$t("messages.invalid_qr_uri"));
                        this.ingestScannerAnimationFrame = requestAnimationFrame(() => this.detectIngestQrLoop());
                        return;
                    }
                    this.ingestUri = qr;
                    this.closeIngestScannerModal();
                    this.ingestPaperMessage();
                })
                .catch(() => {
                    if (this.isIngestScannerModalOpen) {
                        this.ingestScannerAnimationFrame = requestAnimationFrame(() => this.detectIngestQrLoop());
                    }
                });
        },
        stopIngestScanner() {
            if (this.ingestScannerAnimationFrame) {
                cancelAnimationFrame(this.ingestScannerAnimationFrame);
                this.ingestScannerAnimationFrame = null;
            }
            if (this.ingestScannerStream) {
                this.ingestScannerStream.getTracks().forEach((track) => track.stop());
                this.ingestScannerStream = null;
            }
        },
        describeCameraError(error) {
            return describeQrCameraError(error, {
                permissionDenied: this.$t("messages.camera_permission_denied"),
                notFound: this.$t("messages.camera_not_found"),
                failed: this.$t("messages.camera_failed"),
            });
        },
        async copyUri() {
            try {
                await navigator.clipboard.writeText(this.generatedUri);
                ToastUtils.success(this.$t("messages.uri_copied"));
            } catch {
                ToastUtils.error(this.$t("messages.failed_copy_uri"));
            }
        },
        downloadQRCode() {
            const canvas = this.$refs.qrcode;
            if (!canvas) return;

            const dataUrl = canvas.toDataURL("image/png");
            if (dataUrl) {
                const link = document.createElement("a");
                link.download = `lxmf-paper-message-${Date.now()}.png`;
                link.href = dataUrl;
                link.click();
            }
        },
        async sendPaperMessage() {
            if (!this.destinationHash || !this.generatedUri) return;

            try {
                this.isSending = true;

                // build lxmf message
                const lxmf_message = {
                    destination_hash: this.destinationHash,
                    content: `Please scan the attached Paper Message or manually ingest this URI: ${this.generatedUri}`,
                    fields: {},
                };

                // get data url from canvas if available
                const canvas = this.$refs.qrcode;
                if (canvas) {
                    const dataUrl = canvas.toDataURL("image/png");
                    const imageBytes = dataUrl.split(",")[1];
                    lxmf_message.fields.image = {
                        image_type: "png",
                        image_bytes: imageBytes,
                        name: "paper_message_qr.png",
                    };
                }

                // send message
                const response = await window.api.post(apiPath("/lxmf-messages/send"), {
                    delivery_method: "opportunistic",
                    lxmf_message: lxmf_message,
                });

                if (response.data.lxmf_message) {
                    ToastUtils.success(this.$t("messages.paper_message_sent"));
                    this.generatedUri = null;
                    this.destinationHash = "";
                    this.content = "";
                    this.title = "";
                } else {
                    ToastUtils.error(response.data.message || "Failed to send paper message");
                }
            } catch (err) {
                console.error("Failed to send paper message:", err);
                ToastUtils.error(this.$t("messages.failed_send_paper"));
            } finally {
                this.isSending = false;
            }
        },
        printQRCode() {
            const canvas = this.$refs.qrcode;
            if (!canvas) return;

            const dataUrl = canvas.toDataURL("image/png");
            if (!dataUrl) return;

            const printWindow = window.open("", "_blank");
            if (!printWindow) {
                ToastUtils.error("Pop-up blocked. Please allow pop-ups to print.");
                return;
            }

            printWindow.document.write(`
                <html>
                    <head>
                        <title>LXMF Paper Message</title>
                        <style>
                            body { display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100vh; font-family: sans-serif; }
                            img { width: 400px; height: 400px; margin-bottom: 20px; }
                            .hash { font-family: monospace; font-size: 12px; color: #666; }
                            @media print { body { height: auto; padding: 20px; } }
                        </style>
                    </head>
                    <body>
                        <h1>LXMF Paper Message</h1>
                        <img src="${Utils.escapeHtml(dataUrl)}" />
                        <div class="hash">Recipient: ${Utils.escapeHtml(this.destinationHash)}</div>
                        <p>Scan this code with an LXMF-compatible app to read the message.</p>
                        <script>window.onload = () => { window.print(); window.close(); }</scr' + 'ipt>
                    </body>
                </html>
            `);
            printWindow.document.close();
        },
    },
};
</script>

<style scoped>
@reference "../../style.css";
.input-field {
    @apply bg-sem-surface-muted/80 dark:bg-sem-surface/80 border border-sem-border text-sm rounded-2xl focus:ring-2 focus:ring-sem-info focus:border-sem-info dark:focus:ring-blue-50 dark:focus:border-sem-accent block w-full p-2.5 text-sem-fg transition;
}
</style>

// meshchatx/src/frontend/features/paper-message/PaperMessagePage.svelte
<!-- SPDX-License-Identifier: 0BSD -->

<script lang="ts">
    import { onMount, tick } from "svelte";
    import ToolsPageHeader from "../../ui/svelte/ToolsPageHeader.svelte";
    import WebSocketConnection from "../../js/WebSocketConnection.js";
    import ToastUtils from "../../js/ToastUtils.js";
    import { t } from "../../js/i18n.js";
    import { onWsEvent, offWsEvent } from "../../js/registries/wsEventRegistry.js";
    import {
        attachStreamToVideo,
        decodeQrFromVideo,
        describeCameraError as describeQrCameraError,
        isCameraSupported,
        startCameraStream,
    } from "../../js/qrScannerUtils.js";
    import { canGeneratePaperMessage, isValidLxmUri, renderQrCodeToCanvas } from "./lib/paperQr.js";
    import { downloadPaperQr, printPaperQr } from "./lib/paperPrint.js";
    import { sendPaperMessageApi } from "./lib/paperSend.js";
    import type { LxmGeneratePaperUriWsResult, LxmIngestUriWsResult } from "./lib/types.js";
    import PaperComposer from "./components/PaperComposer.svelte";
    import PaperIngestSection from "./components/PaperIngestSection.svelte";
    import PaperPreviewSection from "./components/PaperPreviewSection.svelte";
    import PaperScannerModal from "./components/PaperScannerModal.svelte";

    let destinationHash = $state("");
    let title = $state("");
    let content = $state("");
    let generateTimeout: ReturnType<typeof setTimeout> | null = null;
    let isGenerating = $state(false);
    let generatedUri = $state<string | null>(null);
    let ingestUri = $state("");
    let isSending = $state(false);
    let isIngestScannerModalOpen = $state(false);
    let ingestScannerError = $state<string | null>(null);
    let qrcodeCanvas = $state<HTMLCanvasElement | undefined>();
    let scannerVideo = $state<HTMLVideoElement | undefined>();

    let scannerStream: MediaStream | null = null;
    let scannerAnimationFrame: number | null = null;

    const canGenerate = $derived(canGeneratePaperMessage(destinationHash, content));
    const cameraSupported = isCameraSupported();

    async function onGeneratePaperUriResult(json: LxmGeneratePaperUriWsResult): Promise<void> {
        isGenerating = false;
        if (generateTimeout != null) {
            clearTimeout(generateTimeout);
            generateTimeout = null;
        }
        if (json.status === "success") {
            generatedUri = json.uri || null;
            await tick();
            if (qrcodeCanvas && generatedUri) {
                await renderQrCodeToCanvas(qrcodeCanvas, generatedUri);
            }
        } else {
            ToastUtils.error(json.message || "Failed to generate paper message");
        }
    }

    function onIngestUriResult(json: LxmIngestUriWsResult): void {
        if (json.status === "success") {
            ingestUri = "";
        }
    }

    function generatePaperMessage(): void {
        if (!canGenerate) {
            return;
        }
        isGenerating = true;
        generatedUri = null;
        const sent = WebSocketConnection.send(
            JSON.stringify({
                type: "lxm.generate_paper_uri",
                destination_hash: destinationHash,
                content,
                title,
            })
        );
        if (!sent) {
            isGenerating = false;
            ToastUtils.error(t("messages.failed_generate_paper_uri"));
            return;
        }
        // A dropped reply must not leave the button disabled forever.
        if (generateTimeout != null) {
            clearTimeout(generateTimeout);
        }
        generateTimeout = setTimeout(() => {
            isGenerating = false;
        }, 30000);
    }

    function ingestPaperMessage(): void {
        if (!ingestUri) {
            return;
        }
        WebSocketConnection.send(
            JSON.stringify({
                type: "lxm.ingest_uri",
                uri: ingestUri,
            })
        );
    }

    async function pasteFromClipboard(): Promise<void> {
        try {
            ingestUri = await navigator.clipboard.readText();
        } catch {
            ToastUtils.error(t("messages.failed_read_clipboard"));
        }
    }

    async function copyUri(): Promise<void> {
        if (!generatedUri) {
            return;
        }
        try {
            await navigator.clipboard.writeText(generatedUri);
            ToastUtils.success(t("messages.uri_copied"));
        } catch {
            ToastUtils.error(t("messages.failed_copy_uri"));
        }
    }

    function printQRCode(): void {
        if (!qrcodeCanvas) {
            return;
        }
        printPaperQr({ canvas: qrcodeCanvas, destinationHash });
    }

    export function downloadQRCode(): void {
        if (!qrcodeCanvas) {
            return;
        }
        downloadPaperQr(qrcodeCanvas);
    }

    async function sendPaperMessage(): Promise<void> {
        if (!destinationHash || !generatedUri) {
            return;
        }
        isSending = true;
        try {
            const res = await sendPaperMessageApi({
                destinationHash,
                generatedUri,
                canvas: qrcodeCanvas,
            });
            if (res.success) {
                generatedUri = null;
                destinationHash = "";
                content = "";
                title = "";
            }
        } finally {
            isSending = false;
        }
    }

    function describeCameraError(error: unknown): string {
        return describeQrCameraError(error, {
            permissionDenied: t("messages.camera_permission_denied"),
            notFound: t("messages.camera_not_found"),
            failed: t("messages.camera_failed"),
        });
    }

    function stopIngestScanner(): void {
        if (scannerAnimationFrame != null) {
            cancelAnimationFrame(scannerAnimationFrame);
            scannerAnimationFrame = null;
        }
        if (scannerStream) {
            scannerStream.getTracks().forEach((track) => track.stop());
            scannerStream = null;
        }
    }

    function closeIngestScannerModal(): void {
        isIngestScannerModalOpen = false;
        stopIngestScanner();
    }

    function detectIngestQrLoop(): void {
        if (!isIngestScannerModalOpen) {
            return;
        }
        decodeQrFromVideo(scannerVideo)
            .then((qr) => {
                if (!isIngestScannerModalOpen) {
                    return;
                }
                if (!qr) {
                    scannerAnimationFrame = requestAnimationFrame(() => detectIngestQrLoop());
                    return;
                }
                if (!isValidLxmUri(qr)) {
                    ToastUtils.error(t("messages.invalid_qr_uri"));
                    scannerAnimationFrame = requestAnimationFrame(() => detectIngestQrLoop());
                    return;
                }
                ingestUri = qr;
                closeIngestScannerModal();
                ingestPaperMessage();
            })
            .catch(() => {
                if (isIngestScannerModalOpen) {
                    scannerAnimationFrame = requestAnimationFrame(() => detectIngestQrLoop());
                }
            });
    }

    async function startIngestScanner(): Promise<void> {
        if (!cameraSupported) {
            ingestScannerError = t("messages.camera_not_supported");
            return;
        }
        try {
            const stream = await startCameraStream();
            scannerStream = stream;
            if (!(await attachStreamToVideo(stream, scannerVideo))) {
                ingestScannerError = t("messages.camera_failed");
                stopIngestScanner();
                return;
            }
            detectIngestQrLoop();
        } catch (e) {
            ingestScannerError = describeCameraError(e);
        }
    }

    async function openIngestScannerModal(): Promise<void> {
        ingestScannerError = null;
        isIngestScannerModalOpen = true;
        await tick();
        await startIngestScanner();
    }

    $effect(() => {
        if (generatedUri && qrcodeCanvas) {
            void renderQrCodeToCanvas(qrcodeCanvas, generatedUri);
        }
    });

    onMount(() => {
        onWsEvent("lxm.generate_paper_uri.result", onGeneratePaperUriResult);
        onWsEvent("lxm.ingest_uri.result", onIngestUriResult);
        return () => {
            offWsEvent("lxm.generate_paper_uri.result", onGeneratePaperUriResult);
            offWsEvent("lxm.ingest_uri.result", onIngestUriResult);
            if (generateTimeout != null) clearTimeout(generateTimeout);
            stopIngestScanner();
        };
    });
</script>

<div class="flex flex-col flex-1 overflow-hidden min-w-0 bg-sem-canvas" data-testid="paper-message-page">
    <ToolsPageHeader
        icon="qrcode"
        title={t("tools.paper_message.title")}
        description={t("tools.paper_message.description")}
        accent="blue"
    />
    <div class="flex-1 overflow-y-auto w-full pb-[max(1rem,env(safe-area-inset-bottom))]">
        <div class="p-3 sm:p-4 md:p-6 max-w-5xl mx-auto w-full space-y-4 min-w-0">
            <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
                <div class="space-y-4 min-w-0">
                    <PaperComposer
                        bind:destinationHash
                        bind:title
                        bind:content
                        {isGenerating}
                        {canGenerate}
                        ongenerate={generatePaperMessage}
                    />

                    <PaperIngestSection
                        bind:ingestUri
                        {cameraSupported}
                        onpaste={pasteFromClipboard}
                        onscan={openIngestScannerModal}
                        oningest={ingestPaperMessage}
                    />
                </div>

                <div class="space-y-4 min-w-0">
                    <PaperPreviewSection
                        {generatedUri}
                        {isSending}
                        bind:qrcodeCanvas
                        oncopy={copyUri}
                        onprint={printQRCode}
                        onsend={sendPaperMessage}
                    />
                </div>
            </div>
        </div>
    </div>

    <PaperScannerModal
        open={isIngestScannerModalOpen}
        scannerError={ingestScannerError}
        bind:videoElement={scannerVideo}
        onclose={closeIngestScannerModal}
    />
</div>
