// meshchatx/src/frontend/components/messages/composer/SendMessageButton.vue
<!-- SPDX-License-Identifier: 0BSD AND MIT -->

<template>
    <div class="relative inline-flex items-stretch rounded-xl shadow-xs">
        <template v-if="compact">
            <button
                :disabled="!canSendMessage && !canOpenSendMenu"
                type="button"
                class="inline-flex items-center justify-center rounded-xl p-2.5 min-h-[44px] min-w-[44px] text-white transition-colors focus-visible:outline-solid focus-visible:outline-2 focus-visible:outline-offset-2 touch-manipulation select-none"
                :class="[
                    canSendMessage || canOpenSendMenu
                        ? 'bg-sem-action-primary hover:bg-sem-action-primary-hover focus-visible:outline-sem-focus press-feedback'
                        : 'bg-sem-fg-muted/40 focus-visible:outline-sem-fg-muted cursor-not-allowed',
                ]"
                :title="compactTitle"
                @pointerdown="onCompactPointerDown"
                @pointerup="onCompactPointerUp"
                @pointercancel="onCompactPointerCancel"
                @click="onCompactClick"
            >
                <svg
                    v-if="!isSendingMessage"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke-width="1.5"
                    stroke="currentColor"
                    class="w-5 h-5"
                >
                    <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        d="M6 12 3.269 3.125A59.769 59.769 0 0 1 21.485 12 59.768 59.768 0 0 1 3.27 20.875L5.999 12Zm0 0h7.5"
                    />
                </svg>
                <span v-else class="text-xs font-semibold opacity-90">...</span>
            </button>
        </template>
        <template v-else>
            <button
                :disabled="!canSendMessage"
                type="button"
                class="inline-flex items-center gap-2 rounded-l-xl px-4 py-2.5 text-sm font-semibold text-white transition-colors focus-visible:outline-solid focus-visible:outline-2 focus-visible:outline-offset-2"
                :class="[
                    canSendMessage
                        ? 'bg-sem-action-primary hover:bg-sem-action-primary-hover focus-visible:outline-sem-focus press-feedback'
                        : 'bg-sem-fg-muted/40 focus-visible:outline-sem-fg-muted cursor-not-allowed',
                ]"
                :title="isSendingMessage ? sendingTooltip : ''"
                @click="send"
            >
                <svg
                    v-if="!isSendingMessage"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke-width="1.5"
                    stroke="currentColor"
                    class="w-4 h-4"
                >
                    <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        d="M6 12 3.269 3.125A59.769 59.769 0 0 1 21.485 12 59.768 59.768 0 0 1 3.27 20.875L5.999 12Zm0 0h7.5"
                    />
                </svg>
                <span :class="isSendingMessage ? 'opacity-60' : ''">
                    <span v-if="deliveryMethod === 'direct'">{{ $t("messages.send_direct") }}</span>
                    <span v-else-if="deliveryMethod === 'opportunistic'">{{ $t("messages.send_opportunistic") }}</span>
                    <span v-else-if="deliveryMethod === 'propagated'">{{ $t("messages.send_propagated") }}</span>
                    <span v-else>{{ $t("messages.send") }}</span>
                </span>
            </button>
            <div class="relative self-stretch">
                <button
                    :disabled="!canSendMessage && !canOpenSendMenu"
                    type="button"
                    class="border-l relative inline-flex items-center justify-center rounded-r-xl px-2.5 h-full text-white transition-colors focus-visible:outline-solid focus-visible:outline-2 focus-visible:outline-offset-2"
                    :class="[
                        canSendMessage || canOpenSendMenu
                            ? 'bg-sem-action-primary hover:bg-sem-action-primary-hover focus-visible:outline-sem-focus border-sem-action-primary-hover press-feedback'
                            : 'bg-sem-fg-muted/40 focus-visible:outline-sem-fg-muted border-sem-border cursor-not-allowed',
                    ]"
                    @click="showMenu"
                >
                    <svg class="h-4 w-4" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path
                            fill-rule="evenodd"
                            d="M5.22 8.22a.75.75 0 0 1 1.06 0L10 11.94l3.72-3.72a.75.75 0 1 1 1.06 1.06l-4.25 4.25a.75.75 0 0 1-1.06 0L5.22 9.28a.75.75 0 0 1 0-1.06Z"
                            clip-rule="evenodd"
                        />
                    </svg>
                </button>
            </div>
        </template>

        <Transition
            enter-active-class="transition ease-out duration-100"
            enter-from-class="transform opacity-0 scale-95"
            enter-to-class="transform opacity-100 scale-100"
            leave-active-class="transition ease-in duration-75"
            leave-from-class="transform opacity-100 scale-100"
            leave-to-class="transform opacity-0 scale-95"
        >
            <div
                v-if="isShowingMenu"
                v-click-outside="hideMenu"
                class="absolute bottom-full right-0 mb-1 z-10 focus:outline-hidden"
            >
                <div
                    class="dropdown-caret pointer-events-none absolute -bottom-[4px] right-4 border-b border-r border-sem-border"
                    aria-hidden="true"
                ></div>
                <div class="rounded-xl bg-sem-surface shadow-lg ring-1 ring-sem-border overflow-hidden min-w-[200px]">
                    <div class="py-1">
                        <button
                            type="button"
                            class="w-full block text-left px-4 py-2 text-sm text-sem-fg hover:bg-sem-surface-muted whitespace-nowrap border-b border-sem-border"
                            @click="setDeliveryMethod(null)"
                        >
                            {{ $t("messages.send_automatically") }}
                        </button>
                        <button
                            type="button"
                            class="w-full block text-left px-4 py-2 text-sm text-sem-fg hover:bg-sem-surface-muted whitespace-nowrap"
                            @click="setDeliveryMethod('direct')"
                        >
                            {{ $t("messages.send_over_direct_link") }}
                        </button>
                        <button
                            type="button"
                            class="w-full block text-left px-4 py-2 text-sm text-sem-fg hover:bg-sem-surface-muted whitespace-nowrap"
                            @click="setDeliveryMethod('opportunistic')"
                        >
                            {{ $t("messages.send_opportunistically") }}
                        </button>
                        <button
                            type="button"
                            class="w-full block text-left px-4 py-2 text-sm text-sem-fg hover:bg-sem-surface-muted whitespace-nowrap"
                            @click="setDeliveryMethod('propagated')"
                        >
                            {{ $t("messages.send_to_propagation_node") }}
                        </button>
                        <div
                            class="border-t border-sem-border text-[11px] font-medium text-sem-fg-muted px-4 pt-2 pb-1"
                        >
                            {{ $t("messages.send_menu_more_label") }}
                        </div>
                        <button
                            type="button"
                            class="w-full block text-left px-4 py-2 text-sm text-sem-fg hover:bg-sem-surface-muted whitespace-nowrap"
                            :disabled="!canOpenSendMenu"
                            @click="emitCommandOrRequest"
                        >
                            {{ $t("messages.send_menu_telemetry_request") }}
                        </button>
                        <button
                            type="button"
                            class="w-full block text-left px-4 py-2 text-sm text-sem-fg hover:bg-sem-surface-muted whitespace-nowrap"
                            :disabled="!canGeneratePaper"
                            @click="emitPaperCompose"
                        >
                            {{ $t("messages.send_menu_paper_compose") }}
                        </button>
                    </div>
                </div>
            </div>
        </Transition>
    </div>
</template>

<script>
export default {
    name: "SendMessageButton",
    props: {
        deliveryMethod: {
            required: true,
            validator: (value) => value === null || typeof value === "string",
        },
        canSendMessage: Boolean,
        isSendingMessage: Boolean,
        compact: Boolean,
        sendingTooltip: {
            type: String,
            default:
                "Resolving route to peer (finding path). This can take a while on first contact or after links change. Paths are remembered until they expire.",
        },
        canOpenSendMenu: {
            type: Boolean,
            default: false,
        },
        canGeneratePaper: {
            type: Boolean,
            default: false,
        },
    },
    emits: ["delivery-method-changed", "send", "send-command-or-request", "send-paper-compose"],
    data() {
        return {
            isShowingMenu: false,
            compactLongPressTimer: null,
            compactTapArmed: false,
        };
    },
    computed: {
        compactTitle() {
            if (this.isSendingMessage) {
                return this.sendingTooltip;
            }
            return this.$t("messages.send_hold_for_options");
        },
    },
    beforeUnmount() {
        this.clearCompactLongPressTimer();
    },
    methods: {
        clearCompactLongPressTimer() {
            if (this.compactLongPressTimer != null) {
                clearTimeout(this.compactLongPressTimer);
                this.compactLongPressTimer = null;
            }
        },
        onCompactPointerDown() {
            if (!this.compact || (!this.canSendMessage && !this.canOpenSendMenu)) {
                return;
            }
            this.compactTapArmed = true;
            this.clearCompactLongPressTimer();
            this.compactLongPressTimer = window.setTimeout(() => {
                this.compactLongPressTimer = null;
                this.compactTapArmed = false;
                this.showMenu();
            }, 500);
        },
        onCompactPointerUp() {
            if (!this.compact) {
                return;
            }
            this.clearCompactLongPressTimer();
        },
        onCompactPointerCancel() {
            if (!this.compact) {
                return;
            }
            this.clearCompactLongPressTimer();
            this.compactTapArmed = false;
        },
        onCompactClick() {
            if (!this.compact) {
                return;
            }
            if (!this.compactTapArmed) {
                return;
            }
            this.compactTapArmed = false;
            this.send();
        },
        showMenu() {
            this.isShowingMenu = true;
        },
        hideMenu() {
            this.isShowingMenu = false;
        },
        setDeliveryMethod(deliveryMethod) {
            this.$emit("delivery-method-changed", deliveryMethod);
            this.hideMenu();
        },
        emitCommandOrRequest() {
            this.$emit("send-command-or-request");
            this.hideMenu();
        },
        emitPaperCompose() {
            this.$emit("send-paper-compose");
            this.hideMenu();
        },
        send() {
            this.$emit("send");
        },
    },
};
</script>

// meshchatx/src/frontend/features/messages/components/composer/SendMessageButton.svelte
<!-- SPDX-License-Identifier: 0BSD -->

<script lang="ts">
    import { onClickOutside } from "runed";
    import MaterialDesignIcon from "../../../../ui/svelte/MaterialDesignIcon.svelte";
    import { t } from "../../../../js/i18n.js";

    let {
        deliveryMethod = null as string | null,
        canSendMessage = false,
        isSendingMessage = false,
        compact = false,
        sendingTooltip = "Resolving route to peer (finding path). This can take a while on first contact or after links change. Paths are remembered until they expire.",
        canOpenSendMenu = false,
        canGeneratePaper = false,
        onsend,
        ondeliverymethodchanged,
        onsendcommandorrequest,
        onsendpapercompose,
    }: {
        deliveryMethod?: string | null;
        canSendMessage?: boolean;
        isSendingMessage?: boolean;
        compact?: boolean;
        sendingTooltip?: string;
        canOpenSendMenu?: boolean;
        canGeneratePaper?: boolean;
        onsend?: () => void;
        ondeliverymethodchanged?: (method: string | null) => void;
        onsendcommandorrequest?: () => void;
        onsendpapercompose?: () => void;
    } = $props();

    let isShowingMenu = $state(false);
    let compactLongPressTimer: number | null = $state(null);
    let compactTapArmed = $state(false);
    let rootEl: HTMLDivElement | undefined = $state();

    const compactTitle = $derived(isSendingMessage ? sendingTooltip : t("messages.send_hold_for_options"));

    function clearCompactLongPressTimer() {
        if (compactLongPressTimer != null) {
            clearTimeout(compactLongPressTimer);
            compactLongPressTimer = null;
        }
    }

    function onCompactPointerDown() {
        if (!compact || (!canSendMessage && !canOpenSendMenu)) return;
        compactTapArmed = true;
        clearCompactLongPressTimer();
        compactLongPressTimer = window.setTimeout(() => {
            compactLongPressTimer = null;
            compactTapArmed = false;
            isShowingMenu = true;
        }, 500);
    }

    function onCompactPointerUp() {
        if (!compact) return;
        clearCompactLongPressTimer();
    }

    function onCompactPointerCancel() {
        if (!compact) return;
        clearCompactLongPressTimer();
        compactTapArmed = false;
    }

    function onCompactClick() {
        if (!compact || !compactTapArmed) return;
        compactTapArmed = false;
        onsend?.();
    }

    function setDeliveryMethod(method: string | null) {
        ondeliverymethodchanged?.(method);
        isShowingMenu = false;
    }

    function toggleSendMenu() {
        if (!canSendMessage && !canOpenSendMenu) return;
        isShowingMenu = !isShowingMenu;
    }

    onClickOutside(
        () => rootEl,
        () => {
            isShowingMenu = false;
        }
    );

    $effect(() => {
        return () => clearCompactLongPressTimer();
    });
</script>

<div bind:this={rootEl} class="relative inline-flex items-stretch rounded-xl shadow-xs">
    {#if compact}
        <button
            disabled={!canSendMessage && !canOpenSendMenu}
            type="button"
            class="inline-flex items-center justify-center rounded-xl p-2.5 min-h-[44px] min-w-[44px] text-white transition-colors focus-visible:outline-solid focus-visible:outline-2 focus-visible:outline-offset-2 touch-manipulation select-none {canSendMessage ||
            canOpenSendMenu
                ? 'bg-sem-action-primary hover:bg-sem-action-primary-hover focus-visible:outline-sem-focus press-feedback'
                : 'bg-sem-fg-muted/40 focus-visible:outline-sem-fg-muted cursor-not-allowed'}"
            title={compactTitle}
            onpointerdown={onCompactPointerDown}
            onpointerup={onCompactPointerUp}
            onpointercancel={onCompactPointerCancel}
            onclick={onCompactClick}
        >
            {#if !isSendingMessage}
                <MaterialDesignIcon iconName="send" class="w-5 h-5" />
            {:else}
                <span class="text-xs font-semibold opacity-90">...</span>
            {/if}
        </button>
    {:else}
        <button
            disabled={!canSendMessage}
            type="button"
            class="inline-flex items-center gap-2 rounded-l-xl px-4 py-2.5 text-sm font-semibold text-white transition-colors focus-visible:outline-solid focus-visible:outline-2 focus-visible:outline-offset-2 {canSendMessage
                ? 'bg-sem-action-primary hover:bg-sem-action-primary-hover focus-visible:outline-sem-focus press-feedback'
                : 'bg-sem-fg-muted/40 focus-visible:outline-sem-fg-muted cursor-not-allowed'}"
            title={isSendingMessage ? sendingTooltip : ""}
            onclick={() => onsend?.()}
        >
            {#if !isSendingMessage}
                <MaterialDesignIcon iconName="send" class="w-4 h-4" />
            {/if}
            <span class={isSendingMessage ? "opacity-60" : ""}>
                {#if deliveryMethod === "direct"}
                    {t("messages.send_direct")}
                {:else if deliveryMethod === "opportunistic"}
                    {t("messages.send_opportunistic")}
                {:else if deliveryMethod === "propagated"}
                    {t("messages.send_propagated")}
                {:else}
                    {t("messages.send")}
                {/if}
            </span>
        </button>
        <div class="relative self-stretch">
            <button
                disabled={!canSendMessage && !canOpenSendMenu}
                type="button"
                class="border-l relative inline-flex items-center justify-center rounded-r-xl px-2.5 h-full text-white transition-colors focus-visible:outline-solid focus-visible:outline-2 focus-visible:outline-offset-2 {canSendMessage ||
                canOpenSendMenu
                    ? 'bg-sem-action-primary hover:bg-sem-action-primary-hover focus-visible:outline-sem-focus border-sem-action-primary-hover press-feedback'
                    : 'bg-sem-fg-muted/40 focus-visible:outline-sem-fg-muted border-sem-border cursor-not-allowed'}"
                aria-label={t("messages.send_hold_for_options")}
                aria-expanded={isShowingMenu}
                title={t("messages.send_hold_for_options")}
                onclick={toggleSendMenu}
            >
                <MaterialDesignIcon
                    iconName="chevron-down"
                    class="h-4 w-4 transition-transform {isShowingMenu ? 'rotate-180' : ''}"
                />
            </button>
        </div>
    {/if}

    {#if isShowingMenu}
        <div class="absolute bottom-full right-0 mb-1 z-10 focus:outline-hidden">
            <div
                class="dropdown-caret pointer-events-none absolute -bottom-[4px] right-4 border-b border-r border-sem-border"
                aria-hidden="true"
            ></div>
            <div
                class="rounded-xl bg-sem-surface shadow-lg ring-1 ring-sem-border focus:outline-hidden overflow-hidden min-w-[220px]"
            >
                <div class="py-1">
                    <button
                        type="button"
                        class="w-full flex items-center gap-2 px-4 py-2 text-sm text-sem-fg hover:bg-sem-surface-muted whitespace-nowrap border-b border-sem-border"
                        onclick={() => setDeliveryMethod(null)}
                    >
                        <MaterialDesignIcon iconName="auto-fix" class="size-5 shrink-0 text-sem-fg-muted" />
                        <span>{t("messages.send_automatically")}</span>
                    </button>
                    <button
                        type="button"
                        class="w-full flex items-center gap-2 px-4 py-2 text-sm text-sem-fg hover:bg-sem-surface-muted whitespace-nowrap"
                        onclick={() => setDeliveryMethod("direct")}
                    >
                        <MaterialDesignIcon
                            iconName="transit-connection-variant"
                            class="size-5 shrink-0 text-sem-fg-muted"
                        />
                        <span>{t("messages.send_over_direct_link")}</span>
                    </button>
                    <button
                        type="button"
                        class="w-full flex items-center gap-2 px-4 py-2 text-sm text-sem-fg hover:bg-sem-surface-muted whitespace-nowrap"
                        onclick={() => setDeliveryMethod("opportunistic")}
                    >
                        <MaterialDesignIcon iconName="swap-horizontal" class="size-5 shrink-0 text-sem-fg-muted" />
                        <span>{t("messages.send_opportunistically")}</span>
                    </button>
                    <button
                        type="button"
                        class="w-full flex items-center gap-2 px-4 py-2 text-sm text-sem-fg hover:bg-sem-surface-muted whitespace-nowrap"
                        onclick={() => setDeliveryMethod("propagated")}
                    >
                        <MaterialDesignIcon iconName="access-point-network" class="size-5 shrink-0 text-sem-fg-muted" />
                        <span>{t("messages.send_to_propagation_node")}</span>
                    </button>
                    <div class="border-t border-sem-border text-[11px] font-medium text-sem-fg-muted px-4 pt-2 pb-1">
                        {t("messages.send_menu_more_label")}
                    </div>
                    <button
                        type="button"
                        class="w-full flex items-center gap-2 px-4 py-2 text-sm text-sem-fg hover:bg-sem-surface-muted whitespace-nowrap disabled:opacity-50"
                        disabled={!canOpenSendMenu}
                        onclick={() => {
                            onsendcommandorrequest?.();
                            isShowingMenu = false;
                        }}
                    >
                        <MaterialDesignIcon iconName="code-tags" class="size-5 shrink-0 text-sem-fg-muted" />
                        <span>{t("messages.send_menu_telemetry_request")}</span>
                    </button>
                    <button
                        type="button"
                        class="w-full flex items-center gap-2 px-4 py-2 text-sm text-sem-fg hover:bg-sem-surface-muted whitespace-nowrap disabled:opacity-50"
                        disabled={!canGeneratePaper}
                        onclick={() => {
                            onsendpapercompose?.();
                            isShowingMenu = false;
                        }}
                    >
                        <MaterialDesignIcon iconName="qrcode" class="size-5 shrink-0 text-sem-fg-muted" />
                        <span>{t("messages.send_menu_paper_compose")}</span>
                    </button>
                </div>
            </div>
        </div>
    {/if}
</div>
