// meshchatx/src/frontend/components/ColourPickerDropdown.vue
<!-- SPDX-License-Identifier: 0BSD -->

<template>
    <div
        v-click-outside="{ handler: onClickOutsideMenu, capture: true }"
        class="cursor-default relative inline-block text-left"
    >
        <!-- menu button -->
        <div ref="dropdown-button" @click.stop="toggleMenu">
            <slot>
                <div
                    class="size-8 border border-gray-300 dark:border-zinc-700 rounded-sm shadow-sm cursor-pointer"
                    :style="{ 'background-color': colour }"
                ></div>
            </slot>
        </div>

        <!-- drop down menu -->
        <Transition
            enter-active-class="transition ease-out duration-100"
            enter-from-class="transform opacity-0 scale-95"
            enter-to-class="transform opacity-100 scale-100"
            leave-active-class="transition ease-in duration-75"
            leave-from-class="transform opacity-100 scale-100"
            leave-to-class="transform opacity-0 scale-95"
        >
            <div
                v-if="isShowingMenu"
                class="absolute left-0 z-100 mt-2 rounded-xl border border-gray-200 bg-white p-3 shadow-xl dark:border-zinc-700 dark:bg-zinc-900"
            >
                <input
                    :value="normalizedColour"
                    type="color"
                    class="block h-10 w-full cursor-pointer rounded-lg border border-gray-200 bg-transparent p-0 dark:border-zinc-700"
                    @input="onNativeColorInput"
                />
                <div class="mt-2 grid grid-cols-6 gap-1.5">
                    <button
                        v-for="swatch in swatches"
                        :key="swatch"
                        type="button"
                        class="size-6 rounded-md border border-sem-border"
                        :style="{ backgroundColor: swatch }"
                        :title="swatch"
                        @click="selectSwatch(swatch)"
                    ></button>
                </div>
            </div>
        </Transition>
    </div>
</template>

<script>
const DEFAULT_SWATCHES = [
    "#ef4444",
    "#f97316",
    "#eab308",
    "#22c55e",
    "#3b82f6",
    "#8b5cf6",
    "#ec4899",
    "#64748b",
    "#ffffff",
    "#18181b",
    "#0ea5e9",
    "#14b8a6",
];

export default {
    name: "ColourPickerDropdown",
    props: {
        colour: {
            type: String,
            default: "",
        },
    },
    emits: ["update:colour"],
    data() {
        return {
            isShowingMenu: false,
            swatches: DEFAULT_SWATCHES,
        };
    },
    computed: {
        normalizedColour() {
            return normalizeHexColour(this.colour) || "#3b82f6";
        },
    },
    methods: {
        toggleMenu() {
            if (this.isShowingMenu) {
                this.hideMenu();
            } else {
                this.showMenu();
            }
        },
        showMenu() {
            this.isShowingMenu = true;
        },
        hideMenu() {
            this.isShowingMenu = false;
        },
        onClickOutsideMenu(event) {
            if (this.isShowingMenu) {
                event.preventDefault();
                this.hideMenu();
            }
        },
        onNativeColorInput(event) {
            const value = event?.target?.value;
            if (typeof value === "string" && value) {
                this.$emit("update:colour", normalizeHexColour(value));
            }
        },
        selectSwatch(value) {
            this.$emit("update:colour", normalizeHexColour(value));
        },
    },
};

function normalizeHexColour(value) {
    if (typeof value !== "string") {
        return "";
    }
    let hex = value.trim();
    if (hex.length === 9) {
        hex = hex.substring(0, 7);
    }
    if (/^#[0-9a-fA-F]{6}$/.test(hex)) {
        return hex.toLowerCase();
    }
    return "";
}
</script>

// meshchatx/src/frontend/features/profile/components/ColourPickerDropdown.svelte
<!-- SPDX-License-Identifier: 0BSD -->

<script lang="ts">
    import { onClickOutside } from "runed";
    import { DEFAULT_COLOR_SWATCHES, normalizeHexColour } from "../lib/profileIcon.js";

    interface Props {
        colour?: string;
        onchange?: (colour: string) => void;
    }

    let { colour = $bindable(""), onchange }: Props = $props();

    let isShowingMenu = $state(false);
    let rootEl: HTMLDivElement | null = $state(null);

    const normalizedColour = $derived(normalizeHexColour(colour) || "#3b82f6");

    function toggleMenu(): void {
        isShowingMenu = !isShowingMenu;
    }

    function onNativeColorInput(event: Event): void {
        const target = event.target as HTMLInputElement | null;
        const val = target?.value;
        if (typeof val === "string" && val) {
            const hex = normalizeHexColour(val);
            colour = hex;
            onchange?.(hex);
        }
    }

    function selectSwatch(swatch: string): void {
        const hex = normalizeHexColour(swatch);
        colour = hex;
        onchange?.(hex);
        isShowingMenu = false;
    }

    onClickOutside(
        () => rootEl,
        () => {
            isShowingMenu = false;
        }
    );
</script>

<div bind:this={rootEl} class="cursor-default relative inline-block text-left">
    <!-- Menu button trigger -->
    <button
        type="button"
        class="block p-0 border-0 bg-transparent cursor-pointer rounded-sm focus-ring-sem"
        onclick={toggleMenu}
        aria-label="Pick color"
        aria-expanded={isShowingMenu}
    >
        <div
            class="size-8 border border-gray-300 dark:border-zinc-700 rounded-sm shadow-xs"
            style="background-color: {colour};"
        ></div>
    </button>

    {#if isShowingMenu}
        <div
            class="absolute left-0 z-100 mt-2 rounded-xl border border-gray-200 bg-white p-3 shadow-xl dark:border-zinc-700 dark:bg-zinc-900"
        >
            <input
                value={normalizedColour}
                type="color"
                class="block h-10 w-full cursor-pointer rounded-lg border border-gray-200 bg-transparent p-0 dark:border-zinc-700"
                oninput={onNativeColorInput}
            />
            <div class="mt-2 grid grid-cols-6 gap-1.5">
                {#each DEFAULT_COLOR_SWATCHES as swatch (swatch)}
                    <button
                        type="button"
                        class="size-6 rounded-md border border-sem-border hover:scale-105 transition-transform"
                        style="background-color: {swatch};"
                        title={swatch}
                        aria-label={swatch}
                        onclick={() => selectSwatch(swatch)}
                    ></button>
                {/each}
            </div>
        </div>
    {/if}
</div>
