// meshchatx/src/frontend/features/settings/components/sections/StrangerProtectionSettingsSection.svelte
<!-- SPDX-License-Identifier: 0BSD -->

<script lang="ts">
    import SettingsSectionBlock from "../SettingsSectionBlock.svelte";
    import SettingToggleRow from "../SettingToggleRow.svelte";
    import { t } from "../../../../js/i18n.js";

    interface Props {
        visible?: boolean;
        config?: Record<string, any>;
        onblockattachmentschange?: (val: boolean) => void;
        onblockallchange?: (val: boolean) => void;
        onunknownbannerchange?: (val: boolean) => void;
        onwarnlinkschange?: (val: boolean) => void;
    }

    let {
        visible = true,
        config = {},
        onblockattachmentschange,
        onblockallchange,
        onunknownbannerchange,
        onwarnlinkschange,
    }: Props = $props();
</script>

<SettingsSectionBlock
    show={visible}
    eyebrow="Security"
    title={t("app.stranger_protection")}
    description={t("app.stranger_protection_description")}
    bodyClass="space-y-4"
>
    <SettingToggleRow
        id="block-attachments-from-strangers"
        checked={Boolean(config.block_attachments_from_strangers)}
        title={t("app.block_stranger_attachments")}
        description={t("app.block_stranger_attachments_description")}
        onchange={onblockattachmentschange}
    />
    <SettingToggleRow
        id="block-all-from-strangers"
        checked={Boolean(config.block_all_from_strangers)}
        title={t("app.block_all_from_strangers")}
        description={t("app.block_all_from_strangers_description")}
        onchange={onblockallchange}
    />
    <SettingToggleRow
        id="show-unknown-contact-banner"
        checked={Boolean(config.show_unknown_contact_banner)}
        title={t("app.show_unknown_contact_banner")}
        description={t("app.show_unknown_contact_banner_description")}
        onchange={onunknownbannerchange}
    />
    <SettingToggleRow
        id="warn-on-stranger-links"
        checked={Boolean(config.warn_on_stranger_links)}
        title={t("app.warn_on_stranger_links")}
        description={t("app.warn_on_stranger_links_description")}
        onchange={onwarnlinkschange}
    />
</SettingsSectionBlock>

// meshchatx/src/frontend/components/settings/sections/StrangerProtectionSettingsSection.vue
<!-- SPDX-License-Identifier: 0BSD -->

<template>
    <SettingsSectionBlock
        v-show="visible"
        eyebrow="Security"
        :title="$t('app.stranger_protection')"
        :description="$t('app.stranger_protection_description')"
        body-class="space-y-4"
    >
        <SettingToggleRow
            id="block-attachments-from-strangers"
            :model-value="config.block_attachments_from_strangers"
            :title="$t('app.block_stranger_attachments')"
            :description="$t('app.block_stranger_attachments_description')"
            @update:model-value="$emit('block-attachments-change', $event)"
        />
        <SettingToggleRow
            id="block-all-from-strangers"
            :model-value="config.block_all_from_strangers"
            :title="$t('app.block_all_from_strangers')"
            :description="$t('app.block_all_from_strangers_description')"
            @update:model-value="$emit('block-all-change', $event)"
        />
        <SettingToggleRow
            id="show-unknown-contact-banner"
            :model-value="config.show_unknown_contact_banner"
            :title="$t('app.show_unknown_contact_banner')"
            :description="$t('app.show_unknown_contact_banner_description')"
            @update:model-value="$emit('unknown-banner-change', $event)"
        />
        <SettingToggleRow
            id="warn-on-stranger-links"
            :model-value="config.warn_on_stranger_links"
            :title="$t('app.warn_on_stranger_links')"
            :description="$t('app.warn_on_stranger_links_description')"
            @update:model-value="$emit('warn-links-change', $event)"
        />
    </SettingsSectionBlock>
</template>

<script>
import SettingsSectionBlock from "../SettingsSectionBlock.vue";
import SettingToggleRow from "../SettingToggleRow.vue";

export default {
    name: "StrangerProtectionSettingsSection",
    components: {
        SettingsSectionBlock,
        SettingToggleRow,
    },
    props: {
        visible: {
            type: Boolean,
            default: true,
        },
        config: {
            type: Object,
            required: true,
        },
    },
    emits: ["block-attachments-change", "block-all-change", "unknown-banner-change", "warn-links-change"],
};
</script>
