// meshchatx/src/frontend/components/settings/SettingsNav.vue
<!-- SPDX-License-Identifier: 0BSD -->

<template>
    <nav class="settings-nav" :aria-label="$t('settings.nav_label')">
        <button
            v-for="tab in tabs"
            :key="tab.id"
            type="button"
            class="settings-nav__tab"
            :class="{
                'settings-nav__tab--active': tab.id === activeTab,
                'settings-nav__tab--empty': isSearchEmpty(tab.id),
            }"
            :aria-current="tab.id === activeTab ? 'page' : undefined"
            :disabled="isSearchEmpty(tab.id)"
            @click="onTabClick(tab.id)"
        >
            <span class="settings-nav__label-row">
                <span class="settings-nav__label">{{ $t(tab.labelKey) }}</span>
                <span v-if="searchActive" class="settings-nav__count">{{ matchCount(tab.id) }}</span>
            </span>
            <span class="settings-nav__description">{{ $t(tab.descriptionKey) }}</span>
        </button>
    </nav>
</template>

<script>
import { SETTINGS_TABS } from "../../js/settings/settingsTabs.js";

export default {
    name: "SettingsNav",
    props: {
        activeTab: {
            type: String,
            required: true,
        },
        matchCounts: {
            type: Object,
            default: null,
        },
    },
    emits: ["select"],
    data() {
        return {
            tabs: SETTINGS_TABS,
        };
    },
    computed: {
        searchActive() {
            return this.matchCounts != null;
        },
    },
    methods: {
        matchCount(tabId) {
            if (!this.matchCounts) return 0;
            const n = this.matchCounts[tabId];
            return typeof n === "number" && n > 0 ? n : 0;
        },
        isSearchEmpty(tabId) {
            return this.searchActive && this.matchCount(tabId) === 0;
        },
        onTabClick(tabId) {
            if (this.isSearchEmpty(tabId)) return;
            this.$emit("select", tabId);
        },
    },
};
</script>

<style scoped>
@reference "../../style.css";

.settings-nav {
    @apply flex gap-1 overflow-x-auto pb-1 lg:flex-col lg:overflow-x-visible lg:pb-0 lg:gap-0.5 lg:w-52 lg:shrink-0 lg:sticky lg:top-20 lg:self-start;
}

.settings-nav__tab {
    @apply flex flex-col items-start gap-0.5 rounded-xl border border-transparent px-3 py-2.5 text-left transition-colors shrink-0 lg:w-full;
    @apply text-sem-fg-muted hover:bg-sem-surface-muted;
}

.settings-nav__tab--active {
    @apply border-sem-border bg-sem-surface text-sem-fg shadow-xs;
}

.settings-nav__tab--empty {
    @apply opacity-40 pointer-events-none;
}

.settings-nav__label-row {
    @apply flex items-center gap-2 w-full min-w-0;
}

.settings-nav__label {
    @apply text-sm font-semibold leading-tight min-w-0 truncate;
}

.settings-nav__count {
    @apply ml-auto text-[10px] font-semibold tabular-nums rounded-md px-1.5 py-0.5 bg-sem-surface-muted text-sem-fg-muted;
}

.settings-nav__description {
    @apply hidden text-xs text-sem-fg-muted lg:block;
}
</style>

// meshchatx/src/frontend/features/settings/components/SettingsNav.svelte
<!-- SPDX-License-Identifier: 0BSD -->

<script lang="ts">
    import { SETTINGS_TABS } from "../../../js/settings/settingsTabs.js";
    import { t } from "../../../js/i18n.js";

    interface Props {
        activeTab: string;
        matchCounts?: Record<string, number> | null;
        isSearching?: boolean;
        onselect?: (tabId: string) => void;
        onselecttab?: (tabId: string) => void;
    }

    let { activeTab, matchCounts = null, isSearching = false, onselect, onselecttab }: Props = $props();

    const tabs = SETTINGS_TABS;
    const searchActive = $derived(matchCounts != null || isSearching);

    function matchCount(tabId: string): number {
        if (matchCounts) {
            const n = matchCounts[tabId];
            return typeof n === "number" && n > 0 ? n : 0;
        }
        return 0;
    }

    function isSearchEmpty(tabId: string): boolean {
        return searchActive && matchCount(tabId) === 0 && matchCounts != null;
    }

    function onTabClick(tabId: string) {
        if (isSearchEmpty(tabId)) return;
        onselect?.(tabId);
        onselecttab?.(tabId);
    }
</script>

<nav
    class="settings-nav flex gap-1 overflow-x-auto pb-1 lg:flex-col lg:overflow-x-visible lg:pb-0 lg:gap-0.5 lg:w-52 lg:shrink-0 lg:sticky lg:top-20 lg:self-start"
    aria-label={t("settings.nav_label")}
>
    {#each tabs as tab (tab.id)}
        <button
            type="button"
            class="settings-nav__tab flex flex-col items-start gap-0.5 rounded-xl border border-transparent px-3 py-2.5 text-left transition-colors shrink-0 lg:w-full text-sem-fg-muted hover:bg-sem-surface-muted {tab.id ===
            activeTab
                ? 'border-sem-border bg-sem-surface text-sem-fg shadow-xs'
                : ''} {isSearchEmpty(tab.id) ? 'opacity-40 pointer-events-none' : ''}"
            aria-current={tab.id === activeTab ? "page" : undefined}
            disabled={isSearchEmpty(tab.id)}
            onclick={() => onTabClick(tab.id)}
        >
            <span class="flex items-center gap-2 w-full min-w-0">
                <span class="text-sm font-semibold leading-tight min-w-0 truncate">{t(tab.labelKey)}</span>
                {#if searchActive}
                    <span
                        class="ml-auto text-[10px] font-semibold tabular-nums rounded-md px-1.5 py-0.5 bg-sem-surface-muted text-sem-fg-muted"
                    >
                        {matchCount(tab.id)}
                    </span>
                {/if}
            </span>
            <span class="hidden text-xs text-sem-fg-muted lg:block">{t(tab.descriptionKey)}</span>
        </button>
    {/each}
</nav>
