// meshchatx/src/frontend/components/settings/SettingToggleRow.vue
<!-- SPDX-License-Identifier: 0BSD -->

<template>
    <label class="setting-toggle" :class="{ 'opacity-50 cursor-not-allowed': disabled }">
        <Toggle
            :id="id"
            :model-value="modelValue"
            :disabled="disabled"
            @update:model-value="$emit('update:modelValue', $event)"
        />
        <span class="setting-toggle__label">
            <span class="setting-toggle__title">{{ title }}</span>
            <span v-if="description" class="setting-toggle__description">
                <slot name="description">{{ description }}</slot>
            </span>
            <span v-if="hint" class="setting-toggle__hint">{{ hint }}</span>
        </span>
    </label>
</template>

<script>
import Toggle from "../forms/Toggle.vue";

export default {
    name: "SettingToggleRow",
    components: {
        Toggle,
    },
    props: {
        id: {
            type: String,
            required: true,
        },
        modelValue: {
            type: Boolean,
            default: false,
        },
        title: {
            type: String,
            required: true,
        },
        description: {
            type: String,
            default: "",
        },
        hint: {
            type: String,
            default: "",
        },
        disabled: {
            type: Boolean,
            default: false,
        },
    },
    emits: ["update:modelValue"],
};
</script>

<style scoped>
@reference "../../style.css";
.setting-toggle {
    @apply relative flex flex-row-reverse items-start gap-3 rounded-2xl border border-sem-border bg-sem-surface px-3 py-3;
}
.setting-toggle > :deep(label) {
    @apply shrink-0 self-center;
}
.setting-toggle :deep(.sr-only) {
    @apply absolute w-px h-px p-0 -m-px overflow-hidden whitespace-nowrap border-0;
}
.setting-toggle__label {
    @apply flex-1 min-w-0 flex flex-col gap-0.5;
}
.setting-toggle__title {
    @apply text-sm font-semibold text-sem-fg wrap-break-word leading-snug;
}
.setting-toggle__description {
    @apply text-xs sm:text-sm text-sem-fg-muted wrap-break-word leading-snug;
}
.setting-toggle__hint {
    @apply text-xs text-sem-fg-muted wrap-break-word;
}
</style>

// meshchatx/src/frontend/features/settings/components/SettingToggleRow.svelte
<!-- SPDX-License-Identifier: 0BSD -->

<script lang="ts">
    import type { Snippet } from "svelte";
    import Toggle from "../../../ui/svelte/Toggle.svelte";

    interface Props {
        id: string;
        checked?: boolean;
        title: string;
        description?: string;
        hint?: string;
        disabled?: boolean;
        onchange?: (checked: boolean) => void;
        children?: Snippet;
    }

    let {
        id,
        checked = $bindable(false),
        title,
        description = "",
        hint = "",
        disabled = false,
        onchange,
        children,
    }: Props = $props();

    function handleToggleChange(val: boolean) {
        checked = val;
        onchange?.(val);
    }
</script>

<label
    class="setting-toggle relative flex flex-row-reverse items-start gap-3 rounded-2xl border border-sem-border bg-sem-surface px-3 py-3 {disabled
        ? 'opacity-50 cursor-not-allowed'
        : ''}"
>
    <Toggle {id} {checked} {disabled} onchange={handleToggleChange} />
    <span class="setting-toggle__label flex-1 min-w-0 flex flex-col gap-0.5">
        <span class="setting-toggle__title text-sm font-semibold text-sem-fg wrap-break-word leading-snug">{title}</span
        >
        {#if children}
            <span class="text-xs sm:text-sm text-sem-fg-muted wrap-break-word leading-snug">
                {@render children()}
            </span>
        {:else if description}
            <span class="text-xs sm:text-sm text-sem-fg-muted wrap-break-word leading-snug">{description}</span>
        {/if}
        {#if hint}
            <span class="text-xs text-sem-fg-muted wrap-break-word">{hint}</span>
        {/if}
    </span>
</label>
