// meshchatx/src/frontend/features/app-shell/components/AppShellBanners.svelte
<!-- SPDX-License-Identifier: 0BSD -->

<script lang="ts">
    import MaterialDesignIcon from "../../../ui/svelte/MaterialDesignIcon.svelte";

    interface Props {
        showEmergency?: boolean;
        emergencyLabel?: string;
        showDemo?: boolean;
        demoLabel?: string;
        showWsDisconnected?: boolean;
        wsDisconnectedLabel?: string;
        showBackendRecoveryActions?: boolean;
        backendRestarting?: boolean;
        restartBackendLabel?: string;
        viewBackendLogsLabel?: string;
        showWsReconnected?: boolean;
        wsReconnectedLabel?: string;
        showNetworkStarting?: boolean;
        networkStartingLabel?: string;
        showLanBindNoAuth?: boolean;
        lanBindNoAuthLabel?: string;
        dismissLanBindNoAuthLabel?: string;
        showNetworkDegraded?: boolean;
        networkDegradedLabel?: string;
        networkRecovering?: boolean;
        recoverNetworkLabel?: string;
        openSettingsLabel?: string;
        showOpenBackups?: boolean;
        openBackupsLabel?: string;
        autoRecoverLabel?: string;
        autoRecovering?: boolean;
        openInterfacesLabel?: string;

        onrestartbackend?: () => void;
        onviewbackendlogs?: () => void;
        onrecovernetwork?: () => void;
        onopensettings?: () => void;
        ondismisslanbindnoauth?: () => void;
        onopenbackups?: () => void;
        onautorecoverdatabase?: () => void;
        onopeninterfaces?: () => void;
    }

    let {
        showEmergency = false,
        emergencyLabel = "",
        showDemo = false,
        demoLabel = "",
        showWsDisconnected = false,
        wsDisconnectedLabel = "",
        showBackendRecoveryActions = false,
        backendRestarting = false,
        restartBackendLabel = "",
        viewBackendLogsLabel = "",
        showWsReconnected = false,
        wsReconnectedLabel = "",
        showNetworkStarting = false,
        networkStartingLabel = "",
        showLanBindNoAuth = false,
        lanBindNoAuthLabel = "",
        dismissLanBindNoAuthLabel = "",
        showNetworkDegraded = false,
        networkDegradedLabel = "",
        networkRecovering = false,
        recoverNetworkLabel = "",
        openSettingsLabel = "",
        showOpenBackups = false,
        openBackupsLabel = "",
        autoRecoverLabel = "",
        autoRecovering = false,
        openInterfacesLabel = "",

        onrestartbackend,
        onviewbackendlogs,
        onrecovernetwork,
        onopensettings,
        ondismisslanbindnoauth,
        onopenbackups,
        onautorecoverdatabase,
        onopeninterfaces,
    }: Props = $props();
</script>

<div>
    {#if showEmergency}
        <div
            class="relative z-100 bg-red-600 text-white px-4 py-2 text-center text-sm font-bold shadow-md animate-pulse"
        >
            <div class="flex items-center justify-center gap-2">
                <MaterialDesignIcon iconName="alert-decagram" class="size-5" />
                <span>{emergencyLabel}</span>
            </div>
        </div>
    {/if}

    {#if showDemo}
        <div
            class="relative z-100 bg-amber-600 text-white px-4 py-2 text-center text-sm font-medium shadow-md border-b border-amber-700/80"
            role="status"
        >
            {demoLabel}
        </div>
    {/if}

    {#if showWsDisconnected}
        <div
            class="relative z-100 bg-red-700 text-white px-4 py-3 text-center text-sm font-medium shadow-md border-b border-red-800/80"
            role="status"
            aria-live="polite"
        >
            <p>{wsDisconnectedLabel}</p>
            {#if showBackendRecoveryActions}
                <div class="mt-2 flex flex-wrap items-center justify-center gap-2">
                    <button
                        type="button"
                        class="rounded-md bg-white/15 px-3 py-1 text-xs font-semibold hover:bg-white/25 disabled:opacity-60"
                        disabled={backendRestarting}
                        onclick={() => onrestartbackend?.()}
                    >
                        {restartBackendLabel}
                    </button>
                    <button
                        type="button"
                        class="rounded-md bg-white/10 px-3 py-1 text-xs font-semibold hover:bg-white/20"
                        onclick={() => onviewbackendlogs?.()}
                    >
                        {viewBackendLogsLabel}
                    </button>
                </div>
            {/if}
        </div>
    {/if}

    {#if showWsReconnected}
        <div
            class="relative z-100 bg-emerald-700 text-white px-4 py-2 text-center text-sm font-medium shadow-md border-b border-emerald-800/80 transition-opacity duration-300"
            role="status"
            aria-live="polite"
        >
            {wsReconnectedLabel}
        </div>
    {/if}

    {#if showNetworkStarting}
        <div
            class="relative z-100 bg-sky-800 text-white px-4 py-2 text-center text-sm font-medium shadow-md border-b border-sky-900/80"
            role="status"
            aria-live="polite"
        >
            {networkStartingLabel}
        </div>
    {/if}

    {#if showLanBindNoAuth}
        <div
            class="relative z-100 bg-amber-700 text-white px-4 py-3 text-center text-sm font-medium shadow-md border-b border-amber-800/80"
            role="status"
            aria-live="polite"
        >
            <p>{lanBindNoAuthLabel}</p>
            <div class="mt-2 flex flex-wrap items-center justify-center gap-2">
                <button
                    type="button"
                    class="rounded-md bg-white/15 px-3 py-1 text-xs font-semibold hover:bg-white/25"
                    onclick={() => onopensettings?.()}
                >
                    {openSettingsLabel}
                </button>
                <button
                    type="button"
                    class="rounded-md bg-white/10 px-3 py-1 text-xs font-semibold hover:bg-white/20"
                    onclick={() => ondismisslanbindnoauth?.()}
                >
                    {dismissLanBindNoAuthLabel}
                </button>
            </div>
        </div>
    {/if}

    {#if showNetworkDegraded}
        <div
            class="relative z-100 bg-amber-700 text-white px-4 py-3 text-center text-sm font-medium shadow-md border-b border-amber-800/80"
            role="status"
            aria-live="polite"
        >
            <p>{networkDegradedLabel}</p>
            <div class="mt-2 flex flex-wrap items-center justify-center gap-2">
                <button
                    type="button"
                    class="rounded-md bg-white/15 px-3 py-1 text-xs font-semibold hover:bg-white/25 disabled:opacity-60"
                    disabled={networkRecovering}
                    onclick={() => onrecovernetwork?.()}
                >
                    {recoverNetworkLabel}
                </button>
                {#if !showOpenBackups}
                    <button
                        type="button"
                        class="rounded-md bg-white/10 px-3 py-1 text-xs font-semibold hover:bg-white/20"
                        onclick={() => onopensettings?.()}
                    >
                        {openSettingsLabel}
                    </button>
                {/if}
                {#if showOpenBackups}
                    <button
                        type="button"
                        class="rounded-md bg-white/15 px-3 py-1 text-xs font-semibold hover:bg-white/25 disabled:opacity-60"
                        disabled={autoRecovering}
                        onclick={() => onautorecoverdatabase?.()}
                    >
                        {autoRecoverLabel}
                    </button>
                    <button
                        type="button"
                        class="rounded-md bg-white/15 px-3 py-1 text-xs font-semibold hover:bg-white/25"
                        onclick={() => onopenbackups?.()}
                    >
                        {openBackupsLabel}
                    </button>
                {/if}
                <button
                    type="button"
                    class="rounded-md bg-white/10 px-3 py-1 text-xs font-semibold hover:bg-white/20"
                    onclick={() => onopeninterfaces?.()}
                >
                    {openInterfacesLabel}
                </button>
            </div>
        </div>
    {/if}
</div>

// meshchatx/src/frontend/components/layout/AppShellBanners.vue
<!-- SPDX-License-Identifier: 0BSD -->

<template>
    <div>
        <div
            v-if="showEmergency"
            class="relative z-100 bg-red-600 text-white px-4 py-2 text-center text-sm font-bold shadow-md animate-pulse"
        >
            <div class="flex items-center justify-center gap-2">
                <MaterialDesignIcon icon-name="alert-decagram" class="size-5" />
                <span>{{ emergencyLabel }}</span>
            </div>
        </div>

        <div
            v-if="showDemo"
            class="relative z-100 bg-amber-600 text-white px-4 py-2 text-center text-sm font-medium shadow-md border-b border-amber-700/80"
            role="status"
        >
            {{ demoLabel }}
        </div>

        <div
            v-if="showWsDisconnected"
            class="relative z-100 bg-red-700 text-white px-4 py-3 text-center text-sm font-medium shadow-md border-b border-red-800/80"
            role="status"
            aria-live="polite"
        >
            <p>{{ wsDisconnectedLabel }}</p>
            <div v-if="showBackendRecoveryActions" class="mt-2 flex flex-wrap items-center justify-center gap-2">
                <button
                    type="button"
                    class="rounded-md bg-white/15 px-3 py-1 text-xs font-semibold hover:bg-white/25 disabled:opacity-60"
                    :disabled="backendRestarting"
                    @click="$emit('restart-backend')"
                >
                    {{ restartBackendLabel }}
                </button>
                <button
                    type="button"
                    class="rounded-md bg-white/10 px-3 py-1 text-xs font-semibold hover:bg-white/20"
                    @click="$emit('view-backend-logs')"
                >
                    {{ viewBackendLogsLabel }}
                </button>
            </div>
        </div>
        <div
            v-if="showWsReconnected"
            class="relative z-100 bg-emerald-700 text-white px-4 py-2 text-center text-sm font-medium shadow-md border-b border-emerald-800/80 transition-opacity duration-300"
            role="status"
            aria-live="polite"
        >
            {{ wsReconnectedLabel }}
        </div>
        <div
            v-if="showNetworkStarting"
            class="relative z-100 bg-sky-800 text-white px-4 py-2 text-center text-sm font-medium shadow-md border-b border-sky-900/80"
            role="status"
            aria-live="polite"
        >
            {{ networkStartingLabel }}
        </div>
        <div
            v-if="showLanBindNoAuth"
            class="relative z-100 bg-amber-700 text-white px-4 py-3 text-center text-sm font-medium shadow-md border-b border-amber-800/80"
            role="status"
            aria-live="polite"
        >
            <p>{{ lanBindNoAuthLabel }}</p>
            <div class="mt-2 flex flex-wrap items-center justify-center gap-2">
                <button
                    type="button"
                    class="rounded-md bg-white/15 px-3 py-1 text-xs font-semibold hover:bg-white/25"
                    @click="$emit('open-settings')"
                >
                    {{ openSettingsLabel }}
                </button>
                <button
                    type="button"
                    class="rounded-md bg-white/10 px-3 py-1 text-xs font-semibold hover:bg-white/20"
                    @click="$emit('dismiss-lan-bind-no-auth')"
                >
                    {{ dismissLanBindNoAuthLabel }}
                </button>
            </div>
        </div>
        <div
            v-if="showNetworkDegraded"
            class="relative z-100 bg-amber-700 text-white px-4 py-3 text-center text-sm font-medium shadow-md border-b border-amber-800/80"
            role="status"
            aria-live="polite"
        >
            <p>{{ networkDegradedLabel }}</p>
            <div class="mt-2 flex flex-wrap items-center justify-center gap-2">
                <button
                    type="button"
                    class="rounded-md bg-white/15 px-3 py-1 text-xs font-semibold hover:bg-white/25 disabled:opacity-60"
                    :disabled="networkRecovering"
                    @click="$emit('recover-network')"
                >
                    {{ recoverNetworkLabel }}
                </button>
                <button
                    v-if="!showOpenBackups"
                    type="button"
                    class="rounded-md bg-white/10 px-3 py-1 text-xs font-semibold hover:bg-white/20"
                    @click="$emit('open-settings')"
                >
                    {{ openSettingsLabel }}
                </button>
                <button
                    v-if="showOpenBackups"
                    type="button"
                    class="rounded-md bg-white/15 px-3 py-1 text-xs font-semibold hover:bg-white/25 disabled:opacity-60"
                    :disabled="autoRecovering"
                    @click="$emit('auto-recover-database')"
                >
                    {{ autoRecoverLabel }}
                </button>
                <button
                    v-if="showOpenBackups"
                    type="button"
                    class="rounded-md bg-white/15 px-3 py-1 text-xs font-semibold hover:bg-white/25"
                    @click="$emit('open-backups')"
                >
                    {{ openBackupsLabel }}
                </button>
                <button
                    type="button"
                    class="rounded-md bg-white/10 px-3 py-1 text-xs font-semibold hover:bg-white/20"
                    @click="$emit('open-interfaces')"
                >
                    {{ openInterfacesLabel }}
                </button>
            </div>
        </div>
    </div>
</template>

<script>
import MaterialDesignIcon from "../MaterialDesignIcon.vue";

export default {
    name: "AppShellBanners",
    components: { MaterialDesignIcon },
    props: {
        showEmergency: {
            type: Boolean,
            default: false,
        },
        emergencyLabel: {
            type: String,
            default: "",
        },
        showDemo: {
            type: Boolean,
            default: false,
        },
        demoLabel: {
            type: String,
            default: "",
        },
        showWsDisconnected: {
            type: Boolean,
            default: false,
        },
        wsDisconnectedLabel: {
            type: String,
            default: "",
        },
        showBackendRecoveryActions: {
            type: Boolean,
            default: false,
        },
        backendRestarting: {
            type: Boolean,
            default: false,
        },
        restartBackendLabel: {
            type: String,
            default: "",
        },
        viewBackendLogsLabel: {
            type: String,
            default: "",
        },
        showWsReconnected: {
            type: Boolean,
            default: false,
        },
        wsReconnectedLabel: {
            type: String,
            default: "",
        },
        showNetworkStarting: {
            type: Boolean,
            default: false,
        },
        networkStartingLabel: {
            type: String,
            default: "",
        },
        showLanBindNoAuth: {
            type: Boolean,
            default: false,
        },
        lanBindNoAuthLabel: {
            type: String,
            default: "",
        },
        dismissLanBindNoAuthLabel: {
            type: String,
            default: "",
        },
        showNetworkDegraded: {
            type: Boolean,
            default: false,
        },
        networkDegradedLabel: {
            type: String,
            default: "",
        },
        networkRecovering: {
            type: Boolean,
            default: false,
        },
        recoverNetworkLabel: {
            type: String,
            default: "",
        },
        openSettingsLabel: {
            type: String,
            default: "",
        },
        showOpenBackups: {
            type: Boolean,
            default: false,
        },
        openBackupsLabel: {
            type: String,
            default: "",
        },
        autoRecoverLabel: {
            type: String,
            default: "",
        },
        autoRecovering: {
            type: Boolean,
            default: false,
        },
        openInterfacesLabel: {
            type: String,
            default: "",
        },
    },
    emits: [
        "restart-backend",
        "view-backend-logs",
        "recover-network",
        "open-settings",
        "dismiss-lan-bind-no-auth",
        "open-backups",
        "auto-recover-database",
        "open-interfaces",
    ],
};
</script>
