// meshchatx/src/frontend/features/plugins/components/PluginHtmlFrame.svelte
<!-- SPDX-License-Identifier: 0BSD -->

<script lang="ts">
    import { onMount, onDestroy } from "svelte";

    const CHANNEL = "meshchatx-plugin-html-frame";

    interface Props {
        pluginId: string;
        frameId?: string;
        src?: string;
        srcdoc?: string;
        title?: string;
        minHeight?: string;
        csp?: string;
        onframeAction?: (actionId: string) => void;
    }

    let {
        pluginId,
        frameId = "",
        src = "",
        srcdoc = "",
        title = "",
        minHeight = "12rem",
        csp = "default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data:;",
        onframeAction,
    }: Props = $props();

    let frameEl = $state<HTMLIFrameElement | null>(null);

    let frameSrc = $derived(src || undefined);

    let frameSrcdoc = $derived.by(() => {
        if (src) {
            return undefined;
        }
        if (!srcdoc) {
            return undefined;
        }
        const meta = `<meta http-equiv="Content-Security-Policy" content="${csp.replace(/"/g, "")}">`;
        if (srcdoc.includes("<head>")) {
            return srcdoc.replace("<head>", `<head>${meta}`);
        }
        return `<!DOCTYPE html><html><head>${meta}</head><body>${srcdoc}</body></html>`;
    });

    function onLoad(): void {
        try {
            frameEl?.contentWindow?.postMessage(
                {
                    channel: CHANNEL,
                    type: "ready",
                    pluginId,
                    frameId,
                },
                "*"
            );
        } catch {
            /* opaque sandbox */
        }
    }

    function onMessage(event: MessageEvent): void {
        if (event.source !== frameEl?.contentWindow) {
            return;
        }
        const data = event.data;
        if (!data || data.channel !== CHANNEL || data.pluginId !== pluginId) {
            return;
        }
        if (typeof data.actionId === "string") {
            onframeAction?.(data.actionId);
        }
    }

    onMount(() => {
        window.addEventListener("message", onMessage);
    });

    onDestroy(() => {
        window.removeEventListener("message", onMessage);
    });
</script>

<iframe
    bind:this={frameEl}
    class="w-full rounded-lg border border-sem-border bg-sem-surface"
    style="min-height: {minHeight}"
    title={title || "Plugin frame"}
    src={frameSrc}
    srcdoc={frameSrcdoc}
    sandbox="allow-scripts"
    referrerpolicy="no-referrer"
    onload={onLoad}
></iframe>

// meshchatx/src/frontend/components/plugins/PluginHtmlFrame.vue
<!-- SPDX-License-Identifier: 0BSD -->

<template>
    <iframe
        ref="frame"
        class="w-full rounded-lg border border-sem-border bg-sem-surface"
        :style="{ minHeight: minHeight }"
        :title="title || 'Plugin frame'"
        :src="frameSrc"
        :srcdoc="frameSrcdoc"
        sandbox="allow-scripts"
        referrerpolicy="no-referrer"
        @load="onLoad"
    />
</template>

<script>
const CHANNEL = "meshchatx-plugin-html-frame";

export default {
    name: "PluginHtmlFrame",
    props: {
        pluginId: { type: String, required: true },
        frameId: { type: String, default: "" },
        src: { type: String, default: "" },
        srcdoc: { type: String, default: "" },
        title: { type: String, default: "" },
        minHeight: { type: String, default: "12rem" },
        csp: {
            type: String,
            default: "default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data:;",
        },
    },
    emits: ["frame-action"],
    computed: {
        frameSrc() {
            return this.src || undefined;
        },
        frameSrcdoc() {
            if (this.src) {
                return undefined;
            }
            if (!this.srcdoc) {
                return undefined;
            }
            const meta = `<meta http-equiv="Content-Security-Policy" content="${this.csp.replace(/"/g, "")}">`;
            if (this.srcdoc.includes("<head>")) {
                return this.srcdoc.replace("<head>", `<head>${meta}`);
            }
            return `<!DOCTYPE html><html><head>${meta}</head><body>${this.srcdoc}</body></html>`;
        },
    },
    mounted() {
        this.onMessage = (event) => {
            if (event.source !== this.$refs.frame?.contentWindow) {
                return;
            }
            const data = event.data;
            if (!data || data.channel !== CHANNEL || data.pluginId !== this.pluginId) {
                return;
            }
            if (typeof data.actionId === "string") {
                this.$emit("frame-action", data.actionId);
            }
        };
        window.addEventListener("message", this.onMessage);
    },
    beforeUnmount() {
        window.removeEventListener("message", this.onMessage);
    },
    methods: {
        onLoad() {
            try {
                this.$refs.frame?.contentWindow?.postMessage(
                    {
                        channel: CHANNEL,
                        type: "ready",
                        pluginId: this.pluginId,
                        frameId: this.frameId,
                    },
                    "*"
                );
            } catch {
                /* opaque sandbox */
            }
        },
    },
};
</script>
