// meshchatx/src/frontend/features/plugins/PluginPage.svelte
<!-- SPDX-License-Identifier: 0BSD -->

<script lang="ts">
    import { onMount, onDestroy } from "svelte";
    import PluginSlotRenderer from "./components/PluginSlotRenderer.svelte";
    import { pluginHost } from "../../js/plugins/PluginHost.js";
    import GlobalState from "../../js/GlobalState.js";
    import { resolveEffectiveTheme, shellCanvasBackgroundStyle } from "../../theme/themeEngine.js";

    interface Props {
        pluginId?: string;
    }

    let { pluginId = "" }: Props = $props();

    let resolvedPluginId = $derived.by(() => {
        if (pluginId) return pluginId;
        if (typeof window !== "undefined" && window.location.hash) {
            const match = window.location.hash.match(/^#\/plugins\/([^/?#]+)/);
            if (match?.[1]) {
                return decodeURIComponent(match[1]);
            }
        }
        return "";
    });

    let caps = $derived(
        resolvedPluginId ? pluginHost.getPluginUiCaps(resolvedPluginId) : { allowedWidgets: [], allowHtmlFrame: false }
    );
    let allowedWidgets = $derived(caps?.allowedWidgets || []);
    let allowHtmlFrame = $derived(Boolean(caps?.allowHtmlFrame));

    let descriptor = $state<any>(null);
    let uiError = $state("");

    let config = $derived(GlobalState.config || {});
    let effectiveThemeMode = $derived(resolveEffectiveTheme((config as any)?.theme));
    let pageStyle = $derived.by(() => {
        const transparency = Number((config as any)?.ui_transparency) || 0;
        if (transparency <= 0) {
            return "";
        }
        const bg = shellCanvasBackgroundStyle(config, effectiveThemeMode);
        return bg ? `background-color: ${bg}` : "";
    });
    let panelClass = $derived.by(() => {
        const glass = (config as any)?.ui_glass_enabled !== false;
        return glass ? "glass-card bg-sem-surface/90" : "bg-sem-surface";
    });

    let uiListener: ((event: any) => void) | null = null;
    let errorListener: ((event: any) => void) | null = null;

    function onAction(actionId: string): void {
        if (resolvedPluginId) {
            pluginHost.postAction(resolvedPluginId, actionId);
        }
    }

    function onInput(payload: { id: string; value: any }): void {
        if (resolvedPluginId) {
            pluginHost.postInput(resolvedPluginId, payload.id, payload.value);
        }
    }

    $effect(() => {
        const pid = resolvedPluginId;
        if (pid) {
            descriptor = pluginHost.getLastDescriptor(pid);
            uiError = pluginHost.getLastUiError(pid) || "";
            pluginHost.requestUiRefresh(pid);
        }
    });

    onMount(() => {
        uiListener = (event: any) => {
            if (event.detail?.pluginId === resolvedPluginId) {
                descriptor = event.detail.descriptor;
                uiError = event.detail.error || "";
            }
        };
        errorListener = (event: any) => {
            if (event.detail?.pluginId === resolvedPluginId && event.detail?.uiError) {
                uiError = event.detail.message || "";
            }
        };
        window.addEventListener("meshchatx-plugin-ui", uiListener);
        window.addEventListener("meshchatx-plugin-ui-error", errorListener);
    });

    onDestroy(() => {
        if (uiListener) {
            window.removeEventListener("meshchatx-plugin-ui", uiListener);
        }
        if (errorListener) {
            window.removeEventListener("meshchatx-plugin-ui-error", errorListener);
        }
    });
</script>

<div class="h-full overflow-y-auto p-4 sm:p-6" style={pageStyle}>
    <div class="mx-auto max-w-5xl rounded-xl border border-sem-border p-4 sm:p-6 shadow-sm {panelClass}">
        <PluginSlotRenderer
            pluginId={resolvedPluginId}
            {descriptor}
            {allowedWidgets}
            {allowHtmlFrame}
            {uiError}
            onaction={onAction}
            oninput={onInput}
        />
    </div>
</div>

// meshchatx/src/frontend/components/plugins/PluginPage.vue
<!-- SPDX-License-Identifier: 0BSD -->

<template>
    <div class="h-full overflow-y-auto p-4 sm:p-6" :style="pageStyle">
        <div class="mx-auto max-w-5xl rounded-xl border border-sem-border p-4 sm:p-6 shadow-sm" :class="panelClass">
            <PluginSlotRenderer
                :plugin-id="pluginId"
                :descriptor="descriptor"
                :allowed-widgets="allowedWidgets"
                :allow-html-frame="allowHtmlFrame"
                :ui-error="uiError"
                @action="onAction"
                @input="onInput"
            />
        </div>
    </div>
</template>

<script>
import PluginSlotRenderer from "./PluginSlotRenderer.vue";
import { pluginHost } from "../../js/plugins/PluginHost.js";
import { GlobalState } from "../../js/GlobalState.js";
import { resolveEffectiveTheme, shellCanvasBackgroundStyle } from "../../theme/themeEngine.js";

export default {
    name: "PluginPage",
    components: { PluginSlotRenderer },
    props: {
        pluginId: {
            type: String,
            required: true,
        },
    },
    data() {
        return {
            descriptor: null,
            uiError: "",
            allowedWidgets: [],
            allowHtmlFrame: false,
        };
    },
    computed: {
        config() {
            return GlobalState.config || {};
        },
        effectiveThemeMode() {
            return resolveEffectiveTheme(this.config.theme);
        },
        pageStyle() {
            const transparency = Number(this.config.ui_transparency) || 0;
            if (transparency <= 0) {
                return {};
            }
            return {
                backgroundColor: shellCanvasBackgroundStyle(this.config, this.effectiveThemeMode),
            };
        },
        panelClass() {
            const glass = this.config.ui_glass_enabled !== false;
            return glass ? "glass-card bg-sem-surface/90" : "bg-sem-surface";
        },
    },
    mounted() {
        const caps = pluginHost.getPluginUiCaps(this.pluginId);
        this.allowedWidgets = caps.allowedWidgets || [];
        this.allowHtmlFrame = Boolean(caps.allowHtmlFrame);
        this.descriptor = pluginHost.getLastDescriptor(this.pluginId);
        this.uiError = pluginHost.getLastUiError(this.pluginId) || "";
        this.uiListener = (event) => {
            if (event.detail?.pluginId === this.pluginId) {
                this.descriptor = event.detail.descriptor;
                this.uiError = event.detail.error || "";
            }
        };
        this.errorListener = (event) => {
            if (event.detail?.pluginId === this.pluginId && event.detail?.uiError) {
                this.uiError = event.detail.message || "";
            }
        };
        window.addEventListener("meshchatx-plugin-ui", this.uiListener);
        window.addEventListener("meshchatx-plugin-ui-error", this.errorListener);
        pluginHost.requestUiRefresh(this.pluginId);
    },
    beforeUnmount() {
        window.removeEventListener("meshchatx-plugin-ui", this.uiListener);
        window.removeEventListener("meshchatx-plugin-ui-error", this.errorListener);
    },
    methods: {
        onAction(actionId) {
            pluginHost.postAction(this.pluginId, actionId);
        },
        onInput(payload) {
            pluginHost.postInput(this.pluginId, payload.id, payload.value);
        },
    },
};
</script>
