// meshchatx/src/frontend/components/messages/InViewAnimatedImg.vue
<template>
    <div ref="wrap" :class="wrapClass">
        <img
            v-if="show"
            :src="src"
            :loading="loading"
            :decoding="decoding"
            :class="imgClass"
            :alt="alt"
            draggable="false"
            @click="$emit('click', $event)"
        />
        <div v-else :class="placeholderClassComputed" aria-hidden="true" />
    </div>
</template>

<script>
import { attachInView } from "../../js/inViewObserver.js";

export default {
    name: "InViewAnimatedImg",
    props: {
        src: { type: String, required: true },
        imgClass: { type: String, default: "" },
        fitParent: { type: Boolean, default: false },
        alt: { type: String, default: "" },
        loading: { type: String, default: "lazy" },
        decoding: { type: String, default: "async" },
    },
    emits: ["click"],
    data() {
        return {
            show: false,
            ioCleanup: null,
        };
    },
    computed: {
        wrapClass() {
            return this.fitParent ? "absolute inset-0 overflow-hidden" : "relative w-full";
        },
        placeholderClassComputed() {
            if (this.fitParent) {
                return "absolute inset-0 bg-zinc-200/30 dark:bg-white/10";
            }
            return "min-h-32 w-full rounded-2xl bg-gray-100/90 dark:bg-zinc-800/60";
        },
    },
    mounted() {
        this.$nextTick(() => {
            const el = this.$refs.wrap;
            if (!el) {
                return;
            }
            this.ioCleanup = attachInView(el, (entry) => {
                // One-way reveal. Toggling hide collapses height and yanks the message list scroll.
                if (entry.isIntersecting) {
                    this.show = true;
                }
            });
        });
    },
    beforeUnmount() {
        if (this.ioCleanup) {
            this.ioCleanup();
        }
    },
};
</script>

// meshchatx/src/frontend/features/messages/components/InViewAnimatedImg.svelte
<!-- SPDX-License-Identifier: 0BSD -->

<script lang="ts">
    import { attachInView } from "../../../js/inViewObserver.js";

    let {
        src,
        imgClass = "",
        fitParent = false,
        alt = "",
        loading = "lazy" as "eager" | "lazy",
        decoding = "async" as "async" | "sync" | "auto",
        onclick,
    }: {
        src: string;
        imgClass?: string;
        fitParent?: boolean;
        alt?: string;
        loading?: "eager" | "lazy";
        decoding?: "async" | "sync" | "auto";
        onclick?: (event: MouseEvent) => void;
    } = $props();

    let wrap: HTMLDivElement | undefined = $state();
    let show = $state(false);

    const wrapClass = $derived(fitParent ? "absolute inset-0 overflow-hidden" : "relative w-full");
    const placeholderClass = $derived(
        fitParent
            ? "absolute inset-0 bg-zinc-200/30 dark:bg-white/10"
            : "min-h-32 w-full rounded-2xl bg-gray-100/90 dark:bg-zinc-800/60"
    );

    $effect(() => {
        const el = wrap;
        if (!el) {
            return;
        }
        const cleanup = attachInView(el, (entry: IntersectionObserverEntry) => {
            if (entry.isIntersecting) {
                show = true;
            }
        });
        return () => {
            cleanup?.();
        };
    });
</script>

<div bind:this={wrap} class={wrapClass}>
    {#if show}
        {#if onclick}
            <button type="button" class="block w-full p-0 border-0 bg-transparent cursor-pointer" {onclick}>
                <img {src} {loading} {decoding} class={imgClass} {alt} draggable="false" />
            </button>
        {:else}
            <img {src} {loading} {decoding} class={imgClass} {alt} draggable="false" />
        {/if}
    {:else}
        <div class={placeholderClass} aria-hidden="true"></div>
    {/if}
</div>
