// meshchatx/src/frontend/components/archives/ArchivesPage.vue
<!-- SPDX-License-Identifier: 0BSD -->

<template>
    <!-- eslint-disable vue/no-v-html -->
    <div class="flex h-full overflow-hidden bg-sem-canvas text-sem-fg">
        <ArchiveSidebar
            v-if="!isSidebar1Hidden"
            class="w-full shrink-0 sm:w-60 lg:w-64"
            :class="{ 'hidden sm:flex': selectedNodeHash }"
            :nodes="groupedArchives"
            :selected-node-hash="selectedNodeHash"
            :initial-search-query="searchQuery"
            @select-node="onNodeSelect"
            @update:search-query="onSearchQueryChange"
        />

        <div
            v-if="selectedNode && !isSidebar2Hidden"
            class="flex w-full shrink-0 flex-col border-r border-sem-border bg-sem-canvas sm:w-72 lg:w-80"
            :class="{ 'hidden sm:flex': viewingArchive }"
        >
            <div class="flex flex-col gap-2 border-b border-sem-border px-3 py-2.5">
                <div class="flex items-center gap-2">
                    <button
                        type="button"
                        class="rounded-lg p-1 text-sem-fg-muted hover:bg-sem-surface/60 sm:hidden"
                        @click="selectedNodeHash = null"
                    >
                        <MaterialDesignIcon icon-name="arrow-left" class="size-5" />
                    </button>
                    <h2 class="min-w-0 flex-1 truncate text-sm font-semibold">{{ selectedNode.node_name }}</h2>
                    <span class="rounded-full bg-sem-surface-muted px-2 py-0.5 text-xs text-sem-fg-muted">
                        {{ selectedNode.archives.length }}
                    </span>
                </div>

                <div class="flex items-center justify-between gap-2">
                    <button
                        v-if="!selectMode"
                        type="button"
                        class="rounded-lg px-2 py-1 text-xs font-medium text-sem-fg-muted transition-colors hover:bg-sem-surface/60 hover:text-sem-fg"
                        @click="selectMode = true"
                    >
                        {{ $t("common.select") }}
                    </button>
                    <label v-else class="flex cursor-pointer items-center gap-2">
                        <input
                            type="checkbox"
                            class="rounded border-sem-border text-sem-accent focus:ring-sem-accent/30"
                            :checked="isAllSelected"
                            @change="toggleSelectAll"
                        />
                        <span class="text-xs text-sem-fg-muted">{{ $t("archives.select_all") }}</span>
                    </label>

                    <div class="flex items-center gap-1">
                        <template v-if="selectMode && selectedArchives.length > 0">
                            <button
                                type="button"
                                class="rounded-lg p-1.5 text-sem-accent hover:bg-sem-surface/60"
                                :title="$t('archives.export_selected_mu', { count: selectedArchives.length })"
                                @click="exportSelectedArchivesAsMu"
                            >
                                <MaterialDesignIcon icon-name="download" class="size-4" />
                            </button>
                            <button
                                type="button"
                                class="rounded-lg p-1.5 text-red-500 hover:bg-sem-surface/60"
                                :title="$t('archives.delete_selected', { count: selectedArchives.length })"
                                @click="deleteSelected"
                            >
                                <MaterialDesignIcon icon-name="trash-can-outline" class="size-4" />
                            </button>
                        </template>
                        <button
                            v-if="selectMode"
                            type="button"
                            class="rounded-lg px-2 py-1 text-xs font-medium text-sem-fg-muted transition-colors hover:bg-sem-surface/60 hover:text-sem-fg"
                            @click="exitSelectMode"
                        >
                            {{ $t("common.cancel") }}
                        </button>
                    </div>
                </div>
            </div>

            <div class="flex-1 overflow-y-auto">
                <div
                    v-for="archive in selectedNode.archives"
                    :key="archive.id"
                    class="group relative flex items-stretch border-b border-sem-border/50 transition-colors hover:bg-sem-surface/40"
                    :class="{
                        'bg-sem-surface/60 ring-1 ring-inset ring-sem-accent/30': viewingArchive?.id === archive.id,
                        'bg-sem-accent/5': selectedArchives.includes(archive.id),
                    }"
                >
                    <div v-if="selectMode" class="flex items-center px-2" @click.stop>
                        <input
                            v-model="selectedArchives"
                            type="checkbox"
                            class="rounded border-sem-border text-sem-accent focus:ring-sem-accent/30"
                            :value="archive.id"
                        />
                    </div>

                    <button
                        type="button"
                        class="min-w-0 flex-1 px-2 py-2.5 text-left"
                        :class="selectMode ? '' : 'pl-3'"
                        @click="viewArchive(archive)"
                    >
                        <div class="truncate text-sm font-medium">{{ archive.page_path || "/" }}</div>
                        <div class="mt-1 flex items-center justify-between gap-2 text-xs text-sem-fg-muted">
                            <span class="inline-flex items-center gap-1">
                                <MaterialDesignIcon icon-name="clock-outline" class="size-3" />
                                {{ formatDate(archive.created_at) }}
                            </span>
                            <span class="font-mono opacity-60">{{ archive.hash.substring(0, 8) }}</span>
                        </div>
                    </button>

                    <button
                        type="button"
                        class="self-center rounded-lg p-2 text-sem-fg-muted opacity-0 transition-opacity hover:text-red-500 group-hover:opacity-100"
                        :title="$t('archives.delete_snapshot')"
                        @click.stop="deleteArchive(archive)"
                    >
                        <MaterialDesignIcon icon-name="trash-can-outline" class="size-4" />
                    </button>
                </div>
            </div>
        </div>

        <div
            class="flex min-w-0 flex-1 flex-col overflow-hidden bg-sem-canvas"
            :class="{ 'hidden sm:flex': !viewingArchive }"
        >
            <div v-if="viewingArchive" class="flex shrink-0 items-center gap-1 border-b border-sem-border px-2 py-2">
                <button
                    type="button"
                    class="rounded-lg p-1 text-sem-fg-muted hover:bg-sem-surface/60 sm:hidden"
                    @click="viewingArchive = null"
                >
                    <MaterialDesignIcon icon-name="arrow-left" class="size-5" />
                </button>

                <div class="min-w-0 flex-1 px-1">
                    <div class="text-xs text-sem-fg-muted">{{ $t("archives.viewing_archive") }}</div>
                    <div class="truncate font-mono text-sm">{{ viewingArchive.page_path || "/" }}</div>
                </div>

                <div class="flex items-center gap-0.5">
                    <button
                        type="button"
                        class="hidden rounded-lg p-2 hover:bg-sem-surface/60 sm:block"
                        :class="isSidebar1Hidden ? 'text-sem-fg-muted' : 'text-sem-accent'"
                        :title="isSidebar1Hidden ? $t('archives.show_nodes') : $t('archives.hide_nodes')"
                        @click="isSidebar1Hidden = !isSidebar1Hidden"
                    >
                        <MaterialDesignIcon icon-name="page-layout-sidebar-left" class="size-4" />
                    </button>
                    <button
                        type="button"
                        class="hidden rounded-lg p-2 hover:bg-sem-surface/60 sm:block"
                        :class="isSidebar2Hidden ? 'text-sem-fg-muted' : 'text-sem-accent'"
                        :title="isSidebar2Hidden ? $t('archives.show_snapshots') : $t('archives.hide_snapshots')"
                        @click="isSidebar2Hidden = !isSidebar2Hidden"
                    >
                        <MaterialDesignIcon icon-name="view-list" class="size-4" />
                    </button>
                    <button
                        type="button"
                        class="rounded-lg p-2 text-sem-fg hover:bg-sem-surface/60"
                        :title="$t('archives.export_mu')"
                        @click="exportArchiveAsMu(viewingArchive)"
                    >
                        <MaterialDesignIcon icon-name="download" class="size-4" />
                    </button>
                    <button
                        type="button"
                        class="rounded-lg p-2 text-sem-accent hover:bg-sem-surface/60"
                        :title="$t('archives.open_live')"
                        @click="openInNomadnet(viewingArchive)"
                    >
                        <MaterialDesignIcon icon-name="open-in-new" class="size-4" />
                    </button>
                    <button
                        type="button"
                        class="hidden rounded-lg p-2 text-sem-fg-muted hover:bg-sem-surface/60 sm:block"
                        :title="$t('common.cancel')"
                        @click="viewingArchive = null"
                    >
                        <MaterialDesignIcon icon-name="close" class="size-5" />
                    </button>
                </div>
            </div>

            <div class="nodeContainer flex-1 overflow-y-auto overscroll-contain p-4">
                <div v-if="isLoading" class="flex h-full items-center justify-center text-sem-fg-muted">
                    <MaterialDesignIcon icon-name="refresh" class="size-8 animate-spin-reverse" />
                </div>
                <div
                    v-else-if="!viewingArchive"
                    class="flex h-full flex-col items-center justify-center gap-3 text-sem-fg-muted"
                >
                    <MaterialDesignIcon icon-name="archive-clock-outline" class="size-14 opacity-30" />
                    <div class="text-sm">{{ $t("archives.select_snapshot") }}</div>
                </div>
                <div
                    v-else
                    class="h-full selection:bg-sem-accent/30"
                    :class="archiveViewerClasses"
                    @click.capture="onArchiveContentClick"
                    v-html="renderedContent"
                ></div>
            </div>
        </div>
    </div>
</template>

<script>
import MaterialDesignIcon from "../MaterialDesignIcon.vue";
import Utils from "../../js/Utils";
import DownloadUtils from "../../js/DownloadUtils";
import MicronParser from "../../js/MicronParser.js";
import GlobalState from "../../js/GlobalState.js";
import {
    preloadNomadMicronWasm,
    invalidateNomadMicronWasmPreload,
    isMicronWasmBundled,
} from "../../js/MicronWasmLoader.js";
import { renderNomadPageByPath, isolateNomadLinksInHtml } from "../../js/NomadPageRenderer.js";
import { handleRichHtmlLinkClick } from "../../js/NomadRichHtmlLinks.js";
import ArchiveSidebar from "./ArchiveSidebar.vue";

export default {
    name: "ArchivesPage",
    components: {
        MaterialDesignIcon,
        ArchiveSidebar,
    },
    data() {
        return {
            archives: [],
            isLoading: false,
            selectedNodeHash: null,
            viewingArchive: null,
            isSidebar1Hidden: false,
            isSidebar2Hidden: false,
            renderedContent: "",
            searchQuery: "",
            selectedArchives: [],
            selectMode: false,
            pagination: {
                page: 1,
                limit: 500, // Reduced from 1000 to improve initial load
            },
            nomadMicronWasmReady: false,
        };
    },
    computed: {
        nomadMicronWasmFeatureEffective() {
            return isMicronWasmBundled() && (GlobalState.config || {}).nomad_micron_wasm_enabled === true;
        },
        nomadMicronWasmActive() {
            const engineWasm = (GlobalState.config?.nomad_micron_default_engine || "js") === "wasm";
            return (
                this.nomadMicronWasmFeatureEffective &&
                this.nomadMicronWasmReady === true &&
                typeof globalThis.micronConvert === "function" &&
                engineWasm
            );
        },
        nomadRenderOptions() {
            const c = GlobalState.config || {};
            const hash = this.viewingArchive?.destination_hash || null;
            const engineWasm = (c.nomad_micron_default_engine || "js") === "wasm";
            return {
                renderMarkdown: c.nomad_render_markdown_enabled !== false,
                renderHtml: c.nomad_render_html_enabled !== false,
                renderPlaintext: c.nomad_render_plaintext_enabled !== false,
                nomadDestinationHash: hash,
                nomad_micron_wasm_use:
                    this.nomadMicronWasmFeatureEffective && this.nomadMicronWasmReady === true && engineWasm,
            };
        },
        selectedNode() {
            if (!this.selectedNodeHash) return null;
            return this.groupedArchives.find((g) => g.destination_hash === this.selectedNodeHash);
        },
        isAllSelected() {
            if (!this.selectedNode || this.selectedNode.archives.length === 0) return false;
            return this.selectedNode.archives.every((a) => this.selectedArchives.includes(a.id));
        },
        archiveViewerClasses() {
            const a = this.viewingArchive;
            if (!a?.page_path) {
                return ["wrap-break-word", "whitespace-pre-wrap", "text-gray-100"];
            }
            const pl = (a.page_path || "").split("`")[0].toLowerCase();
            const isRich = pl.endsWith(".mu") || pl.endsWith(".md") || pl.endsWith(".html");
            const isHtml = pl.endsWith(".html");
            const isMd = pl.endsWith(".md");
            const classes = ["wrap-break-word"];
            if (isRich) {
                classes.push("nomad-page-rich");
            } else {
                classes.push("whitespace-pre-wrap");
            }
            if (isHtml) {
                classes.push("nomad-page-html-host");
            } else {
                classes.push("text-gray-100");
            }
            if (isMd) {
                classes.push("nomad-markdown-host");
            }
            return classes;
        },
        groupedArchives() {
            // Optimization: Use a simple object for grouping
            const groups = {};
            const list = this.archives || [];
            for (let i = 0; i < list.length; i++) {
                const archive = list[i];
                const hash = archive.destination_hash;
                if (!groups[hash]) {
                    groups[hash] = {
                        destination_hash: hash,
                        node_name: archive.node_name,
                        archives: [],
                    };
                }
                groups[hash].archives.push(archive);
            }

            return Object.values(groups).sort((a, b) => {
                // Sort by latest archive date
                const dateA = new Date(a.archives[0].created_at);
                const dateB = new Date(b.archives[0].created_at);
                return dateB - dateA;
            });
        },
    },
    watch: {
        groupedArchives(newVal) {
            if (!this.selectedNodeHash && newVal.length > 0 && window.innerWidth >= 640) {
                this.selectedNodeHash = newVal[0].destination_hash;
            }
        },
        viewingArchive(newVal) {
            if (newVal) {
                // Defer heavy rendering to next tick or use a small delay to prevent UI freezing
                this.renderedContent = "Rendering...";
                setTimeout(() => {
                    this.renderedContent = this.renderFullContent(newVal);
                }, 10);
            } else {
                this.renderedContent = "";
                this.isSidebar1Hidden = false;
                this.isSidebar2Hidden = false;
            }
        },
    },
    mounted() {
        this.getArchives();

        this.$watch(
            () => GlobalState.config?.nomad_micron_wasm_enabled,
            async (enabled) => {
                if (!isMicronWasmBundled()) {
                    this.nomadMicronWasmReady = false;
                    return;
                }
                if (!enabled) {
                    this.nomadMicronWasmReady = false;
                    return;
                }
                invalidateNomadMicronWasmPreload();
                this.nomadMicronWasmReady = await preloadNomadMicronWasm();
                const a = this.viewingArchive;
                if (a) {
                    this.renderedContent = this.renderFullContent(a);
                }
            }
        );

        this.$watch(
            () => GlobalState.config?.nomad_micron_default_engine,
            () => {
                const a = this.viewingArchive;
                if (a) {
                    this.renderedContent = this.renderFullContent(a);
                }
            }
        );

        if (isMicronWasmBundled() && GlobalState.config?.nomad_micron_wasm_enabled === true) {
            preloadNomadMicronWasm().then((ok) => {
                this.nomadMicronWasmReady = ok === true;
                const a = this.viewingArchive;
                if (a && ok) {
                    this.renderedContent = this.renderFullContent(a);
                }
            });
        }
    },
    methods: {
        async getArchives() {
            this.isLoading = true;
            try {
                const response = await window.api.get("/api/v1/nomadnet/archives", {
                    params: {
                        page: 1,
                        limit: 500,
                        q: this.searchQuery,
                    },
                });
                this.archives = response.data.archives;
            } catch (e) {
                console.error("Failed to load archives:", e);
            } finally {
                this.isLoading = false;
            }
        },
        onSearchQueryChange(query) {
            this.searchQuery = query;
            // Debounce search
            clearTimeout(this.searchTimeout);
            this.searchTimeout = setTimeout(() => {
                this.getArchives();
            }, 300);
        },
        onNodeSelect(node) {
            this.selectedNodeHash = node.destination_hash;
            this.selectedArchives = [];
            this.selectMode = false;
            // On desktop, auto-select latest archive. On mobile, just show the list.
            if (window.innerWidth >= 640 && node.archives && node.archives.length > 0) {
                this.viewingArchive = node.archives[0];
            } else {
                this.viewingArchive = null;
            }
        },
        toggleSelectAll() {
            if (this.isAllSelected) {
                this.selectedArchives = [];
            } else if (this.selectedNode) {
                this.selectedArchives = this.selectedNode.archives.map((a) => a.id);
            }
        },
        exitSelectMode() {
            this.selectMode = false;
            this.selectedArchives = [];
        },
        async deleteSelected() {
            if (this.selectedArchives.length === 0) return;

            if (!confirm(`Are you sure you want to delete ${this.selectedArchives.length} selected snapshots?`)) {
                return;
            }

            try {
                await window.api.delete("/api/v1/nomadnet/archives", {
                    data: { ids: this.selectedArchives },
                });

                // Remove from local list
                this.archives = this.archives.filter((a) => !this.selectedArchives.includes(a.id));
                this.selectedArchives = [];

                if (this.viewingArchive && !this.archives.find((a) => a.id === this.viewingArchive.id)) {
                    this.viewingArchive = null;
                }

                // If current node has no more archives, deselect it
                if (this.selectedNode && this.selectedNode.archives.length === 0) {
                    this.selectedNodeHash = null;
                }
            } catch (e) {
                console.error("Failed to delete archives:", e);
                alert("Failed to delete snapshots. Please try again.");
            }
        },
        async deleteArchive(archive) {
            if (!confirm("Are you sure you want to delete this snapshot?")) {
                return;
            }

            try {
                await window.api.delete("/api/v1/nomadnet/archives", {
                    data: { ids: [archive.id] },
                });

                // Remove from local list
                this.archives = this.archives.filter((a) => a.id !== archive.id);
                this.selectedArchives = this.selectedArchives.filter((id) => id !== archive.id);

                if (this.viewingArchive?.id === archive.id) {
                    this.viewingArchive = null;
                }

                // If current node has no more archives, deselect it
                if (this.selectedNode && this.selectedNode.archives.length === 0) {
                    this.selectedNodeHash = null;
                }
            } catch (e) {
                console.error("Failed to delete archive:", e);
                alert("Failed to delete snapshot. Please try again.");
            }
        },
        viewArchive(archive) {
            this.viewingArchive = archive;
        },
        openInNomadnet(archive) {
            this.$router.push({
                name: "nomadnetwork",
                params: { destinationHash: archive.destination_hash },
                query: {
                    path: archive.page_path,
                    archive_id: archive.id,
                },
            });
        },
        formatDate(dateStr) {
            return Utils.formatTimeAgo(dateStr);
        },
        onArchiveContentClick(event) {
            handleRichHtmlLinkClick(event, {
                onNomadUrl: (url) => {
                    const [hash, ...pathParts] = url.split(":");
                    const path = pathParts.join(":");
                    this.$router.push({
                        name: "nomadnetwork",
                        params: { destinationHash: hash },
                        query: { path: path },
                    });
                },
                onOpenNode: (destination) => {
                    const [hash, ...pathParts] = destination.split(":");
                    const path = pathParts.join(":") || "/page/index.mu";
                    this.$router.push({
                        name: "nomadnetwork",
                        params: { destinationHash: hash },
                        query: { path: path },
                    });
                },
            });
        },
        async downloadTextAsFile(content, filename) {
            const blob = new Blob([content ?? ""], { type: "text/plain;charset=utf-8" });
            await DownloadUtils.downloadFile(filename, blob);
        },
        muExportBasename(archive) {
            let base = (archive.page_path || "page").split("/").pop() || "page";
            base = base.replace(/[\\/:*?"<>|]+/g, "_").trim() || "page";
            return base;
        },
        muExportFilename(archive) {
            let base = this.muExportBasename(archive);
            const lower = base.toLowerCase();
            const allowed = [".mu", ".md", ".txt", ".html"];
            if (allowed.some((ext) => lower.endsWith(ext))) {
                return base;
            }
            const without = base.includes(".") ? base.replace(/\.[^.]+$/, "") : base;
            return `${without || "page"}.mu`;
        },
        muExportFilenameDisambiguated(archive) {
            const name = this.muExportFilename(archive);
            const m = name.match(/^(.+)(\.[^.]+)$/);
            const stem = m ? m[1] : name.replace(/\.[^.]+$/, "");
            const ext = m ? m[2] : ".mu";
            const short = (archive.hash || "snap").substring(0, 8);
            return `${stem}_${short}${ext}`;
        },
        exportArchiveAsMu(archive) {
            if (!archive) {
                return;
            }
            this.downloadTextAsFile(archive.content, this.muExportFilename(archive));
        },
        exportSelectedArchivesAsMu() {
            const list = this.archives.filter((a) => this.selectedArchives.includes(a.id));
            list.forEach((archive, i) => {
                window.setTimeout(() => {
                    this.downloadTextAsFile(archive.content, this.muExportFilenameDisambiguated(archive));
                }, i * 120);
            });
        },
        renderFullContent(archive) {
            if (!archive.content) {
                return "";
            }
            const pathPart = (archive.page_path || "").split("`")[0];
            const pl = pathPart.toLowerCase();
            const hasKnownExt = /\.(mu|md|txt|html)$/.test(pl);
            const micronOpts = {
                useWasm: this.nomadMicronWasmActive,
            };
            const destinationHash = archive.destination_hash || this.viewingArchive?.destination_hash || null;
            try {
                if (!hasKnownExt && archive.content.includes("`")) {
                    let out = new MicronParser().convertMicronToHtml(archive.content, {}, micronOpts);
                    if (destinationHash) {
                        out = isolateNomadLinksInHtml(out, destinationHash);
                    }
                    return out;
                }
                return renderNomadPageByPath(pathPart, archive.content, {}, MicronParser, {
                    ...this.nomadRenderOptions,
                    nomadDestinationHash: destinationHash || this.nomadRenderOptions.nomadDestinationHash,
                });
            } catch (e) {
                console.error("Archive render failed", e);
                return String(archive.content)
                    .replace(/&/g, "&amp;")
                    .replace(/</g, "&lt;")
                    .replace(/>/g, "&gt;")
                    .replace(/"/g, "&quot;")
                    .replace(/'/g, "&#039;");
            }
        },
    },
};
</script>

<style scoped>
pre {
    font-family: "Roboto Mono Nerd Font", ui-monospace, monospace;
    font-size: 13px;
    line-height: 1.5;
    letter-spacing: normal;
    font-variant-ligatures: none;
    font-feature-settings: normal;
}

/* Ensure long pages don't lag the layout */
.nodeContainer {
    contain: content;
}

:deep(.nodeContainer) a {
    color: #3b82f6;
    text-decoration: underline;
}

:deep(.nodeContainer) p {
    margin: 0.5rem 0;
}

:deep(.nodeContainer) h1,
:deep(.nodeContainer) h2,
:deep(.nodeContainer) h3 {
    margin: 1.25rem 0 0.75rem 0;
    font-weight: bold;
    line-height: 1.2;
}

:deep(.nodeContainer) h1 {
    font-size: 1.5rem;
}
:deep(.nodeContainer) h2 {
    font-size: 1.25rem;
}
:deep(.nodeContainer) h3 {
    font-size: 1.1rem;
}

:deep(.nodeContainer) hr {
    margin: 1.5rem 0;
    border: 0;
    border-top: 1px solid rgba(255, 255, 255, 0.1);
}
</style>

<style>
/* Match NomadNetworkPage so archives render Markdown/HTML before that route is loaded */
.nomad-markdown-host {
    font-family: ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji";
}

.nomad-markdown-host .nomad-markdown {
    white-space: pre-wrap;
    word-wrap: break-word;
}

.nomad-markdown-host .nomad-markdown table {
    white-space: normal;
}

.nomad-markdown-host .nomad-markdown h1 {
    font-size: 1.875rem;
    line-height: 2.25rem;
    font-weight: 700;
    margin: 0.75rem 0 0.5rem;
}

.nomad-markdown-host .nomad-markdown h2 {
    font-size: 1.5rem;
    line-height: 2rem;
    font-weight: 700;
    margin: 0.65rem 0 0.45rem;
}

.nomad-markdown-host .nomad-markdown h3 {
    font-size: 1.25rem;
    line-height: 1.75rem;
    font-weight: 600;
    margin: 0.55rem 0 0.4rem;
}

.nomad-markdown-host .nomad-markdown h4 {
    font-size: 1.125rem;
    line-height: 1.75rem;
    font-weight: 600;
    margin: 0.5rem 0 0.35rem;
}

.nomad-markdown-host .nomad-markdown h5,
.nomad-markdown-host .nomad-markdown h6 {
    font-size: 1rem;
    line-height: 1.5rem;
    font-weight: 600;
    margin: 0.45rem 0 0.3rem;
}

.nomad-markdown-host .nomad-markdown p {
    margin: 0.4rem 0;
}

.nomad-markdown-host .nomad-markdown ul,
.nomad-markdown-host .nomad-markdown ol {
    margin: 0.4rem 0;
    padding-left: 1.5rem;
}

.nomad-markdown-host .nomad-markdown blockquote {
    margin: 0.5rem 0;
    padding-left: 0.75rem;
    border-left: 3px solid rgb(107 114 128);
}

.nomad-markdown-host .nomad-markdown pre {
    white-space: pre-wrap;
    word-wrap: break-word;
    overflow-x: auto;
}

.nomad-page-html-host {
    font-family: ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji";
}

.nomad-page-html-host .nomad-html-root {
    color: rgb(229 231 235);
}
</style>

// meshchatx/src/frontend/features/archives/ArchivesPage.svelte
<!-- SPDX-License-Identifier: 0BSD -->

<script lang="ts">
    import { onMount } from "svelte";
    import { SvelteMap } from "svelte/reactivity";
    import DialogUtils from "../../js/DialogUtils.js";
    import GlobalState from "../../js/GlobalState.js";
    import {
        invalidateNomadMicronWasmPreload,
        isMicronWasmBundled,
        preloadNomadMicronWasm,
    } from "../../js/MicronWasmLoader.js";
    import ToastUtils from "../../js/ToastUtils.js";
    import { t } from "../../js/i18n.js";
    import MaterialDesignIcon from "../../ui/svelte/MaterialDesignIcon.svelte";
    import ArchiveCard from "./components/ArchiveCard.svelte";
    import ArchiveViewer from "./components/ArchiveViewer.svelte";
    import { exportArchiveAsMu } from "./lib/archiveExport.js";
    import {
        handleArchiveContentClick,
        openInNomadnet,
        type RouterLike,
    } from "./lib/archiveNavigation.js";
    import { renderFullContent, shortHash } from "./lib/archiveRender.js";
    import {
        API_NOMADNET_ARCHIVES,
        API_NOMADNET_ARCHIVES_RECRAWL,
        API_NOMADNET_OPT_OUTS,
        DEFAULT_PAGE_LIMIT,
        SEARCH_DEBOUNCE_MS,
        SPLIT_MIN_WIDTH,
    } from "./lib/constants.js";
    import type {
        ArchiveItem,
        ArchiveItemApiResponse,
        ArchivePagination,
        ArchiveRecrawlApiResponse,
        ArchivesApiResponse,
        NodeOption,
        NomadRenderOptions,
    } from "./lib/types.js";

    interface Props {
        routeQuery?: Record<string, string>;
        router?: RouterLike;
    }

    let { routeQuery = {}, router }: Props = $props();

    let archives = $state<ArchiveItem[]>([]);
    let isLoading = $state(false);
    let isSearching = $state(false);
    let isLoadingViewer = $state(false);
    let isRecrawling = $state(false);
    let loadError = $state(false);
    let viewingArchive = $state<ArchiveItem | null>(null);
    let renderedContent = $state("");
    let searchQuery = $state("");
    let nodeFilter = $state("");
    let nodeOptions = $state<NodeOption[]>([]);
    let isWideSplit = $state(false);
    let cardPreviewCache = $state<Record<string, string>>({});
    let nomadMicronWasmReady = $state(false);
    let searchTimeout: ReturnType<typeof setTimeout> | null = null;

    let pagination = $state<ArchivePagination>({
        page: 1,
        limit: DEFAULT_PAGE_LIMIT,
        total_count: 0,
        total_pages: 0,
    });

    const rangeStart = $derived(
        pagination.total_count > 0 ? (pagination.page - 1) * pagination.limit + 1 : 0
    );

    const rangeEnd = $derived(
        Math.min(pagination.page * pagination.limit, pagination.total_count)
    );

    const nomadMicronWasmFeatureEffective: boolean = $derived(
        Boolean(isMicronWasmBundled()) && (GlobalState.config || {}).nomad_micron_wasm_enabled === true
    );

    const nomadMicronWasmActive: boolean = $derived(
        Boolean(
            nomadMicronWasmFeatureEffective &&
            nomadMicronWasmReady &&
            typeof globalThis.micronConvert === "function" &&
            ((GlobalState.config?.nomad_micron_default_engine || "js") === "wasm")
        )
    );

    const nomadRenderOptions = $derived<NomadRenderOptions>({
        renderMarkdown: GlobalState.config?.nomad_render_markdown_enabled !== false,
        renderHtml: GlobalState.config?.nomad_render_html_enabled !== false,
        renderPlaintext: GlobalState.config?.nomad_render_plaintext_enabled !== false,
        nomadDestinationHash: viewingArchive?.destination_hash || null,
        nomad_micron_wasm_use:
            Boolean(nomadMicronWasmFeatureEffective) &&
            Boolean(nomadMicronWasmReady) &&
            ((GlobalState.config?.nomad_micron_default_engine || "js") === "wasm"),
    });

    function updateWideSplit(): void {
        isWideSplit = typeof window !== "undefined" && window.innerWidth >= SPLIT_MIN_WIDTH;
    }

    function refreshNodeOptions(): void {
        const map = new SvelteMap<string, NodeOption>();
        for (const a of archives) {
            if (!map.has(a.destination_hash)) {
                map.set(a.destination_hash, {
                    hash: a.destination_hash,
                    label: `${a.node_name} (${shortHash(a.destination_hash)})`,
                });
            }
        }
        if (nodeFilter && !map.has(nodeFilter)) {
            map.set(nodeFilter, {
                hash: nodeFilter,
                label: shortHash(nodeFilter),
            });
        }
        nodeOptions = Array.from(map.values()).sort((a, b) => a.label.localeCompare(b.label));
    }

    async function getArchives(): Promise<void> {
        isLoading = true;
        isSearching = Boolean(searchQuery);
        loadError = false;
        try {
            const params: Record<string, unknown> = {
                page: pagination.page,
                limit: pagination.limit,
                include_content: false,
            };
            if (searchQuery) {
                params.q = searchQuery;
            }
            if (nodeFilter) {
                params.destination_hash = nodeFilter;
            }
            const response = await window.api.get(API_NOMADNET_ARCHIVES, { params });
            const data = response.data as ArchivesApiResponse | undefined;
            archives = data?.archives || [];
            const pag = data?.pagination || {};
            pagination = {
                page: pag.page || pagination.page,
                limit: pag.limit || pagination.limit,
                total_count: pag.total_count || 0,
                total_pages: pag.total_pages || 0,
            };
            refreshNodeOptions();
            cardPreviewCache = {};
        } catch (e) {
            console.error("Failed to load archives:", e);
            loadError = true;
            ToastUtils.error(t("archives.search_failed"));
        } finally {
            isLoading = false;
            isSearching = false;
        }
    }

    function onSearchInput(): void {
        if (searchTimeout) {
            clearTimeout(searchTimeout);
        }
        isSearching = true;
        searchTimeout = setTimeout(() => {
            pagination.page = 1;
            getArchives();
        }, SEARCH_DEBOUNCE_MS);
    }

    function clearSearch(): void {
        searchQuery = "";
        pagination.page = 1;
        getArchives();
    }

    function onFilterChange(): void {
        pagination.page = 1;
        getArchives();
    }

    function goPage(page: number): void {
        pagination.page = page;
        getArchives();
    }

    async function openArchive(archive: ArchiveItem): Promise<void> {
        isLoadingViewer = true;
        viewingArchive = { ...archive, content: archive.content || null };
        try {
            const response = await window.api.get(`${API_NOMADNET_ARCHIVES}/${archive.id}`);
            const full = (response.data as ArchiveItemApiResponse | undefined)?.archive;
            if (full) {
                viewingArchive = full;
                renderedContent = renderFullContent(full, nomadRenderOptions, nomadMicronWasmActive);
            }
        } catch (e) {
            console.error("Failed to load archive:", e);
            ToastUtils.error(t("archives.failed_load"));
            viewingArchive = null;
        } finally {
            isLoadingViewer = false;
        }
    }

    function closeViewer(): void {
        viewingArchive = null;
        renderedContent = "";
    }

    async function recrawlArchive(archive: ArchiveItem): Promise<void> {
        if (!archive || isRecrawling) {
            return;
        }
        isRecrawling = true;
        const toastKey = `archives-recrawl-${archive.id || archive.destination_hash}`;
        ToastUtils.loading(t("archives.recrawl_pending"), 0, toastKey);
        try {
            const response = await window.api.post(API_NOMADNET_ARCHIVES_RECRAWL, {
                destination_hash: archive.destination_hash,
                page_path: archive.page_path,
            });
            ToastUtils.dismiss(toastKey);
            const next = (response.data as ArchiveRecrawlApiResponse | undefined)?.archive;
            ToastUtils.success(t("archives.recrawl_done"));
            if (next) {
                viewingArchive = next;
                renderedContent = renderFullContent(next, nomadRenderOptions, nomadMicronWasmActive);
                const idx = archives.findIndex(
                    (a) => a.destination_hash === next.destination_hash && a.page_path === next.page_path
                );
                if (idx >= 0) {
                    archives[idx] = {
                        ...archives[idx],
                        ...next,
                        content: undefined,
                    };
                } else {
                    archives.unshift({
                        ...next,
                        content: undefined,
                    });
                }
                cardPreviewCache = {};
            } else {
                await getArchives();
            }
        } catch (e: any) {
            ToastUtils.dismiss(toastKey);
            console.error("Recrawl failed:", e);
            const msg = e?.response?.data?.message || t("archives.recrawl_failed");
            ToastUtils.error(msg);
        } finally {
            isRecrawling = false;
        }
    }

    async function deleteArchive(archive: ArchiveItem): Promise<void> {
        if (!(await DialogUtils.confirm(t("archives.delete_snapshot_confirm")))) {
            return;
        }
        try {
            await window.api.delete(API_NOMADNET_ARCHIVES, {
                data: { ids: [archive.id] },
            });
            archives = archives.filter((a) => a.id !== archive.id);
            if (viewingArchive?.id === archive.id) {
                closeViewer();
            }
            pagination.total_count = Math.max(0, pagination.total_count - 1);
            ToastUtils.success(t("archives.deleted"));
        } catch (e) {
            console.error("Failed to delete archive:", e);
            ToastUtils.error(t("archives.failed_delete"));
        }
    }

    async function optOutNode(archive: ArchiveItem): Promise<void> {
        if (!(await DialogUtils.confirm(t("archives.never_crawl_confirm")))) {
            return;
        }
        try {
            await window.api.post(API_NOMADNET_OPT_OUTS, {
                destination_hash: archive.destination_hash,
                reason: "user",
            });
            ToastUtils.success(t("archives.never_crawl_saved"));
        } catch (e) {
            console.error("Failed to opt out node:", e);
            ToastUtils.error(t("archives.never_crawl_failed"));
        }
    }

    function handleOpenInNomadnet(archive: ArchiveItem): void {
        openInNomadnet(archive, router);
    }

    function handleContentClick(event: MouseEvent): void {
        handleArchiveContentClick(event, router);
    }

    onMount(() => {
        updateWideSplit();
        window.addEventListener("resize", updateWideSplit);
        const q = routeQuery?.q;
        if (typeof q === "string" && q) {
            searchQuery = q;
        }
        getArchives();

        const cfg = (GlobalState.config || {}) as Record<string, unknown>;
        if (isMicronWasmBundled() && cfg.nomad_micron_wasm_enabled === true) {
            preloadNomadMicronWasm().then((ok) => {
                nomadMicronWasmReady = ok === true;
                cardPreviewCache = {};
                if (viewingArchive && ok) {
                    renderedContent = renderFullContent(
                        viewingArchive,
                        nomadRenderOptions,
                        nomadMicronWasmActive
                    );
                }
            });
        }

        return () => {
            window.removeEventListener("resize", updateWideSplit);
            if (searchTimeout) {
                clearTimeout(searchTimeout);
            }
        };
    });
</script>

<div class="flex h-full min-h-0 flex-col overflow-hidden bg-sem-canvas text-sem-fg" data-testid="archives-page">
    <div class="shrink-0 border-b border-sem-border px-3 py-3 sm:px-4">
        <div class="mx-auto flex w-full max-w-6xl flex-col gap-3">
            <div class="flex items-start justify-between gap-3">
                <div class="min-w-0">
                    <h1 class="text-lg font-semibold sm:text-xl">{t("archives.title")}</h1>
                    <p class="mt-0.5 text-xs text-sem-fg-muted sm:text-sm">{t("archives.description")}</p>
                </div>
                {#if viewingArchive && !isWideSplit}
                    <button
                        type="button"
                        class="rounded-lg p-2 text-sem-fg-muted hover:bg-sem-surface/60"
                        title={t("archives.close_viewer")}
                        onclick={closeViewer}
                    >
                        <MaterialDesignIcon iconName="close" class="size-5" />
                    </button>
                {/if}
            </div>

            {#if !viewingArchive || isWideSplit}
                <div class="relative">
                    <MaterialDesignIcon
                        iconName="magnify"
                        class="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-sem-fg-muted"
                    />
                    <input
                        bind:value={searchQuery}
                        type="search"
                        placeholder={t("archives.search_placeholder")}
                        class="w-full rounded-xl border border-sem-border bg-sem-surface py-2.5 pl-10 pr-10 text-sm text-sem-fg placeholder:text-sem-fg-muted focus:border-sem-accent focus:outline-hidden focus:ring-2 focus:ring-sem-accent/20"
                        oninput={onSearchInput}
                    />
                    {#if isSearching}
                        <div class="absolute inset-y-0 right-3 flex items-center">
                            <MaterialDesignIcon iconName="loading" class="size-4 animate-spin text-sem-fg-muted" />
                        </div>
                    {:else if searchQuery}
                        <button
                            type="button"
                            class="absolute inset-y-0 right-2 flex items-center rounded p-1 text-sem-fg-muted hover:text-sem-fg"
                            title={t("archives.clear_search")}
                            onclick={clearSearch}
                        >
                            <MaterialDesignIcon iconName="close" class="size-4" />
                        </button>
                    {/if}
                </div>

                <div class="flex flex-wrap items-center gap-2 text-xs text-sem-fg-muted">
                    {#if pagination.total_count > 0}
                        <span class="rounded-full bg-sem-surface-muted px-2 py-0.5 font-medium">
                            {searchQuery
                                ? t("archives.matches_count", { count: pagination.total_count })
                                : t("archives.showing_range", {
                                      start: rangeStart,
                                      end: rangeEnd,
                                      total: pagination.total_count,
                                  })}
                        </span>
                    {/if}
                    <label class="ml-auto flex items-center gap-1.5">
                        <span>{t("archives.filter_node")}</span>
                        <select
                            bind:value={nodeFilter}
                            class="rounded-lg border border-sem-border bg-sem-canvas px-2 py-1 text-xs text-sem-fg"
                            onchange={onFilterChange}
                        >
                            <option value="">{t("archives.all_nodes")}</option>
                            {#each nodeOptions as node (node.hash)}
                                <option value={node.hash}>
                                    {node.label}
                                </option>
                            {/each}
                        </select>
                    </label>
                </div>
            {/if}
        </div>
    </div>

    <div
        class="mx-auto flex min-h-0 w-full max-w-6xl flex-1 overflow-hidden {isWideSplit
            ? 'flex-row'
            : 'flex-col'}"
    >
        {#if !viewingArchive || isWideSplit}
            <div
                class="flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden {isWideSplit && viewingArchive
                    ? 'lg:max-w-md lg:border-r lg:border-sem-border xl:max-w-lg'
                    : ''}"
            >
                {#if loadError}
                    <div class="flex flex-1 flex-col items-center justify-center gap-2 p-8 text-center">
                        <MaterialDesignIcon iconName="alert-circle-outline" class="size-10 text-red-400" />
                        <p class="text-sm">{t("archives.search_failed")}</p>
                        <button type="button" class="text-xs font-medium text-sem-accent" onclick={getArchives}>
                            {t("archives.retry")}
                        </button>
                    </div>
                {:else if !isLoading && archives.length === 0}
                    <div class="flex flex-1 flex-col items-center justify-center gap-2 p-8 text-center">
                        <MaterialDesignIcon iconName="text-search" class="size-12 text-sem-fg-muted opacity-40" />
                        <p class="text-sm font-medium">
                            {searchQuery ? t("archives.no_results") : t("archives.no_archives")}
                        </p>
                        <p class="max-w-sm text-xs text-sem-fg-muted">
                            {searchQuery ? t("archives.adjust_filters") : t("archives.browse_to_archive")}
                        </p>
                        {#if searchQuery}
                            <button
                                type="button"
                                class="mt-2 text-xs font-medium text-sem-accent"
                                onclick={clearSearch}
                            >
                                {t("archives.clear_search")}
                            </button>
                        {/if}
                    </div>
                {:else}
                    <div class="flex-1 overflow-y-auto">
                        <div class="grid grid-cols-1 gap-3 p-3 sm:p-4 {!viewingArchive ? 'sm:grid-cols-2' : ''}">
                            {#each archives as archive (archive.id)}
                                <ArchiveCard
                                    {archive}
                                    isSelected={viewingArchive?.id === archive.id}
                                    {searchQuery}
                                    {cardPreviewCache}
                                    {nomadMicronWasmActive}
                                    {nomadRenderOptions}
                                    onSelect={openArchive}
                                />
                            {/each}
                        </div>

                        {#if pagination.total_pages > 1}
                            <div class="flex items-center justify-center gap-3 border-t border-sem-border px-3 py-3">
                                <button
                                    type="button"
                                    class="rounded-lg px-3 py-1.5 text-xs font-medium disabled:opacity-40"
                                    disabled={pagination.page <= 1 || isLoading}
                                    onclick={() => goPage(pagination.page - 1)}
                                >
                                    {t("archives.prev_page")}
                                </button>
                                <span class="text-xs text-sem-fg-muted">
                                    {t("archives.page_of", {
                                        page: pagination.page,
                                        total_pages: pagination.total_pages,
                                    })}
                                </span>
                                <button
                                    type="button"
                                    class="rounded-lg px-3 py-1.5 text-xs font-medium disabled:opacity-40"
                                    disabled={pagination.page >= pagination.total_pages || isLoading}
                                    onclick={() => goPage(pagination.page + 1)}
                                >
                                    {t("archives.next_page")}
                                </button>
                            </div>
                        {/if}
                    </div>
                {/if}
            </div>
        {/if}

        {#if viewingArchive}
            <ArchiveViewer
                {viewingArchive}
                {renderedContent}
                {isLoadingViewer}
                {isRecrawling}
                {isWideSplit}
                onClose={closeViewer}
                onRecrawl={recrawlArchive}
                onExport={exportArchiveAsMu}
                onOpenLive={handleOpenInNomadnet}
                onOptOut={optOutNode}
                onDelete={deleteArchive}
                onContentClick={handleContentClick}
            />
        {/if}
    </div>
</div>
